### ISSUE TITLE
Run command for babel

### ISSUE THREAD

**Issue by BitPuffin** [nim-lang/nimble#10]
Babel should have a "run" command that works like the following:

+ `babel run` should run the first defined executable in the foo.babel file
+ `babel run exename` should run the executable called "exename" after building
+ `babel run alias` should run the executable that is bound to an alias. For example if you have an executable called "superlongsoftwarenamethatistoomuchtotype-server" you could define an alias "server" and do `babel run server`

That would be super useful!

**Comment by dom96** [comment]
You can achieve this with the new NimScript support. Also the new ``c`` command does pretty much what you want: ``nimble c -r modulename``.
