### ISSUE TITLE
Split packages.json as directory.

### ISSUE THREAD

**Issue by flaviut** [nim-lang/nimble#101]
@huodon says

> Conflict less , like [homebrew](https://github.com/Homebrew/homebrew/tree/master/Library/Formula),

@dom96 says

> You want each package to have its own file? How does this help with conflicts?

Migrated from https://github.com/nim-lang/packages

**Comment by dom96** [comment]
I'm going to close this since the original reporter did not reply, and I don't see any advantages that this brings.
