### ISSUE TITLE
nimble refresh -> SIGILL: Illegal operation

### ISSUE THREAD

**Issue by alk0** [nim-lang/nimble#1029]
OS: Manjaro (Arch-based), current stable
OpenSSL (just in case): OpenSSL 1.1.1q  5 Jul 2022
Toolchain: 1.6.8, installed via choosenim
nimble v0.13.1 compiled at 2022-09-27 01:28:08
```
$ nimble --debug refresh
Downloading Official package list
     Trying https://github.com/nim-lang/packages/raw/master/packages.json
SIGILL: Illegal operation.
```
Same happens when switching to 1.6.6 or running the corresponding binaries manually:

```
$ cd ~/.choosenim/toolchains/nim-1.6.6/bin
$ ./nimble -v
nimble v0.13.1 compiled at 2022-05-05 01:16:54
git hash: couldn't determine git hash
$ ./nimble refresh
Downloading Official package list
SIGILL: Illegal operation.
Illegal instruction (core dumped)
```

```
$ cd ~/.choosenim/toolchains/nim-1.6.8/bin
$ ./nimble -v
nimble v0.13.1 compiled at 2022-09-27 01:28:08
git hash: couldn't determine git hash
$ ./nimble refresh
Downloading Official package list
SIGILL: Illegal operation.
Illegal instruction (core dumped)
```
What am I doing wrong? Can I fix it on my own? Can it be fixed for everyone?

**Comment by Joao620** [comment]
what I did to get around the error was change to nim version 1.0.0 using choosenim, run the `nimble refresh`, and then change back with `choosenim stable`. Not at all a solution, but now i can continue my day

**Comment by xTrayambak** [comment]
This seems to have been fixed. I can no longer reproduce the crash in both devel and stable.
```
$ nim -v
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
$ nimble -v
nimble v0.14.2 compiled at 1980-01-01 00:00:00
git hash: couldn't determine git hash
```
