### ISSUE TITLE
Why is nimble asking to reinstall all packages on build every time?

### ISSUE THREAD

**Issue by oderwat** [nim-lang/nimble#103]
There must be something I miss because I can't believe that it is the expected behavior that nimble asks to reinstall every single package every time I do a "nimble build"?

Should it not detect that they are installed and skip reinstall until I use some "--reinstall" switch?

**Comment by dom96** [comment]
This is because #88 needs to be implemented.

This also only affects packages that depend on a specific git commit/branch.
