### ISSUE TITLE
could not import: SSL_get_peer_certificate

### ISSUE THREAD

**Issue by overtube** [nim-lang/nimble#1038]
When I use nimble command on terminal and get this error

**Comment by digr8wanka** [comment]
Current release depends on openssl 1.1.1. Install the `openssl-1.1.1` package if you are on a linux based distro.

**Comment by overtube** [comment]
problem was lifted after reinstalling compiler form git and update openssl to 3.0

**Comment by overtube** [comment]
Thank!
