### ISSUE TITLE
Update the token

### ISSUE THREAD

**Issue by ShalokShalom** [nim-lang/nimble#1044]
I refreshed my Github token, and now is that one, that I initially attributed to Nimble, no longer working. 

The README does not contain the word `token` at all.
How to update?

**Comment by ire4ever1190** [comment]
If your nimble directory (`~/.nimble/` on linux, can't remember about windows) you'll find a file called `github_api_token`, put the new token in there (replacing the old one)

Think nimble should maybe delete that on a 401/403 so that the user is taken through the token process again

**Comment by ShalokShalom** [comment]
Can we add that to the documentation, or am I blind and thats already there?
