### ISSUE TITLE
packages.json is cleared before it's overwritten

### ISSUE THREAD

**Issue by ephja** [nim-lang/nimble#106]
Abort at a specific moment and the file will remain empty, and so this error message will appear whenever nimble tries to use it: "Error: unhandled exception: /home/exe/.nimble/packages.json(1, 0) Error: { expected [JsonParsingError]"

**Comment by sky-khan** [comment]
As a side note; it leaves packages.json as an empty file if internet connection is broken while it is trying to update (How do I know ? Because my net connection sucks)

**Comment by Brobin** [comment]
Same issue here. I had to manually update packages.json in order to get it to work.

**Comment by dom96** [comment]
Fixed via 835157ce34798ce1
