### ISSUE TITLE
`nim c` can't resolve packages when NIMBLE_DIR env var is set

### ISSUE THREAD

**Issue by michaelsbradleyjr** [nim-lang/nimble#1061]
I think this might be a problem with Nim, not nimble per se, but I wasn't sure so I'm filing an issue here first.

Using Nim `#version-2-0` installed via choosenim, if I have `NIMBLE_DIR` set in my shell environment, `nim c` is unable to locate installed packages in `${NIMBLE_DIR}/pkgs2/`. In my shell, if I `unset NIMBLE_DIR` then `nim c` works correctly.

With previous versions of nim/nimble, `nim c` finds the installed packages in `${NIMBLE_DIR}/pkgs/` no problem.

**Comment by SolitudeSF** [comment]
nim gets package directories from `nimblepath` define that you can set in your local nim.cfg/config.nims.

**Comment by michaelsbradleyjr** [comment]
Sure, but it still seems to be a change in behavior. Having `NIMBLE_DIR` set in my shell's environment worked perfectly with Nim 1.2, 1.4, 1.6, but with some change introduced on branch `version-2-0` it causes a problem.

**Comment by SolitudeSF** [comment]
yep, devel nim still defaults to `pkgs` when `NIMBLE_DIR` is set. https://github.com/nim-lang/Nim/blob/2620da9bf9994d09da3d5b31b29c95855fb79a41/compiler/commands.nim#L613
