### ISSUE TITLE
nimble develop broken?

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#1064]
After nimble `develop` feature was redesigned I'm struggling to understand how to make it work for me.
I'm having repo `a` and `b`. Both only exist on my machine, not committed anywhere. How do I make `b` see `a`? Previously I would `cd a && nimble develop`, but now it doesn't work.

**Comment by ringabout** [comment]
`nimble develop` has changed its behaviour => https://github.com/nim-lang/nimble#nimble-develop

> -g, --global - Creates an old style link file in the special links directory. It is read by Nim to be able to use global develop mode packages. Nimble uses it as a global develop file if a local one does not exist.

See also https://github.com/nim-lang/nimble/pull/970 https://github.com/nim-lang/nimble/issues/948

**Comment by yglukhov** [comment]
I see, thanks. Apparently `-g` is only available in `0.14.1`, while `koch` provides `0.14.0`, probably that's why it didn't work for me.
