### ISSUE TITLE
[Request] Tag a new release

### ISSUE THREAD

**Issue by yyoncho** [nim-lang/nimble#1070]
Given the important fixes that went in recently, it will be nice if a new release is tagged. Projects using lock files cannot be build with the latest tag: e. g. https://github.com/nim-lang/langserver/issues/34

**Comment by ringabout** [comment]
Please change the version first.

**Comment by ringabout** [comment]
The Nim language ships specific commit of the nimble, which doesn't relies on the tag of nimble. It might be able to ship a moderner nimble which includes the important fixes, though.

**Comment by yyoncho** [comment]
PR at https://github.com/nim-lang/nimble/pull/1071

**Comment by ringabout** [comment]
fixed
