### ISSUE TITLE
No error message when building non-binary packages

### ISSUE THREAD

**Issue by ephja** [nim-lang/nimble#108]
Only warnings are printed:
```
WARNING: using deprecated babelmeta.json file in /home/exe/.nimble/pkgs/babel-0.4.0
WARNING: No .nimble file found for /home/exe/.nimble/pkgs/nim-glfw-0.1.0
WARNING: using deprecated babelmeta.json file in /home/exe/.nimble/pkgs/x11-1.0
```
And it seems like the compiler is never invoked.

**Comment by dom96** [comment]
Try removing ``~/.nimble`` and see if that helps.

**Comment by EXetoC** [comment]
Nope, doesn't help. This seems to be caused by the absence of 'bin' in the package file.

**Comment by EXetoC** [comment]
Actually, the package file did not contain the bin key, so it's no wonder it didn't work. It would be good if the user was notified of that fact.
