### ISSUE TITLE
Passing the --threads:on option to nim

### ISSUE THREAD

**Issue by xyz32** [nim-lang/nimble#109]
This is more of a question that an issue, but I have been looking through the nimble documentation ( https://github.com/nim-lang/nimble/blob/master/developers.markdown#package ) to figure out how to set the "--threads:on" inside nimble. No success.
Can someone point me to where I can find this info?

Thanks.

**Comment by dom96** [comment]
You should set it in a ``.nim.cfg`` file. Here is an example: https://github.com/nim-lang/nimble/blob/master/src/nimble.nimrod.cfg

**Comment by xyz32** [comment]
Ok it works now, just as a note the file name is without a leading ".", so it should be named: `nim.cfg`

**Comment by dom96** [comment]
No. It should be named ``modulename.nim.cfg``. A ``nim.cfg`` file will apply to all modules which usually is not what you want.
