### ISSUE TITLE
project strucure

### ISSUE THREAD

**Issue by bung87** [nim-lang/nimble#1107]
`Package 'aaa' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'aaapkg'`

while readme recommend as `foobar`

the reason directory has `pkg` suffix likely when I run `nim c -r` output `aaa` binary file which cause conflict with `aaa` directory

so what's the design?

**Comment by Araq** [comment]
> so what's the design?

We should remove the `pkg` suffix thing.
