### ISSUE TITLE
`--noColor` flag does not suppress colored output in the terminal

### ISSUE THREAD

**Issue by rivten** [nim-lang/nimble#1110]
When I run `nimble build --noColor` and if there is an error in a file, the output is still colored: the file impacted is bold and Error is written in red.

**Comment by xTrayambak** [comment]
Do you mean as in the Nim compiler output is still colored? I tried to reproduce this bug couldn't do it.
![image](https://github.com/nim-lang/nimble/assets/59499552/912a4a29-00b7-4874-a311-cd13b1708f24)
