### ISSUE TITLE
Cannot uninstall gtk2

### ISSUE THREAD

**Issue by winksaville** [nim-lang/nimble#113]
I tried to uninstall gtk2 and it says I can't because aporia depends on it:
```
$ nimble uninstall gtk2
Looking for gtk2 (any version)...
Checking reverse dependencies...
FAILURE:
  Cannot uninstall gtk2 (1.0) because aporia (0.2.0) depends on it
```
But I've already uninstalled aporia
```
$ nimble list -i
benchmark  [0.3.0]
nake  [1.4]
gtk2  [1.0]
nimble  [0.6.0]
cairo  [1.0]
cmdargsopts  [0.1.0, 0.2.0, 0.3.0]
```
How do I uninstall gtk2, is there any information I can provide that might help debug the problem?

**Comment by dom96** [comment]
How did you uninstall Aporia?

**Comment by winksaville** [comment]
nimble uninstall aporia

**Comment by dom96** [comment]
Does ~/.nimble/aporia-*/ still exist?

**Comment by winksaville** [comment]
Sorry I read the first sentence and not the second, and the answer is that is aporia-* does not exist:
```
$ pwd
/Users/wink/.nimble/pkgs
$ ls -al
total 0
drwxr-xr-x   9 wink  5000  306 Apr  7 08:23 .
drwxr-xr-x   6 wink  5000  204 Feb 17 08:17 ..
drwxr-xr-x  15 wink  5000  510 Apr  6 10:17 benchmark-0.4.0
drwxr-xr-x   9 wink  5000  306 Feb 28 17:49 cairo-1.0
drwxr-xr-x   5 wink  5000  170 Mar 25 12:39 cmdargsopts-0.1.0
drwxr-xr-x   5 wink  5000  170 Mar 31 10:20 cmdargsopts-0.3.0
drwxr-xr-x  16 wink  5000  544 Feb 28 21:54 gtk2-1.0
drwxr-xr-x  13 wink  5000  442 Mar 29 17:33 nake-1.4
drwxr-xr-x   8 wink  5000  272 Mar 25 09:29 nimble-0.6.0
```
This is on mac laptop running 10.10.2 and as you can see its nimble version 0.6.0:

**Comment by dom96** [comment]
Somehow ``~/.nimble/nimbledata.json`` didn't get modified properly. You will likely see the following if you open it:

```
    "gtk2": 
    {
      "1.0": [
        {
          "name": "aporia", 
          "version": "0.2.0"
        }
      ]
    }, 
```

Can you reproduce this? i.e. can you backup your .nimble folder, reinstall Aporia, uninstall it and then try uninstalling gtk2 again?

**Comment by winksaville** [comment]
So I kinda reproduced it, the problem was aporia doesn't install it fails
with an error but the nimbledata.json file has the references to it from
gtk and cario as you suspected.

Here is the failure installing aporia:

*wink-macbookpro2:~ wink$ nimble install aporia*


*Downloading aporia into /tmp/nimble_64080/aporia using git...Found
tags...Cloning latest tagged version: v0.1.1.0Initialized empty Git
repository in /private/tmp/nimble_64080/aporia/.git/remote: Counting
objects: 148, done.remote: Compressing objects: 100% (125/125),
done.remote: Total 148 (delta 88), reused 39 (delta 20), pack-reused
0Receiving objects: 100% (148/148), 396.83 KiB | 0 bytes/s, done.Resolving
deltas: 100% (88/88), done.From git://github.com/nim-lang/Aporia
<http://github.com/nim-lang/Aporia> * tag               v0.1.1.0   ->
FETCH_HEADHEAD is now at 936d88d Merge pull request #47 from
gradha/pr_babel_tweaksSwitched to a new branch 'v0.1.1.0'Looking for gtk2
(>= 1.0)...None found, installing...Downloading gtk2 into
/tmp/nimble_64080/gtk2_1.0 using git...Initialized empty Git repository in
/private/tmp/nimble_64080/gtk2_1.0/.git/remote: Counting objects: 28,
done.remote: Compressing objects: 100% (28/28), done.remote: Total 28
(delta 3), reused 4 (delta 0), pack-reused 0Unpacking objects: 100%
(28/28), done.From git://github.com/nim-lang/gtk2
<http://github.com/nim-lang/gtk2> * branch            master     ->
FETCH_HEAD * [new branch]      master     -> origin/masterHEAD is now at
e7c0a0d gtk2 is gcsafeSwitched to a new branch 'origin/master'Looking for
cairo (any version)...None found, installing...Downloading cairo into
/tmp/nimble_64080/cairo using git...Initialized empty Git repository in
/private/tmp/nimble_64080/cairo/.git/remote: Counting objects: 9,
done.remote: Compressing objects: 100% (9/9), done.remote: Total 9 (delta
0), reused 6 (delta 0), pack-reused 0Unpacking objects: 100% (9/9),
done.From git://github.com/nim-lang/cairo
<http://github.com/nim-lang/cairo> * branch            master     ->
FETCH_HEAD * [new branch]      master     -> origin/masterHEAD is now at
3cf525e Merge pull request #4 from asheb/masterSwitched to a new branch
'origin/master'Installing cairo-1.0/tmp/nimble_64080/cairo/src/cairo.nim ->
/Users/wink/.nimble/pkgs/cairo-1.0/cairo.nim/tmp/nimble_64080/cairo/src/cairo_pragma.nim
->
/Users/wink/.nimble/pkgs/cairo-1.0/cairo_pragma.nim/tmp/nimble_64080/cairo/src/cairoft.nim
->
/Users/wink/.nimble/pkgs/cairo-1.0/cairoft.nim/tmp/nimble_64080/cairo/src/cairowin32.nim
->
/Users/wink/.nimble/pkgs/cairo-1.0/cairowin32.nim/tmp/nimble_64080/cairo/src/cairoxlib.nim
->
/Users/wink/.nimble/pkgs/cairo-1.0/cairoxlib.nim/tmp/nimble_64080/cairo/cairo.babel
-> /Users/wink/.nimble/pkgs/cairo-1.0/cairo.babelcairo installed
successfully.Installing gtk2-1.0/tmp/nimble_64080/gtk2_1.0/src/atk.nim ->
/Users/wink/.nimble/pkgs/gtk2-1.0/atk.nim/tmp/nimble_64080/gtk2_1.0/src/gdk2.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gdk2.nim/tmp/nimble_64080/gtk2_1.0/src/gdk2pixbuf.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gdk2pixbuf.nim/tmp/nimble_64080/gtk2_1.0/src/gdkglext.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gdkglext.nim/tmp/nimble_64080/gtk2_1.0/src/glib2.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/glib2.nim/tmp/nimble_64080/gtk2_1.0/src/gtk2.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gtk2.nim/tmp/nimble_64080/gtk2_1.0/src/gtkglext.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gtkglext.nim/tmp/nimble_64080/gtk2_1.0/src/gtkhtml.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gtkhtml.nim/tmp/nimble_64080/gtk2_1.0/src/gtkmacintegration.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/gtkmacintegration.nim/tmp/nimble_64080/gtk2_1.0/src/libglade2.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/libglade2.nim/tmp/nimble_64080/gtk2_1.0/src/pango.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/pango.nim/tmp/nimble_64080/gtk2_1.0/src/pangoutils.nim
->
/Users/wink/.nimble/pkgs/gtk2-1.0/pangoutils.nim/tmp/nimble_64080/gtk2_1.0/gtk2.nimble
-> /Users/wink/.nimble/pkgs/gtk2-1.0/gtk2.nimblegtk2 installed
successfully.Installing aporia-0.2.0Building aporia/aporia using c
backend...Hint: used config file '/opt/nim/config/nim.cfg' [Conf]Warning:
/private/tmp/nimble_64080/aporia/aporia.nimrod.cfg is deprecated
[Deprecated]Hint: used config file
'/private/tmp/nimble_64080/aporia/aporia.nimrod.cfg' [Conf]Hint: system
[Processing]Hint: aporia [Processing]Hint: glib2 [Processing]Hint: gtk2
[Processing]Hint: atk [Processing]Hint: pango [Processing]Hint: gdk2pixbuf
[Processing]Hint: gdk2 [Processing]Hint: cairo [Processing]Hint:
gtksourceview [Processing]Hint: dialogs [Processing]Hint: os
[Processing]Hint: strutils [Processing]Hint: parseutils [Processing]Hint:
times [Processing]Hint: posix [Processing]Hint: osproc [Processing]Hint:
strtabs [Processing]Hint: hashes [Processing]Hint: streams
[Processing]Hint: cpuinfo [Processing]lib/pure/osproc.nim(779, 6) Warning:
raiseOSError is deprecated [Deprecated]lib/pure/osproc.nim(747, 7) Hint:
'osproc.startProcessAuxFork(data: TStartProcessData)' is declared but not
used [XDeclaredButNotUsed]Hint: pegs [Processing]Hint: unicode
[Processing]Hint: parseopt [Processing]lib/pure/parseopt.nim(59, 34)
Warning: quoteIfContainsWhite is deprecated [Deprecated]Hint: asyncio
[Processing]Hint: sockets [Processing]Hint: unsigned
[Processing]lib/pure/asyncio.nim(11, 7) Warning: sockets is deprecated
[Deprecated]aporia.nim(12, 51) Warning: asyncio is deprecated
[Deprecated]aporia.nim(12, 60) Warning: sockets is deprecated
[Deprecated]Hint: encodings [Processing]Hint: tables [Processing]Hint: math
[Processing]Hint: algorithm [Processing]Hint: settings [Processing]Hint:
utils [Processing]Hint: AboutDialog [Processing]utils.nim(10, 65) Warning:
asyncio is deprecated [Deprecated]Hint: CustomStatusBar
[Processing]CustomStatusBar.nim(41, 24) Error: undeclared identifier:
'False'FAILURE: Execution failed with exit code 256*


Here is the contents of nimbledata.json:

*wink-macbookpro2:~ wink$ cat .nimble/nimbledata.json*
*{*
*  "reverseDeps":*
*  {*
*    "cairo":*
*    {*
*      "1.0": [*
*        {*
*          "name": "gtk2",*
*          "version": "1.0"*
*        }*
*      ]*
*    },*
*    "gtk2":*
*    {*
*      "1.0": [*
*        {*
*          "name": "aporia",*
*          "version": "0.2.0"*
*        }*
*      ]*
*    }*
*  }*


Here is the list of installed items:


*wink-macbookpro2:~ wink$ nimble list -i*
*benchmark  [0.4.0]*
*nake  [1.4]*
*gtk2  [1.0]*
*nimble  [0.6.0]*
*cairo  [1.0]*
*cmdargsopts  [0.3.0]*


And here the uninstall fails:

*wink-macbookpro2:~ wink$ nimble uninstall gtk2*
*Looking for gtk2 (any version)...*
*Checking reverse dependencies...*
*FAILURE:*
*  Cannot uninstall gtk2 (1.0) because aporia (0.2.0) depends on it*

]

**Comment by dom96** [comment]
So the issue is that if a package fails to build during installation it will still be added to nimbledata.json?

**Comment by winksaville** [comment]
Its dependencies are added not "it" at least in my repo case aporia was not
added only gtk2 and cardio.
