### ISSUE TITLE
Package list on the fallback server is out of date

### ISSUE THREAD

**Issue by futureisfoss** [nim-lang/nimble#1144]
```
~ >>>  nimble --verbose install nimlangserver
     Info:  Nimble data file "/home/rokosun/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
    Prompt: nimlangserver not found in any local packages.json, check internet for updated packages? [y/N]
y
    Answer: Downloading Official package list
     Trying https://raw.githubusercontent.com/nim-lang/packages/master/packages.json
   Warning: Could not download: Operation timed out
     Trying https://nim-lang.org/nimble/packages.json
    Success Package list downloaded.
    Reading official package list
nimble.nim(683)          getDownloadInfo

    Error:  Package nimlangserver@any version not found.
     Info:  Nimble data file "/home/rokosun/.nimble/nimbledata2.json" has been saved.
```
Nimble seems to grab the package list from these 2 URLs:
1. https://raw.githubusercontent.com/nim-lang/packages/master/packages.json
2. https://nim-lang.org/nimble/packages.json

I'm experiencing some connectivity issues with the first URL so it uses the next URL as a fallback. The issue is that package list on the second URL is not updated, some of the packages (like `nimlangserver`, `happyx`, etc) are not found there - causing errors when I try to install/update them.

**Comment by xTrayambak** [comment]
This is already a known issue and has already been fixed. Please wait until the next nimble update comes along for your package manager, or try choosenim and switch to the devel channel (I don't know if it applies that for Nimble too).

**Comment by xTrayambak** [comment]
#1139 is the old issue btw. This is a duplicate.

**Comment by futureisfoss** [comment]
Sorry I didn't find the duplicate issue when I looked before, closing this now.
