### ISSUE TITLE
`nimble install nimble` fails

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#116]
Just installed today Nim and nimble on a new Ubuntu 14.10 system. After that, I ran `nimble install nimble` and got

    nimblepkg/version.nim(141, 21) Error: use '^' instead of '-'; negative indexing is obsolete
    FAILURE: Execution failed with exit code 1

**Comment by dom96** [comment]
Try ``nimble install nimble@#head``.

**Comment by andreaferretti** [comment]
Thank you, that works
