### ISSUE TITLE
nimble publish when parsing tags, if whitespace strutils.split() puts empty string in packages.json

### ISSUE THREAD

**Issue by bloomingchad** [nim-lang/nimble#1204]
when you publish using nimble, it asks for tags. if a newbie user is typing the tags,

for example: `"tag1 tag2 tag3 tag4 "`<<<(this last char before ")
the trailing white space at the last will be parsed as a empty string `[""]` into tags field of packages.json

this will result in a ci error where the package_scanner.nim will return
`at line 157:            logPackageError(displayName & " has empty tags")`

wasted ci resources, redundant workflow approvals, wasted time and makes us look buggy.

**Comment by Araq** [comment]
If only the stdlib had something like `splitWhitespace`...
