### ISSUE TITLE
skipFiles not working

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [nim-lang/nimble#1226]
`skipFiles` has no effect with `installExt` or `installDirs`.

### Sample package structure,

```
folder
|- app.nimble
|- src
    |- app.nim
    |- appPkg
        |- utils.nim
        |- protocol.nim
```

### Corresponding nimble file

```nimble
srcDir        = "src"
installExt    = @["nim"]
skipFiles     = @["appPkg/utils.nim"]
```

### Expected Behaviour

All files inside `appPkg` should be copied except `appPkg/utils.nim`

### Actual Behaviour

`appPkg` is copied as it is.

**Comment by xTrayambak** [comment]
It seems like `samePaths` incorrectly returns false when provided with the absolute path of the file during `checkInstallFile` checks.
