### ISSUE TITLE
description field missing of some packages

### ISSUE THREAD

**Issue by pyloor** [nim-lang/nimble#123]
Hi,
currently I got the following error message:

> FAILURE: Package in packages.json file does not contain a description field.

A short grepping shows that the desc field seems mssing on 7 packages

System:
Debian Stretch amd64
nimble v0.6.0 compiled at 2015-05-18 02:55:14
Nim Compiler Version 0.11.2 (2015-05-18) [Linux: amd64]

**Comment by Iancurtis** [comment]
me too . get my foot wet in nim just a hour ago.

**Comment by Iancurtis** [comment]
I guess there's something wrong with json parser.

**Comment by dom96** [comment]
Should be fixed now.
