### ISSUE TITLE
Error: unhandled exception: input(1, 6) Error: : expected [JsonParsingError

### ISSUE THREAD

**Issue by Iancurtis** [nim-lang/nimble#124]
could not  `nimble install docopt` 
error info :
Downloading docopt into /tmp/nimble_4837/docopt using git...
Found tags...
Cloning latest tagged version: v0.6.1
Initialized empty Git repository in /private/tmp/nimble_4837/docopt/.git/
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 21 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (21/21), done.
From git://github.com/docopt/docopt.nim
 * tag               v0.6.1     -> FETCH_HEAD
HEAD is now at c9b4247 v0.6.1
Switched to a new branch 'v0.6.1'
Error: unhandled exception: input(1, 6) Error: : expected [JsonParsingError]

***mac os x*** and ***ubuntu*** got the same error.

**Comment by dom96** [comment]
Move your ``~/.nimble`` to ``~/.nimble_backup`` and try again, it's likely corrupted somehow.

**Comment by Iancurtis** [comment]
HI @dom96 , I moved the ~/.nimble and recompiled nimble ,then updated it ,but  still got the same error

**Comment by dom96** [comment]
That's really strange. Can you install other packages?

**Comment by Iancurtis** [comment]
I tried to install several packages, and got the same error again and again :(

**Comment by dom96** [comment]
Which version of Nim are you using? If devel then try updating and
recompiling.

**Comment by Iancurtis** [comment]
I'd just recompiled nim
`Nim Compiler Version 0.11.2 (2015-05-20) [MacOSX: amd64]`
`Copyright (c) 2006-2015 by Andreas Rumpf`
`git hash: 5d4ee87f3b18f145c77075ac96e303b39015a515`
`active boot switches: -d:release`
but nimble install failed
`[Linking]`
`Hint: operation successful (39456 lines compiled; 3.671 sec total; 89.916MB; Debug Build) [SuccessX]`
`/opt/nimble/src/nimble install`
`Traceback (most recent call last)`
`nimble.nim(920)          nimble`
`nimble.nim(892)          doAction`
`nimble.nim(626)          install`
`nimble.nim(512)          installFromDir`
`nimble.nim(417)          processDeps`
`packageinfo.nim(286)     getInstalledPkgs`
`packageinfo.nim(236)     readMetaData`
`json.nim(1083)           parseJson`
`json.nim(1078)           parseJson`
`json.nim(1054)           parseJson`
`json.nim(1021)           eat`
`json.nim(561)            raiseParseErr`
`Error: unhandled exception: input(1, 6) Error: : expected [JsonParsingError]`
`Error: execution of an external program failed`

**Comment by dom96** [comment]
Try removing ``~./nimble`` once again. I think you may have been caught out by a regression in JSON.

**Comment by Iancurtis** [comment]
done. thx @dom96  :+1:

**Comment by dom96** [comment]
Cool. It works now?

**Comment by Iancurtis** [comment]
yes :D but got another issue 
[https://github.com/nim-lang/Aporia/issues/88](https://github.com/nim-lang/Aporia/issues/88)
