### ISSUE TITLE
`--useSystemNim` is ignored

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/nimble#1251]
Compiling `nimlangserver` with `nimble --useSystemNim install` still builds 2.0.2 compiler.

**Comment by jmgomez** [comment]
Didnt know this existed, a quick look at the code it says: 
` Use system nim and ignore nim from the lock file if any`

It only seems to apply to lock files not to `requires`. Not sure what was the intended design though

**Comment by SolitudeSF** [comment]
after looking further, if required compiler is already fetched and compiled `--useSystemNim` is working and uses system compiler, but it will try to redownload and rebuild required version if it was removed.
