### ISSUE TITLE
Requiring a specific git hash fails

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#129]
A statement like this

    Requires: "nim >= 0.10.3, nim-stringinterpolation#e0746e3"

fails, because the hash will be interpreted as the `branch` variable [at this point](https://github.com/nim-lang/nimble/blob/f7114ca7884d75d1ffc0f2c6e07d8c9a904ebab2/src/nimblepkg/download.nim#L60) (running `git fetch origin --depth 1 e0746e3e` manually produces `fatal: Couldn't find remote ref e0746e3e`). On the other hand:

    Requires: "nim >= 0.10.3, nim-stringinterpolation#master"

also fails, probably in the checkout command.

Probably the syntax for `Requires` should allow to provide both the branch and the hash.

**Comment by dom96** [comment]
I don't think Nimble needs to distinguish between commit hashes and branch names.

**Comment by bluenote10** [comment]
Yes, you are right. The hash determines the branch, so it is definitely better not having to specify them both.

**Comment by timotheecour** [comment]
can't it lead to ambiguities in the rare case a hash matches a branch name?

**Comment by dom96** [comment]
@timotheecour if it's good enough for Git...
