### ISSUE TITLE
"Nimble for developers" - well - it _is_ for developers ;-)

### ISSUE THREAD

**Issue by ozra** [nim-lang/nimble#132]
Separating package creation, and fetching, is kind of weird in my eyes. Everyone using a package, is "basically creating a package" - whether it's kept private or published - but that should be the normative view, imho.
Developers use nimble. And the normal expectancy is that they also want to publish packages.

Perhaps, what I'm saying: rename it to "How To Publish Your Own Modules" or the likes..

**Comment by dom96** [comment]
I think we should merge it with the readme. Thoughts?

**Comment by ozra** [comment]
Yes I agree, it's basic want-to-know intell.

**Comment by zielmicha** [comment]
readme still links to developers.markdown:
> Note: This readme explains how to install and use nimble. It does not explain how to create nimble packages. Take a look at the developers.markdown file for information regarding package creation.

**Comment by dom96** [comment]
Fixed.
