### ISSUE TITLE
http://nim-lang.org/docs/lib.html#nimble-official-packages display

### ISSUE THREAD

**Issue by apense** [nim-lang/nimble#133]
At 8:43pm EST on 5/27/15, the above site gives:
![Uploading Untitled.png…]()

I'm not sure what's happening with the picture attachment, so here is the text:

Nimble

Nimble is a package manager for the Nim programming language. For instructions on how to install Nimble packages see its README.
Official packages

These packages are officially supported and will therefore be continually maintained to ensure that they work with the latest versions of the Nim compiler.

Unable to retrieve package list: JSON.parse: unexpected character at line 1581 column 1 of the JSON data
Unofficial packages

These packages have been developed by independent Nim developers and as such may not always be up to date with the latest developments in the Nim programming language.

Unable to retrieve package list: JSON.parse: unexpected character at line 1581 column 1 of the JSON data

**Comment by dom96** [comment]
Should be fixed soon.
