### ISSUE TITLE
Directory control for `bin`

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#134]
I'm missing control over the `nim -o:...` switch in nimble. This is imho important in order to use nimble as a general build solution for stand-alone applications. As far as I can see, it is only possible to compile `src/main.nim` to the binary `src/main`. I guess in many cases a structure like this may be preferred (separating sources from binaries):

    .
    ├── bin
    │   ├── myapp
    │   └── myapp_converter
    └── src
        ├── converter.nim
        └── main.nim

Is it already possible to build such a structure with nimble?

If not, I propose to allow an (optional) definition of the output bin file for each `bin` statement. For example:

        bin = "src/main.nim" => "bin/myapp"
        bin = "src/converter.nim" => "bin/myapp_converter"

**Comment by dom96** [comment]
Perhaps ``binDir`` would be enough? (and consistent with ``srcDir``).

You should also be able to execute ``nimble c -o:... src/main.nim``

**Comment by bluenote10** [comment]
I also though about having `binDir`, but it has a drawback: It is not possible to chose a different name, and I guess it is not uncommon to have different internal names. Example: I'm currently publishing one of my algorithms (called "HiCS") as a library. The core algorithm is located in `src/hics.nim`. I also want to offer a command line interface for stand-alone use, which I would place in `src/main.nim` or `src/cmdLineInterface.nim`. The binary in `./bin` obviously should not have the internal source name; it should just be `bin/hics`. Without the possibility to specify the names I would again feel the need for a build script, which simply renames the binaries. It would just be nice to reduce any necessity for having build scripts (especially such a silly one).

**Comment by dom96** [comment]
Why don't you just rename ``main.nim`` to ``hics.nim``?

**Comment by strcmp** [comment]
hello, I would also find the requested feature to be useful. I have a file called "main.nim" that imports library code(lets say "hics.nim"), so main.nim is basically just a runner for the library code. I would like the produced binary to be called "hics", though. I used the same names as this issue because it's easier to explain that way.

**Comment by bluenote10** [comment]
This is not possible, maybe my example wasn't clear enough. There already is a `hics.nim` which represents the core algorithm. Used as a library this is what a client would import. And the command line front-end should not be part of the library. This is a common situation for libraries providing command line interfaces where `libname.nim` will be like the core of the library, but there still should be a binary of the same name.

I just think that the internal (source) representation should be decoupled from the (external) binary representation in general. In many cases they will match, but as soon as they do not match the `binDir` approach is not flexible enough.

**Comment by dom96** [comment]
It may not be as convenient but couldn't you simply split your library and main.nim file into two separate packages?

**Comment by gradha** [comment]
@bluenote10 your description fits easily some of my projects. I have say an [xcode_constantine.nim](https://github.com/gradha/xcode_constantine/blob/master/xcode_constantine.nim) file with the command line interface, which imports [xc_pkg/xc_core.nim](https://github.com/gradha/xcode_constantine/blob/master/xc_pkg/xc_core.nim). Or [dropbox_filename_sanitizer.nim](https://github.com/gradha/dropbox_filename_sanitizer/blob/master/dropbox_filename_sanitizer.nim) contains the command line parsing and imports [dbfs_pkg/dbfs_core.nim](https://github.com/gradha/dropbox_filename_sanitizer/blob/master/dbfs_pkg/dbfs_core.nim). In both cases the user gets binaries to run and libraries with a package prefix.

**Comment by bluenote10** [comment]
@dom96 Don't worry about my example. The simplest workaround in my case is not to use `nimble build` but to use a build script. I'm just suggesting this feature to avoid build script necessity, and because I think decoupling sources from binaries is a good thing in general.

(If you are interested: A split into two packages is probably not appropriate in my case: <200 LOC for the command line interface, and having two repositories/readmes might be confusing. This particular project addresses mainly the scientific community (stuff from my PhD), not so much the Nim community. My users will probably never have heard of Nim/Nimble before. Which is why I was brooding over the ease-of-use of cargo vs nimble in the first place.)

**Comment by dom96** [comment]
``binDir`` should now be implemented. I think this is the best solution, and there already was a PR for it :)

**Comment by bluenote10** [comment]
Having the PR merged is good but it is probably not a "solution" in the sense that a basic need like src/bin file name decoupling still calls for having an external build solution and prevents to use nimble for building. Thanks anyway!

**Comment by dom96** [comment]
I just remembered how I solved this in Nimble. Nimble is also a binary/library hybrid, the library is inside a ``nimblepkg`` folder so you must import via ``import nimblepkg/module``.

This is actually documented [here](https://github.com/nim-lang/nimble/blob/master/developers.markdown#hybrids).

**Comment by bluenote10** [comment]
Which is another very good example calling for src/bin independence ;). In my opinion a missing feature in a build tool should not have a negative effect on code style.

**Comment by dom96** [comment]
This is a good enough compromise IMO.

**Comment by jiyinyiyong** [comment]
Should be related https://github.com/nim-lang/nimble/issues/515
