### ISSUE TITLE
Specify and forward custom parameters/options to the nim compiler

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#135]
I haven't found a way store options/parameters for the nim compiler in a `.nimble` file. Think of enabling optimizations, defines, or just thread support.

This would be another important feature in order to use `nimble build` as a general build tool. Let me know if you do not want me to open issues going in that direction for the time being ;).

**Comment by gradha** [comment]
[Configuration files](https://github.com/nim-lang/Aporia/blob/master/aporia.nimrod.cfg) seem to do that.

**Comment by dom96** [comment]
What @gradha said.
