### ISSUE TITLE
Package list not found

### ISSUE THREAD

**Issue by tastyminerals** [nim-lang/nimble#137]
Cannot download package list with nimble.
```
$ nimble install gtk2
Local packages.json not found, download it from internet? [y/N] y
Downloading package list from https://github.com/nim-lang/packages/raw/master/packages.json
Error: unhandled exception: 404 Not Found [HttpRequestError]
```

**Comment by dom96** [comment]
Are you on Arch Linux?

**Comment by tastyminerals** [comment]
yes, I am using one of the arch spinoffs, manjaro

**Comment by dom96** [comment]
Try installing nimble-git from the AUR.

**Comment by tastyminerals** [comment]
Tried it already, same error

**Comment by dom96** [comment]
Then please try compiling nimble manually with the latest compiler (0.11.2).

**Comment by tastyminerals** [comment]
Ok, just installed again. Nimble updated successfully.
