### ISSUE TITLE
Store packages and data in the AppData directory

### ISSUE THREAD

**Issue by Varriount** [nim-lang/nimble#141]
Standard convention in Windows dictates that programs should store their mutable data/storage in one of the three folders in the AppData directory:
 - Roaming, for program data tied to a user account.
 - Local, for program data tied to a specific machine.
 - LocalLow, for program data used by low-integrity programs tied to a specific machine.

Currently Nimble doesn't follow this convention - it stores its data in the users home directory. This is undesirable, mainly because it clutters up the home directory (it isn't even set to be hidden, though for those who have 'view hidden files' on, that wouldn't matter). Furthermore, storing data directly in the user's home directory has the potential to complicate administration of the users profile (by IT staff in a business environment), as group policy and active directory configurations can view a user's profile, and a users application data as separate.
Nimble's package data should probably be put in the Roaming subdirectory, as that will make downloaded/modified packages available to a user across multiple machines (usually in a domain) if an administrator desires.

**Comment by dom96** [comment]
Programs rarely conform to Windows' conventions. But I don't think Nimble packages should be stored there, in fact I'm starting to think that they should be stored in ``~/nimble`` not ``~/.nimble``. But then we are not consistent with other package managers.

In any case, you can change where Nimble installs things by setting ``nimbleDir`` in the config file if you really want this.

**Comment by Araq** [comment]
+1 for getting rid of leading '.' Unixism that it totally alien on Windows.

**Comment by Varriount** [comment]
@dom96 I wasn't only talking about packages - I meant the whole .nimble directory. Currently this can't be done through settings, as the path in which nimble looks for its configuration file is hardcoded.

**Comment by dom96** [comment]
@Varriount That is what ``nimbleDir`` is. You wanna change the path of the configuration file too? How should Nimble know where to look for the configuration file then?

**Comment by Varriount** [comment]
>How should Nimble know where to look for the configuration file then?

@dom96 Well, you can use a path relative to the exe/batch script, or look at a value in the registry, or use an environment variable.

> Programs rarely conform to Windows' conventions.

I think what you mean here is that *ported* or *non-native* programs rarely conform to Window's convention, which is understandable given the difficulty in both porting OS-specific code and maintaining a sane source tree. Most native Windows programs __*do*__ use the AppData directories, or else use the registry (since most program settings easily fit into a key/value schema). The only popular, *native* programs I have on my computers which don't store their data in the AppData directories  are PyCharm/IntelliJ Idea, VirtualBox, and Steam.

In any case, "because other programs do it" isn't a very good reason on its own - it's akin to someone throwing their trash on the sidewalk because "everyone else does it". Granted, my own argument partially relies on such a statement, however it's supported by other reasons (it's *native* convention, and it makes administration easier).


> But then we are not consistent with other package managers.

There's consistency? Let's review the locations of some popular package managers:
 - Python's `pip` stores global packages in the site-packages directory, within Python's own `lib` directory (Usually `C:\Python34\Lib\site-packages`. 
 - Javascript's `npm` stores global packages in it's installation folder ("C:\Program Files (x86)\nodejs\node_modules" I think).
 - Java's `Gradle` installs global packages in a path determined by its configuration file (which is stored in `~/.gradle`).

Please, if there's consistency in any of that, don't hesitate to enlighten me.



Personally, I would prefer it if Nimble followed these conventions on Windows:
 - Store global configuration data in the registry, with overridable defaults in global and project-specific text file locations (and possibly with restricted read/write permissions placed on certain values).
 - Store packages in `~\AppData\Roaming\Nimble` by default.
 - Store the Nimble binary and read-only/write-rarely textual data in `C:\Program Files` by default.

However such drastic changes would probably not go down well, and only confuse the main user base (People who work on both *nix systems and Windows).

**Comment by dom96** [comment]
> However such drastic changes would probably not go down well, and only
confuse the main user base (People who work on both *nix systems and
Windows).

Precisely. I see no advantages to changing the default .nimble location. As
far as I'm concerned this is just bike shedding.
