### ISSUE TITLE
Problem with LibreSSL

### ISSUE THREAD

**Issue by Peter2121** [nim-lang/nimble#142]
I'm trying to install nimble (from github) on PCBSD 10.1. The problem is that OpenSSL is replaced by LibreSSL in the last PCBSD. So the shared libraries searched by nimble do not exist and symlinking the existing LibreSSL libraries I got SSL v2 error (there is no SSL v2 in LibreSSL).
Is there any solution?

**Comment by dom96** [comment]
Compile with dead code elimination enabled perhaps.

**Comment by Peter2121** [comment]
Could you provide more details, please?

**Comment by dom96** [comment]
It seems that the OpenSSL wrapper already forces dead code elimination. Which symbol exactly is missing in LibreSSL?

**Comment by Peter2121** [comment]
[peter@pcbsd-peter ~/nim/nimble/src]$ ./nimble install
could not import: SSLv2_method

**Comment by Peter2121** [comment]
Finally I could get it working - putting openssl libs in separate dir and creating symlinks in /usr/local/lib, but it would be nice to be able to use the system LibreSSL lib...

**Comment by dom96** [comment]
I'm pretty sure this is a Nim bug, not Nimble bug so I will close this. Also, I am planning to get rid of the need for the SSL dependency in Nimble.

**Comment by Angluca** [comment]
Hi, Nimble can't open and echo 'could not import: SSLv2_method' when I update openssl yesterday, How to solve it? :sob:

**Comment by dom96** [comment]
Try compiling with ``--deadCodeElim:on``. I am going to have to get rid of this annoying SSL dependency.

**Comment by crazyproger** [comment]
OSX 10.10.4 even with `--deadCodeElim:on` I'm getting this error. Nim from `master` branch.
Can't install nimble(

**Comment by allochi** [comment]
Same here, I tried with `--deadCodeElim:on` on OSX 10.10.4, still `could not import: SSLv2_method`

**Comment by Angluca** [comment]
Has a temporary solutions.
Find nim/lib/pure/net.nim#212 and change it to newCTX = SSL_CTX_new(SSLv23_method())

**Comment by allochi** [comment]
Hi, thanks for your reply, but it failed again

```
Building nimble/nimble using c backend...
Hint: used config file '/usr/local/Cellar/nimrod/0.11.2/nim/config/nim.cfg' [Conf]
Error: arguments can only be given if the '--run' option is selected
Traceback (most recent call last)
nimble.nim(952)          nimble
nimble.nim(924)          doAction
nimble.nim(650)          install
nimble.nim(527)          installFromDir
nimble.nim(475)          buildFromDir
Error: unhandled exception: Build failed for package: nimble [BuildFailed]
Error: execution of an external program failed
```

**Comment by allochi** [comment]
Ok, sorry, now it works with `newCTX = SSL_CTX_new(SSLv23_method())`, thanks a lot!

**Comment by crazyproger** [comment]
Just pull fresh changes - nimble installed successfully even without `net.nim` patching, thanks!
