### ISSUE TITLE
Latest tag/release incompatible with latest Nim

### ISSUE THREAD

**Issue by jonathonf** [nim-lang/nimble#146]
nimble 0.6 is incompatible with Nim 0.11, but HEAD is.

Please tag a new release of nimble!

Not only will this mean 'nimble install nimble' will succeed, but third-party packagers (and including AUR) will rebuild because of the new release. This will in turn fix those older packages.

**Comment by jonathonf** [comment]
Thank you! :)

**Comment by dom96** [comment]
np
