### ISSUE TITLE
BSD 4 clause license

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/nimble#153]
I've started making Nimble buildroot package and noticed that nimble is on old BSD license. 
```
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by Dominik Picheta.
```
This clause makes Nimble almost legally impossible to incorporate in any projects (especially commercial). FSF recommends not using it in any new projects (http://www.gnu.org/philosophy/bsd.html).

Is this usage of the old BSD license intentional?

**Comment by dom96** [comment]
I just removed that clause. That article makes a good case for not including it. Hopefully people that contributed code to Nimble won't mind that I changed the license this way.
