### ISSUE TITLE
Managing tests

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#154]
A common need for library authors is writing tests for them. Usually, this is done by compiling a test executable. If the library has dependencies, the test executable will need these dependencies as well (plus, optionally, some more of its own). In this case nimble can be used to build the test executable, but this has the consequence of having to distribute the test executable along with the library, which is usually undesirable.

A possibility is to have a separate nimble file just to build the tests, but this is unintuitive and requires repetitions. It would be better if nimble was aware of tests and their dependencies, and there was a way to run tests from nimble.

By the way, this should probably come after [this discussion](http://forum.nim-lang.org/t/1530/3#9597) is settled

**Comment by yglukhov** [comment]
Nimble tasks should help, right?

**Comment by andreaferretti** [comment]
Yes, that solves the bulk of the issue. There is still a small problem, though. What if one needs a particular library just as dependency of a test? A typical case would be that the dependency is a test library, a benchmarking library, a fuzzying library or something like that.

In that case, one should be able to express that the tests need that dependency without making it a transitive dependency of the library itself. This may be a separate issue, though

**Comment by andreaferretti** [comment]
I am closing this in favour of the more explicit https://github.com/nim-lang/nimble/issues/244
