### ISSUE TITLE
Add "libs" option in .nimble file (--passL)

### ISSUE THREAD

**Issue by filcuc** [nim-lang/nimble#157]
I think it could be useful to add an option inside the .nimble file for specifing the linkage of some libraries during the build step.
This should simply add -passL:libname in the build phase.

We should double check if Nim itself handles the conversion of the linker options based on the c++ compiler. Otherwise we should decide if implement it here or inside Nim

See  http://code.dlang.org/package-format?lang=json

**Comment by yglukhov** [comment]
This can now be done with a task or hook, right?

**Comment by dom96** [comment]
Now that I look at this again, I wonder: couldn't this be specified in the .nim.cfg file?

**Comment by yglukhov** [comment]
Also note that you can use `{.passL.}` pragma right in the source code.

**Comment by genotrance** [comment]
Closing this since it can be handled better in the Nim source instead of within Nimble which can handle multiple binaries.
