### ISSUE TITLE
uninstall confirmation prompt is not visible

### ISSUE THREAD

**Issue by kFo** [nim-lang/nimble#159]
$ nimble list -i
nimble  [0.6.2]
compiler  [0.10.3]

$ nimble uninstall compiler

(blinking cursor waiting for input)
(hit enter)
Looking for compiler (any version)...
Checking reverse dependencies...
The following packages will be removed:
  compiler (0.10.3)
Do you wish to continue? [y/N]
## 

Workaround is to hit 'y' at the prompt.

$ nim --version
Nim Compiler Version 0.11.2 (2015-10-02) [Windows: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 8dedfdb236cc50a811ec3423de492368d4ed6329
active boot switches: -d:release

$ nimble --version
nimble v0.6.2 compiled at 2015-10-02 22:48:22

**Comment by dom96** [comment]
What OS is this on? Works fine for me on Windows.

**Comment by dom96** [comment]
Please update, otherwise will need to close this.

**Comment by dom96** [comment]
Closing due to lack of update. Feel free to reopen if you're still experiencing this issue.
