### ISSUE TITLE
cannot find git (on Windows)?

### ISSUE THREAD

**Issue by anta40** [nim-lang/nimble#160]
I already have git in my PATH:
C:\Users\CSL-NB-064\Downloads\Software\Nimrod\nimble-git>git --version
git version 2.5.1.windows.1

Now, when I run something like "nimble install jester", I got:
Downloading git://github.com/dom96/jester/ into C:\Users\CSL-NB~1\AppData\Local\Temp\nimble_3416\githubcom_dom96jester using git...
FAILURE: 'git' not in PATH.

This is the latest nimble, BTW
C:\Users\CSL-NB-064\Downloads\Software\Nimrod\nimble-git>nimble --version
nimble v0.6.2 compiled at 2015-10-22 10:28:08

**Comment by Araq** [comment]
"C:\Users\CSL-NB~1\AppData\Local\Temp\" looks suspicious (old school DOS paths?). What version of Windows do you use?

**Comment by anta40** [comment]
32-bit Windows 10

**Comment by dom96** [comment]
What does the following example produce?

```nim
import os
echo(findExe"git")
```
?

**Comment by anta40** [comment]
The output is an empty line

**Comment by dom96** [comment]
Are you sure ``git`` is in your PATH? Can you check your PATH environment variable and verify that it is there? Maybe you could show us what the contents of your PATH is too?

**Comment by anta40** [comment]
Yes, I have git availabie in PATH

C:\Users\CSL-NB-064\Downloads\Software\Nimrod\nim-git>echo %PATH%
C:\Users\CSL-NB-064\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11\Driver;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\GNU\GnuPG;C:\sbt\;C:\Program Files\Microsoft SDKs\TypeScript\0.8.1.1\;C:\Program Files\nodejs;c:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Python27;C:\Program Files\Flash Magic;C:\Program Files\Java\jdk1.8.0_66\bin;C:\mingw\sjlj\bin;C:\maven\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\gforth;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\AMD\ATI.ACE\Core-Static;C:\Program Files\TortoiseSVN\bin;C:\Program Files\GNU\GnuPG\pub;C:\Program Files\Skype\Phone\;C:\Vim\vim74;C:\scala\bin;C:\mingw\bin;C:\FASM;"C:\Program Files\Git\bin";C:\texlive\2014\bin\win32;C:\8th\bin\win32\

**Comment by dom96** [comment]
``...;"C:\Program Files\Git\bin";...``, seems like ``findExe`` might not support quotes in the PATH.

**Comment by anta40** [comment]
So it's a bug, then?

**Comment by dom96** [comment]
@anta40 it looks like it, can you remove the quotes around `C:\Program Files\Git\bin` from your PATH and see if it then works?

**Comment by anta40** [comment]
@dom96 Sorry for the late reply. It seems I don't enclose it with quotes
![env](https://cloud.githubusercontent.com/assets/16976/13069376/c2d0d308-d4b6-11e5-960f-826141e50ac9.jpg)

I'll try to reinstall git on a path without space, and see if it works.

**Comment by Varriount** [comment]
Spaces shouldn't matter, the path variable is delimited by semicolons.

**Comment by dom96** [comment]
Odd that ``echo %PATH%`` shows the quotes then. In either case, this is a Nim stdlib bug.

**Comment by dom96** [comment]
Let us know if it works when you reinstall Git.

**Comment by PhoenixDeku** [comment]
Hmmm... I have the same error...
And reinstalling Git doesn't work either.

I wanted to run the command "git install opengl".
Well, okay then, PC, I will do that manually.

**Comment by dom96** [comment]
I'm going to close this now as there hasn't been an update to this issue in a while. Feel free to reopen if you're still experiencing this issue.
