### ISSUE TITLE
Backend support for libraries

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#163]
Apparently, now Nimble supports the `backend` annotation. Documentation says: "Specifies the backend which will be used to build the files listed in bin. Possible values include: c, cc, cpp, objc, js".

I think it would be more useful to use this for libraries. One could specify that a certain library is only available for one or more backends, and nimble would fetch it only if the backend of the library matches that of the binary being built.

For instance, I could mark `linalg` as only available for the c or cpp backends, so that trying to use it from js would fail. Pure libraries would be available for all backends.

Is it possible to do something like this?

**Comment by dom96** [comment]
This should be achieved with a [compilation error](http://nim-lang.org/docs/manual.html#pragmas-fatal-pragma).

**Comment by andreaferretti** [comment]
Thank you. Do you have an idea about what would be a reliable way to test if something is being compiled for a native backend? I tried

```nim
when not defined(c) and not defined(cpp):
```

but it does not seem to work with `nim c`

**Comment by dom96** [comment]
I would just check for ``defined(js)`` that's the only non-native backend.
