### ISSUE TITLE
Prevent use of global packages

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#164]
Right now, nimble allows to list dependencies, and retrieves them (if needed) at build time.

This is a step towards reproducible builds, but unfortunately comes with a caveat. If package `foo` is already installed - maybe as a dependency of another project - it will be available at build time even if it is not listed among the project dependencies.

This opens the following scenario:

* user 1 has project A that depends on package `foo`
* when building A, `foo` gets installed
* user 1 also has project B, that **should** depend on `foo`, but forgets to add it to the list of dependencies in the nimble file
* when building B, the previously installed `foo` is used, and user 1 thinks everything is alright, so commits to a repository
* user 2 clones the repository, and tries to build project B, but fails because of the missing dependency `foo`.

To avoid this, `nimble x` commands should only use packages explicitly listed as dependencies (and their transitive dependencies). If this is not possible, maybe there could be a flag enabling this behaviour.

**Comment by dom96** [comment]
This is already done. :)

**Comment by andreaferretti** [comment]
Great! I don't know how I could have missed that!

Seems most of my issues are solved already :-) Sorry for reporting everything this morning, but I had a few little annoyances and decided to post them together
