### ISSUE TITLE
.nimble file ignored.

### ISSUE THREAD

**Issue by shakna-israel** [nim-lang/nimble#166]
I've recently published [nimcat](https://github.com/shakna-israel/nimcat) to see how nimble handles publishing.

It passed all tests and merged.

However, it doesn't install: nimble complains:

```
FAILURE: Specified directory does not contain a .nimble file.
```

The package file I created is ```.nimble```, but I'm guessing from the fact that nimble can't find it, even though it exists, that it needs to have more than just an extension.

e.g. ```nimcat.nimble```.

**Comment by dom96** [comment]
yes, it needs to be ``<project_name>.nimble``

**Comment by shakna-israel** [comment]
Would it make sense for it to not matter in future?

Metadata that's not all that important to a project often gets a ```.name``` so that it hides by default.

**Comment by dom96** [comment]
Nope. This metadata is actually quite important.
