### ISSUE TITLE
NimScript eval aborts Nimble when given a module with an invalid name

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#172]
Possibly somewhat related to #171.

`readPackageInfoFromNims` on a `foo-bar.nimble` file will cause the NimScript eval code to abort Nimble (As far as I can tell)

**Comment by dom96** [comment]
This will not cause problems now because Nimble validates the Nimble file name ahead of time. But it may cause problems in other instances. The general problem is that compiler code can ``quit()`` Nimble instead of reporting an error (which allows Nimble to produce a more meaningful error message).

**Comment by genotrance** [comment]
Compiler is no longer built into Nimble, it is simply invoked with `nim e` so such situations cannot occur anymore.
