### ISSUE TITLE
Feature request: run task from another task

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#176]
The point is to call nim several times during build, while still using nice configuration api, and not `exec` =).

**Comment by dom96** [comment]
What's wrong with ``exec``?

You can call another task by calling ``<task_name>Task()``.

**Comment by yglukhov** [comment]
1. It's nice to have nim configuration in nimble file. Configuration should still be scriptable. It may involve searching for installed sdks, providing custom paths to c compiler, etc.
2. It's nice to have a single convenient way to configure and run nim.
3. Consider a complex nimble file with complex nim configuration logic. Let's say we're building a Javasript. Then you want to add a task to build a server to serve that js. It may depend on the first task. Then let's add another task to run the server. It depends on the second task. Every time adding a new task with a dependency you need to reimplement dependency configuration in a way compatible with `exec`. It may even involve dynamic generation of `.cfg` file, which is really cumbersome. So switching to `exec` way after you already have a `nimble`-way working task may turn out to be a pita. At the end of the day "proficient" nim developers will avoid the `nimble`-way of doing things =)

**Comment by dom96** [comment]
I'm not sure I understand. ``exec "nimble foo"`` is the same as calling the ``foo`` task.

**Comment by yglukhov** [comment]
Oh, tbh i didn't think of `exec "nimble foo"`. Was thinking about `exec nim`. You're right, that may solve my issues. There still remains a constraint that some global state would be hard to share between tasks, but I guess I'll just live with it for now. Thanks.

**Comment by dom96** [comment]
In that case you can call ``<task_name>Task()``, ``task`` just creates a special ``<task_name>Task()`` procedure. I guess I could add a ``runTask`` which calls it for you, but I think that might be an issue for the Nim repo.
