### ISSUE TITLE
Removing a newer version of a bin pkg does not switch bin symlinks

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#177]
- Install two versions (e.g. 0.6.2 and 0.7.0) of Nimble
- The `~/.nimble/bin/nimble` will point to `~/.nimble/pkgs/nimble-0.7.0/nimble`
- `nimble remove nimble@0.7`
- The symlink in `~/.nimble/bin/nimble` still points to `~/.nimble/pkgs/nimble-0.7.0/nimble`

**Comment by oderwat** [comment]
Yes.. and it would be nice if Nimble itself would allow to switch installed versions or .. even could make multiple versions available by symlinking to 'nimble@0.7.0' and 'nimble@0.6.2' :). What do you think?

**Comment by dom96** [comment]
This is actually pretty much a duplicate of #331.
