### ISSUE TITLE
Unable to install nimble under Debian Testing

### ISSUE THREAD

**Issue by ntilotta** [nim-lang/nimble#178]
Nim Compiler Version 0.12.0 (2015-10-27) [Linux: amd64]
git hash: b186493f0143fa8d977b4815e2ecda9f16a43b63

```
/home/ntilotta/Downloads/nimble/src/nimblepkg/options.nim(296, 5) Warning: renameBabelToNimble is deprecated [Deprecated]
Hint: download [Processing]
Hint: packageparser [Processing]
Hint: nimscriptsupport [Processing]
/home/ntilotta/Downloads/nimble/src/nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'
```

**Comment by dom96** [comment]
Probably a Debian packaging issue. I assume you installed Nim via a debian package? (apt-get?)

**Comment by ntilotta** [comment]
Hi, nope I have installed Nim through the website's package (nim-0.12.0.tar.xz), run build.sh and everything works, but the problem is with nimble, when I try to install it, I get the error above.

**Comment by dom96** [comment]
Oh, sorry. To install the latest Nimble you will need Nim devel. For Nim 0.12.0 you should grab Nimble 0.6.2, you can just ``git checkout v0.6.2`` to do that (or download it here https://github.com/nim-lang/nimble/archive/v0.6.2.tar.gz)

That being said, it is odd that the Nim compiler cannot find its compiler sources when the .tar.xz package contains them.

**Comment by ntilotta** [comment]
Thanks for your reply, now I've downloaded the v0.6.2 and when I try to compile with Nim 0.12.0 I get this error this time.
```
use Hash instead; THash is deprecated [Deprecated]
Hint: tools [Processing]
Hint: nimbletypes [Processing]
/home/ntilotta/Downloads/nimble-0.6.2/src/nimblepkg/packageinfo.nim(113, 3) Error: undeclared identifier: 'map'
```

**Comment by dom96** [comment]
Sorry, that really sucks. v0.6.2 is broken with 0.12.0 it seems. At this point I would just grab the devel Nim compiler if I were you. You're better off using devel anyway.

Alternatively you can try grabbing this commit of Nimble, but I cannot guarantee that it will work: ffbd5f5b3ec85a68e17

**Comment by ntilotta** [comment]
This time with ffbd5f5 it has compiled without problems, anyway I think than I will follow your suggestion to use Nim devel instead. Thanks again ^^

**Comment by xyproto** [comment]
Same issue when compiling Nimble 0.7.0 with Nim 0.12.0 on Arch Linux.

    nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'

**Comment by dom96** [comment]
You need Nim 0.12.1

**Comment by xyproto** [comment]
But, 0.12.1 hasn't been released yet. I'm packaging both nim and nimble for Arch Linux. We only package release versions.

**Comment by dom96** [comment]
Sorry, you're going to need to wait for Nim 0.12.2 (or 0.13.0) to be released.

**Comment by xyproto** [comment]
Ok, thanks.

**Comment by DoooReyn** [comment]
I got this error with Nim 0.12.1, too.
Hope for next version to solve it.

> Nim Compiler Version 0.12.1 (2016-01-08) [MacOSX: amd64]

**Comment by dom96** [comment]
@DoooReyn With Nim 0.12.1 it should work. How did you install Nim 0.12.1?

**Comment by DoooReyn** [comment]
@dom96 Sorry for that. I try `sh deinstall.sh` to avoid using `koch` and reinstall by using `nim e install_nimble.nims`, now nimble works.

**Comment by xyproto** [comment]
As an apropos, Rust and the Rust package manager Cargo are released in lockstep to avoid conflicting versions.

**Comment by dom96** [comment]
@xyproto were they also in lockstep before Rust 1.0 was released?

**Comment by xyproto** [comment]
Yes.

Cargo is included in the Rust release binary, even though it is a separate project. This was also the case for Rust 0.12. ([source](https://github.com/rust-lang/rust/blob/master/RELEASES.md)).

**Comment by kamilchm** [comment]
Same error with Nim 0.13.0 and Nimble 0.7.0 :(
It could save time for many people if this will be noted in compiling instructions ...
I tried to build Nimble package for NixOS without success after few hours :/

**Comment by dom96** [comment]
@kamilchm This simply shouldn't happen anymore. Did you follow instructions in the [readme](https://github.com/nim-lang/nimble#unix) precisely?

**Comment by kamilchm** [comment]
It may be only NixOS issue cause its pure nature. I tried to rewrite your instruction to nix expression and I think I got it all https://github.com/kamilchm/nixpkgs/commit/c40cbf55c05d19ca9ec63e2507190296b099ec8d
Is something missing there?

**Comment by dom96** [comment]
It could be the fact that you are creating a symlink. It's possible that Nim does not follow symlinks, if that is the case then this is a Nim bug.

**Comment by kamilchm** [comment]
Changed to ``cp`` and got same error :/
https://github.com/kamilchm/nixpkgs/blob/nimble/pkgs/development/tools/nimble/default.nix

**Comment by dom96** [comment]
oh, I think I know the problem then. You're checking out the ``0.7.0`` tag of Nimble, my fix for ``vendor/nim`` is in HEAD.

**Comment by kamilchm** [comment]
Works on ``HEAD``. Thx!
It may be worth to release ``0.7.1``?

**Comment by cjhanks** [comment]
I am still experiencing this issue:
```
$> nim --version
Nim Compiler Version 0.13.0 (2016-01-23) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: a121c3f9eb2a348b9d6ae03ffd01aab26a238c30
active boot switches: -d:release
```

Nimble
```
$> git describe       
v0.7.0-8-g670bcec
$> nim c -r src/nimble.nim
Hint: system [Processing]
....
nimblepkg/options.nim(297, 5) Warning: renameBabelToNimble is deprecated [Deprecated]
Hint: download [Processing]
Hint: packageparser [Processing]
Hint: nimscriptsupport [Processing]
nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'
```

Is there anything apparently wrong with my versions?

**Comment by dom96** [comment]
Make sure you have HEAD of Nimble and are using the new installation
instructions in Nimble's readme.

It seems like I should release 0.7.2...

**Comment by cjhanks** [comment]
Thanks, I was missing: `git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim`
