### ISSUE TITLE
Nimble 0.7.0 requires nim >= 0.12.1

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#182]
Nimble 0.7.0 requires nim >= 0.12.1 according to nimble.nimble and http://forum.nim-lang.org/t/1912 but Nim 0.12.1 has not been released yet.
Was 0.7.0 meant to be named -dev or -alpha instead?

**Comment by dom96** [comment]
Nope. I guess I could have made it ``0.7.1``, but it is a Nimble **release**. Nimble's version shouldn't be based on what Nim it depends on IMO.
