### ISSUE TITLE
doc2 task

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#189]
Nim handles the generation of documentation through the `doc` and `doc2` commands. Usually, this requires some configuration parameters (e.g. `docSeeSrcUrl`), hence I had used nimscript to run the task, like this

```
task gendoc, "generate documentation":
  --define: cublas
  --docSeeSrcUrl: https://github.com/unicredit/linear-algebra/blob/master
  setCommand "doc2", "linalg"
```

When doing the same in nimble, though, I get an error stating that nimble does not know the `doc2` task (even though it is native to nim, like `c` or `js`).

**Comment by dom96** [comment]
It's native to nim, but not to Nimble. setCommand sets the command for Nimble, not Nim. You need to use ``exec``.

**Comment by andreaferretti** [comment]
Using `exec` breaks the task DSL. One has to pass everything as a big string instead of passing options via nimscript. Not that this is a big deal (just two options in my case) but I do not see a good reason not to support it in the same way as `c` or `js`

**Comment by dom96** [comment]
Sorry. On second thought you are right. The documentation generator also accesses each module's imports so it makes sense.

**Comment by andreaferretti** [comment]
Any update on this?

**Comment by dom96** [comment]
Not really. There are a bunch of [high priority issues](https://github.com/nim-lang/nimble/issues?q=is%3Aissue+is%3Aopen+label%3A%22High+Priority%22) which I need to fix before I get to this one.
