### ISSUE TITLE
nimble version 0.6.4 incorrectly reported as 0.6.2

### ISSUE THREAD

**Issue by Toenex** [nim-lang/nimble#193]
Only a minor issue but confusing at the moment as you have to explicitly checkout nimble v0.6.4 when using Nim 0.12.0.

Steps to reproduce (no need to actually build it)

 `git update`
 `grep src/nimble.nim nimbleVersion`
 **>`nimbleVersion = "0.7.0"`**

 `git tag v0.6.4`
 `grep src/nimble.nim nimbleVersion`
**>`nimbleVersion = "0.6.2"`**

 `git tag v0.6.2`
 `grep src/nimble.nim nimbleVersion`
**>`nimbleVersion = "0.6.2"`**

 `git tag v0.6`
 `grep src/nimble.nim nimbleVersion`
**>`nimbleVersion = "0.6.0"`**

**Comment by dom96** [comment]
In which situation is this a problem?

**Comment by Toenex** [comment]
The instruction on the main git page explicitly advises using 0.6.4 with Nim versions less than 0.12.1.  If you follow those instructions and checkout and build the code tagged as v0.6.4 it reports as 0.6.2 when run with the `--version` argument.  A user is likely to be confused by this (I was, my git skills are limited and thus assumed a mistake on my part).  Further because the version numbering is also used by the installer it appears to overwrite the existing 0.6.2 installation.

Whilst it may be there are no functional differences between 0.6.2 and 0.6.4 versioning should be consistently reported by the repo and the resultant build.

**Comment by dom96** [comment]
You're right. It is confusing. In the future I will branch off and update the version, right now I don't think there is much to be done. A new version of Nim should soon be released at which point this issue will no longer be of relevance.
