### ISSUE TITLE
Sorted "nimble list -i"?

### ISSUE THREAD

**Issue by oderwat** [nim-lang/nimble#194]
I think it may be of help if `nimble list -i` would sort its output. That would make it easier to skim for some modules one has in mind.

Of course you can do that with `nimble list -i | sort -f` ... but if it is easy implemented I think sorting the output would be a nice touch.

**Comment by dom96** [comment]
Sure. Should be easy to implement.

**Comment by oderwat** [comment]
So easy that even I could do it :)

https://github.com/nim-lang/nimble/pull/197

**Comment by dom96** [comment]
Fixed via #197.
