### ISSUE TITLE
undeclared identifier 'map' when compiling

### ISSUE THREAD

**Issue by JorySchossau** [nim-lang/nimble#198]
I get this error compiling from the latest master nim, and devel nim. Not something I've observed before updating nim and nimble repos.

**Comment by dom96** [comment]
I don't think this is a bug.

From readme:

>The latest version of Nimble (0.7.0) requires a version of Nim greater than 0.12.0.

**Comment by JorySchossau** [comment]
Thanks; I must've missed something trying with devel last time.

**Comment by dom96** [comment]
Please reopen if you can't get it to compile with devel.
