### ISSUE TITLE
Nimble package is broken due to 'nimble/src/nimblepkg/nimscriptsupport.nim(290, 20) Error: undeclared identifier: 'getModule''

### ISSUE THREAD

**Issue by frol** [nim-lang/nimble#200]
`getModule` was recently introduced to `nimscriptsupport.nim` in commits https://github.com/nim-lang/nimble/commit/5d55a5f7a21a3a960c10a70cf3534b0a348759d4 and https://github.com/nim-lang/nimble/commit/ca99ad7d21b1a735ccc100cf2d202668e2b236ba. This cause the following error when I try to do `nim compile --run "src/nimble" build`:

```
...
compiler/semstmts.nim(1079, 6) Hint: 'sem.isForwardDecl(s: PSym)' is declared but not used [XDeclaredButNotUsed]
Hint: scriptconfig [Processing]
Hint: nimconf [Processing]
/opt/nimble-master/src/nimblepkg/nimscriptsupport.nim(87, 9) Warning: Special variable 'result' is shadowed. [ResultShadowed]
/opt/nimble-master/src/nimblepkg/nimscriptsupport.nim(290, 20) Error: undeclared identifier: 'getModule'
```

**Comment by frol** [comment]
BTW, I have Nim compiled from the `devel` branch. Everything used to work fine 18 days ago.

**Comment by dom96** [comment]
How long ago did you compile Nim? You might need to update your installation.

**Comment by frol** [comment]
I compile them together in one Dockerfile: https://github.com/frol/docker-alpine-nim/blob/master/Dockerfile

**Comment by frol** [comment]
Oooooops, it seems I have always used master branch of Nim... Trying to build it now from devel... Sorry

**Comment by frol** [comment]
Yes, building Nim from the `devel` branch instead of `master` has fixed the issue. What is the point of having `devel` and `master` branches?

**Comment by dom96** [comment]
The idea is that ``master`` is always the latest release of Nim, whereas the ``devel`` branch is where development takes place.

**Comment by dom96** [comment]
Glad you got it working!

**Comment by frol** [comment]
The missing part here is that nimble has only `master` branch and Nimble `master` cannot be compiled with Nim `master`.

**Comment by frol** [comment]
Interesting, I cannot compile the latest release of nimble (0.7.0) with the latest release of Nim (0.12.0). The error is just the same: `nimble-0.7.0/src/nimblepkg/nimscriptsupport.nim(290, 20) Error: undeclared identifier: 'getModule'`

**Comment by dom96** [comment]
Yes. You can't. Nimble 0.7.0 requires Nim 0.12.1!

**Comment by frol** [comment]
And where is the 0.12.1?

**Comment by dom96** [comment]
That's Nim ``devel``.

**Comment by frol** [comment]
Ok, I see.

P.S. IMHO, the development cycle is broken here. People usually release a new version of a product when all dependencies are ready (released).
