### ISSUE TITLE
Document how to persist compiler flags with Nimble

### ISSUE THREAD

**Issue by Xe** [nim-lang/nimble#202]
How would I go about adding `--threads:on` or any other compiler flags in general to a Nimble built project?

**Comment by dom96** [comment]
Use a .nim.cfg file (or the new nimscript equivalent, not sure what the extension for that is), example here: https://github.com/nim-lang/nimble/blob/master/src/nimble.nim.cfg

**Comment by Xe** [comment]
Ah, I see. Do you know where documentation on that is?

**Comment by dom96** [comment]
Good question. @Araq ?

**Comment by Araq** [comment]
Well we deprecated the configuration files in favour of Nimscript so that we don't have to document the configuration file syntax ... ;-)

**Comment by dom96** [comment]
@Araq I don't think you can get away with it like that :P

Anyway, going to close this.

**Comment by blaiseli** [comment]
After reading <https://github.com/nim-lang/nimble/blob/master/readme.markdown> and the above discussion, I do not understand, as of january 2018, what is the recommended way to set compile options when using nimble. The documentation mentions of a `src/nimble.nim.cfg`, of a `nim.cfg`, but it seems that having a `src/<modulename>.nim.cfg` file as recomended in an [older issue](https://github.com/nim-lang/nimble/issues/109) still works.

However, the above discussions states that this is deprecated. So where am I supposed to put the compile option? In the `.nimble` file of my project?
And if so, what are the variable that can be set, besides the ones documented in <https://github.com/nim-lang/nimble/blob/master/readme.markdown>?

Are there examples of how to do this somewhere?

**Comment by dom96** [comment]
> However, the above discussions states that this is deprecated. So where am I supposed to put the compile option? In the .nimble file of my project?

"nimscript" != ".nimble file". What @Araq is referring to above is a .nims file. I think the .nim.cfg file will remain functional for a while yet.

**Comment by dom96** [comment]
I will reopen this as a documentation issue to make sure this is documented.

**Comment by jblindsay** [comment]
Has there been any progress made on adding this documentation. Today I wanted to evaluate the new --gc:arc flag in v1.2 and I realized that I have no idea how to set this flag in my Nimble package and cannot find the answer anywhere online. I suspect that those who have been coding with Nim for some time are just familiar with the way this is done but it would be so useful to see an example of setting Nim compiler flags in a Nimble package for those who are still learning.

**Comment by SolitudeSF** [comment]
@jblindsay nimble has nothing to do with setting compiler flags, use nim.cfg or config.nims for that. https://nim-lang.org/docs/nimc.html#compiler-usage-configuration-files

**Comment by jblindsay** [comment]
@SolitudeSF Thank you for your response. Do you have an example of a Nimble based Nim project that uses a config.nims file to set compiler flags that a newbie could look at?

**Comment by SolitudeSF** [comment]
@jblindsay https://github.com/kaushalmodi/std_vector/blob/master/config.nims
https://github.com/search?p=2&q=filename%3Aconfig.nims&type=Code

**Comment by NightMachinary** [comment]
## example
https://github.com/nim-lang/nimble/blob/master/src/nimble.nim.cfg is a simple example of just adding some flags, which is just what I wanted:
```
--path:"$lib/packages/docutils"
#--noNimblePath
--path:"$nim/"
--path:"./vendor/nim"
-d:ssl
-d:nimcore # Enable 'gorge' in Nim's VM. See https://github.com/nim-lang/Nim/issues/8096
```
