### ISSUE TITLE
Can't publish nimble package

### ISSUE THREAD

**Issue by andot** [nim-lang/nimble#209]
when I run:

```
nimble publish
```

I got the following output:

```
Please create a new personal access token on Github in order to allow Nimble to fork the packages repository.
Your default browser should open with the following URL: https://github.com/settings/tokens/new
Personal access token: deaba2d8cc60d0861dd86d5b924c5cef99e778d0
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(914)          doAction
publish.nim(128)         publish
publish.nim(34)          getGithubAuth
httpclient.nim(495)      getContent
httpclient.nim(476)      get
httpclient.nim(449)      request
httpclient.nim(426)      request
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. [HttpRequestError]
```

**Comment by dom96** [comment]
Damn. Forgot that `nimble publish` depends on SSL.

**Comment by karantin2020** [comment]
Hi. Will you do something? The problem exists yet

**Comment by dom96** [comment]
@karantin2020 You can easily fix it yourself by compiling Nimble manually with the ``-d:ssl`` flag.

**Comment by k0pernicus** [comment]
Hi dom96,
It seems the problem is still exists.
I try to compile Nimble manually with the ```-d:ssl``` flag, but I've got an error again:  
```
Traceback (most recent call last)
nimble.nim(969)          nimble
nimble.nim(921)          doAction
publish.nim(128)         publish
publish.nim(34)          getGithubAuth
httpclient.nim(496)      getContent
httpclient.nim(477)      get
httpclient.nim(449)      request
httpclient.nim(426)      request
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. [HttpRequestError]
```

**Comment by dom96** [comment]
Are you sure you're running the version that you compiled?

Keep in mind that if you compile ``nimble`` with ``-d:ssl``, like so: ``nim c -d:ssl src/nimble``. But then **also** run ``./src/nimble install``, nimble will recompile **without** that flag and install that version!

**Comment by k0pernicus** [comment]
Mmmh...
I just use this command line to compile and install the new version of ```nimble```: ```nim -d:release c -r src/nimble install```.

Also, during the installation, I've got ```nimble-0.7.0 already exists. Overwrite? [y/N]``` - so the ssl version is running after that, no?
Did I miss something?

**Comment by dom96** [comment]
That command runs ``src/nimble install`` which itself rebuilds ``src/nimble`` (but without the ``-d:ssl`` flag). To get around this you can add ``-d:ssl`` to this file: https://github.com/nim-lang/nimble/blob/master/src/nimble.nim.cfg

**Comment by dom96** [comment]
I know it's a bit redundant in this case for Nimble to recompile itself again, but that's just how Nimble's ``install`` command works.

**Comment by dom96** [comment]
To illustrate this another way. The command ``nim -d:ssl c -r src/nimble install``, executes the following:

```
nim c -d:ssl src/nimble
./src/nimble install
```
The ``./src/nimble install`` command then executes:

```
nim c -d:release src/nimble
cp src/nimble ~/.nimble/pkgs/nimble-ver/nimble
ln -s ~/.nimble/bin/nimble ~/.nimble/pkgs/nimble-ver/nimble
```

**Comment by k0pernicus** [comment]
Ow ok, thank you for this information.
Do you want to let nimble as this state or can I just check the code to update it and make the installation more "comfortable"?

**Comment by k0pernicus** [comment]
So, basically, I just have to put the flag ```-d:ssl``` in ```src/nimble.nim.cfg``` and run ```./src/nimble install```?

**Comment by dom96** [comment]
Removing ``-d:ssl`` was done on purpose to remove the dependency on OpenSSL. That said, it will be added again because it breaks things and people don't like Nimble pulling package lists over unencrypted HTTP.

**Comment by k0pernicus** [comment]
Fine - thanks for the help :-)
