### ISSUE TITLE
nimble 0.7.0 Cannot retrieve packages.json through SSL

### ISSUE THREAD

**Issue by nigelnquande** [nim-lang/nimble#210]
Nimble 0.7.0 on a fresh install of Nim 0.13.0 does not support downloading the `packages.json` file from an HTTPS URL on Windows 8.1+ or GNU/Linux. (This issue does not occur on Windows 7.) When attempting to run `nimble refresh`, the following results:
```
me@debian-vm:~$ nimble refresh
Downloading "Official" package list
Trying http://irclogs.nim-lang.org/packages.json...
Could not download: Connection timed out
Trying http://nim-lang.org/nimble/packages.json...
Could not download: Connection timed out
Trying https://github.com/nim-lang/packages/raw/master/packages.json...
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(892)          doAction
nimble.nim(97)           update
nimble.nim(78)           downloadList
httpclient.nim(569)      downloadFile
httpclient.nim(495)      getContent
httpclient.nim(476)      get
httpclient.nim(449)      request
httpclient.nim(426)      request
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. [HttpRequestError]
me@debian-vm:~$ 
```

I have managed to download the `packages.json` file using `wget`, but there seems to be no option to tell `nimble` to use a local JSON file as the `packages.json` file. supplying `--nimbleDir ~/.nimble` returns `Error: unhandled exception: No such file or directory [OSError]`.

# Work-around:

```
cd ~/.nimble
wget https://raw.githubusercontent.com/nim-lang/packages/master/packages.json
cp packages.json ./packages_official.json
cp packages.json ./packages_temp.json
```

**Comment by dom96** [comment]
This is by-design. You have to compile Nimble yourself with SSL support.

That being said, it looks like this will need to be changed back due to #209.

**Comment by yinso** [comment]
@dom96 - how do you compile nimble with ssl support?

Looking at #209 you say use `-d:ssl`, but sorry as a noob where do I add it? I add it to the end of `nim c -r src/nimble install` and it errors out:

```
Error: unhandled exception: Unknown option: --d [NimbleError]
Error: execution of an external program failed: '/Volumes/HD2/Users/yc/code/nimble/src/nimble install -d:ssl'
```
Adding it to beginning as `nim c -d:ssl -r src/nimble install` compiles ok but still throw the same `HttpRequestError`.

```
$ nimble update
Downloading "Official" package list
Trying http://irclogs.nim-lang.org/packages.json...
Could not download: Connection refused
Trying http://nim-lang.org/nimble/packages.json...
Could not download: Connection refused
Trying https://github.com/nim-lang/packages/raw/master/packages.json...
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. [HttpRequestError]
```

It seems that if `https` is included in the mirror list for nimble, it makes more sense to enable ssl by default or the error will occur.

Thanks.

**Comment by yinso** [comment]
@dom96 - never mind, I figured out where to place `-d:ssl` flag. Thanks.

**Comment by sergiotapia-papa** [comment]
@dom96 lol found another "thanks I solved it" with no actual solution thread. How exactly can I solve this?

I run `nimble run myproject` and get:

`Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]`

**Comment by dom96** [comment]
is it Nimble that's failing with this error or your program? Can you run `nimble refresh`?

If so, then just create a myproject.nim.cfg file and add `-d:ssl` in there.

**Comment by sergiotapia-papa** [comment]
The solution was a nim.cfg file in the root folder.

It's contents:

`-d:ssl`

Then `nimble run myproject` worked fine again - hope this helps would be users

**Comment by dom96** [comment]
It's important to note that any program written in Nim which uses httpclient can throw this exception if it attempts to request a https url and if it hasn't been compiled with -d:ssl.

The origins of this issue are really old now (back when we tried to avoid the openssl dependency). But nowadays this should never happen for Nimble, so if you're running `nimble run` or `nimble c -r` it's unlikely to be a Nimble problem, but rather something to do with the package you're using or your own code.

**Comment by dom96** [comment]
> lol found another "thanks I solved it" with no actual solution thread. How exactly can I solve this?

Also, if you're running into this kind of frustration, keep in mind that you can always join [IRC/Discord/Gitter](https://nim-lang.org/community.html) and ask. You'll likely get very quick help.
