### ISSUE TITLE
Update version to actual 0.7.2

### ISSUE THREAD

**Issue by karantin2020** [nim-lang/nimble#211]
after installation of nimble 0.7.2 `nimble -v` shows version 0.7.0.
It is important to see actual version after installation and nimble update (`nimble install nimble`).

Info about version 0.7.0 confusing a little

**Comment by dom96** [comment]
Yeah. My fault for rushing the release. Sounds like I need a document which outlines everything I need to update when making a release.

**Comment by dom96** [comment]
https://github.com/nim-lang/nimble/wiki/Releasing-a-new-version
