### ISSUE TITLE
Nimble website like npm?

### ISSUE THREAD

**Issue by hwclass** [nim-lang/nimble#219]
Hi all,

Nim lang is promising the future so the package manager of that lang is needed to be presented well. Is there any website to build in the further plans? If not, I would like to be the volunteer and waiting for the supporter about that idea as well to work with.

Update: I have found that one called "[Nimble Explorer](http://nimble-explorer.com/)" for searching packages. Is it the official one or not? 

Thanks.

**Comment by dom96** [comment]
Hello @hwclass,

A website is certainly planned, but none of us have the time to implement it. It would be absolutely brilliant if you could help out.

@ekarlso did some initial work on this: https://github.com/ekarlso/nim-packages. It would be a good idea to look into that project first. Unfortunately it was never finished and I myself am not sure how far off it is.

I will do as much as I can to help out, but I've got a lot of other commitments at the minute which mean that my time is limited.

Let me know if you have any questions.

**Comment by rishavs** [comment]
i was working on one where i used github pages and had a client side search interface on the package json. Stopped when i found nimble explorer as it is the exactly same thing.

I think we can contact the guy who made it, fork it over and make it nicer looking.
And maybe even get it on the official domain as 

`nimble.nim-lang.com`

**Comment by dom96** [comment]
@FedericoCeratto is working on one as well.

**Comment by FedericoCeratto** [comment]
Beta version at https://nimble.directory/

**Comment by dom96** [comment]
For reference, here is the repo: https://github.com/FedericoCeratto/nim-package-directory
