### ISSUE TITLE
`nimble build` is claims to be debug, but has no debug information.

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimble#221]
According to the `readme.md`, a simple nimble build is a debug build in contracst to a `nimble install`, but when I do compile my project with `nimble build`, and then start the project with gdb, gdb does not find the debug information.

```
~/proj/nim_debug_test/ nimble build                            
Building nim_debug_test/nim_debug_test using c backend...
[...]
Hint:  [Link]
Hint: operation successful (19116 lines compiled; 1.135 sec total; 25.261MB; Debug Build) [SuccessX]
~/proj/nim_debug_test/ gdb nim_debug_test 
[...]
Reading symbols from nim_debug_test...(no debugging symbols found)...done.
(gdb)
```

the project only has two files:
nim_debug_test.nimble:

```
# Package

version       = "0.1.0"
author        = "Arne Döring"
description   = "foobar"
license       = "MIT"
bin           = @["nim_debug_test"]

# Dependencies

requires "nim >= 0.12.1"
```

nim_debug_test.nim:

```
import strutils

proc foobar(a:string) : string =
  var letters = 0
  var digits  = 0
  var other = 0

  for c in a:
    if c.isAlpha: letters += 1
    if c.isDigit: digits += 1
    if not c.isAlphaNumeric: other += 1

  "$1 - $2 - $3".format(letters, digits, other)

echo foobar("hallo Welt 123")
```

**Comment by Araq** [comment]
Debugging information is generated with ``--debugger:native`` not by the absense of ``-d:release``.

**Comment by krux02** [comment]
but `--debugger:native` is a nim argument, according to nimble -h there is no way to pass it to nimble.

**Comment by dom96** [comment]
``nimble c --debugger:native nim_debug_test.nim`` (is it not ``--debuginfo``?).

Alternatively, you can add it to your Nim config file. A debug build doesn't mean that it's ready for GDB, but perhaps we should explain that in the docs :)

**Comment by dom96** [comment]
@krux02 maybe you could create a PR? ;)

**Comment by aidansteele** [comment]
> A debug build doesn't mean that it's ready for GDB

Out of interest, what does it mean? Does it just imply that optimisations aren't performed by the compiler?

I would be happy to submit a PR with improved documentation, but want to clarify my understanding first.

**Comment by krux02** [comment]
Yes I also don't understand this part. In my head it works like the g++ compiler flags. There is an optimization level you can declare with e.g: `-O2`, and completely orthogonal to that you can declare weather you want to have debug information or not in the binary with `-g`. 

So what does "debug build" mean, when it doesn't mean "has debug information"?

@dom96 the way you describe to pass `--debugger:native` to nimble also forces me to chose one file to debug. But how to I add debug information to the whole project/package/library?

**Comment by dom96** [comment]
To understand what a debug build is it's best to look at what a release build is. A debug build happens by default. But when you specify `-d:release` then many debug checks are disabled for better performance as shown here: https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L49

The option which adds extra information for GDB is not enabled by default though, which is why you need to pass ``--debuginfo`` when compiling. A "debug build" is known by that name because it includes stack traces in the program when it crashes.

**Comment by krux02** [comment]
Then I would prefer not to use the term `debug build`. I would just write that it has some runtime checks enabled that would be disabled in a release. I can only speak for myself here, but for me a "debug build" has debug information enabled.

**Comment by dom96** [comment]
That is the term for it though, and it does include debug information. The problem is that there are multiple levels of debug information I guess.

**Comment by krux02** [comment]
Then, is there any reason not to include debug information in the debug build?

**Comment by dom96** [comment]
That's a question for @Araq. I'm not sure.

**Comment by Araq** [comment]
It includes lots of debug information which you can access via ``getStackTrace()``, so it is a debug build. It doesn't make GCC produce debug information since not everybody needs that and it used to increase  build times measurably.

**Comment by rishavs** [comment]
Hi

A followup question.
I have a build failure issue but i only get an unhandled exception error. Is there any way of getting verbose debug info for the "nimble build" process?

**Comment by dom96** [comment]
@rishavs the message output has been improved, you should try it now.

**Comment by cdunn2001** [comment]
I don't think `--debugInfo` nor `-d:debugger:native` is passed along to **nim** for `nimble test`. Should I open a separate Issue for this?

**Comment by dom96** [comment]
That's an even deeper level of debug info. I don't think Nimble should pass that, you should compile your test with those flags manually and then run the executable using gdb/lldb yourself.

**Comment by cdunn2001** [comment]
That's fair. But then `nimble` should exit with an error -- i.e. either pass along the flag or reject it.
