### ISSUE TITLE
Windows. Program crashes when control-c if compiled with --threads:on

### ISSUE THREAD

**Issue by maratkhafizov** [nim-lang/nimble#222]
How to reproduce:

- make a file`ctrlctest.nim`: 
```nimrod
while true:
  discard
```

-  compile:
```
nim c --threads:on ctrlctest.nim
```
- run:
```
ctrlctest.exe
```
- press `control-c` on windows shell while program is running

Note that `control-c` and `setControlCHook` work well if you compile without `--threads:on` switch

Nim version: Nim Compiler Version 0.13.0 (2016-01-19) [Windows: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

OS: windows 7 x64

**Comment by dom96** [comment]
Shouldn't this be reported in the [Nim](https://github.com/nim-lang/nim) repo?

**Comment by dom96** [comment]
Going to close this as it does not concern this repo. Please report in the Nim repo if it's still a problem.

**Comment by maratkhafizov** [comment]
Yes, sorry, I have mistaken.
