### ISSUE TITLE
Nim and Nimble bundling

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#234]
Currently Nimble is somewhat bundled with Nim. [1]
Can you please conform to one of the two models?
A) Nimble is part of Nim.
- They are released with the same version. The HEAD of the Nimble master repo is included in the Nim release tarball and zip
- Nimble can require Nim's source code to build
- The devel version is build from the HEAD of the Nim devel repo and the HEAD of the Nimble master repo

B) Nimble is a Nim application.
- Nimble versioning is independent from Nim. The latest Nimble release can be included, optionally, in the Nim release tarball and zip
- Nimble cannot require a git clone of Nim to build
- The devel version of Nimble is build from the HEAD of the Nimble master repo and the latest Nim release

[1] The current status can be confusing to the users; it makes it impossible to package Nimble as a Nim application; it also lead to [Nim bug 3918](https://github.com/nim-lang/Nim/issues/3918)

**Comment by dom96** [comment]
B). It's bad enough that c2nim/nimsuggest/nimfix/nimgrep/nimweb are/were inside Nim's repo.

**Comment by Araq** [comment]
A). B) doesn't work.

**Comment by dom96** [comment]
Discussion relating to this starting at 16:56 UTC in http://irclogs.nim-lang.org/11-08-2016.html

**Comment by dom96** [comment]
It seems that some people are also having trouble with the ``nimscriptapi.nim`` file (my book's tech proofer ran into this). Maybe we should just compile that into the damn executable and be done with it.

**Comment by dom96** [comment]
Nimble is now packaged with Nim. Each time Nim is released, the latest tagged version of Nimble is included in the package.
