### ISSUE TITLE
Nimble doesn't understand that an aliased package is already installed

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#236]
If a package is listed in package.json under a different name from the name specified in its .nimble file, Nimble keeps re-downloading the package each time you run `nimble build` or `nimble install`, then prompting you whether the existing package should be overwritten.

An example of such existing package is `nimyaml`. This issue can be reproduced by adding `nimyaml` dependency to any nimble file.

**Comment by andreaferretti** [comment]
@endragor This is annoying, but the solution for `nimyaml` is to remove packages named `yaml` or` nimyaml`, and then depend on `yaml` (`nimyaml` has been renamed to `yaml` precisely to avoid this error, and the older `yaml` package has been deprecated and removed from the packages repo)

For me, the simplest solution is simply:

* to document that the name in the packages repo must agree with the name of the nimble file, and
* to actually enforce this when accepting a PR to the packages repository
