### ISSUE TITLE
`nimble publish` results in large diff due to changing ordering of entry values

### ISSUE THREAD

**Issue by euantorano** [nim-lang/nimble#241]
I published a package yesterday using `nimble publish` and it [resulted in a very large diff](https://github.com/nim-lang/packages/pull/367) due to the entries being changed around, as can be seen in the following screenshot of the diff:

![Nimble publish resulting PR](http://i.imgur.com/xCFCo4q.png)

**Comment by dom96** [comment]
Fixed via https://github.com/nim-lang/Nim/commit/9b365ddfddc14f3387134948d1828d1d515a44b1 (thanks @Araq!)
