### ISSUE TITLE
Dependencies for tests or benchmarks

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#244]
When developing a library A, there should be a way to depend on a particular library B only for test purposes, without making it a transitive dependency of A. A typical case would be that the dependency is a test library, a benchmarking library, a fuzzying library or something like that.

In that case, one should be able to express that the tests need that dependency without making it a transitive dependency of the library itself.

What would be a good way to express this in nimble?

**Comment by dom96** [comment]
This will be handled by task level dependencies. #482
