### ISSUE TITLE
Installation error: cannot open 'httpclient'

### ISSUE THREAD

**Issue by mrLSD** [nim-lang/nimble#245]
Ubuntu 16.04
Nim Compiler Version 0.14.3 (2016-08-02) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

```
git clone https://github.com/nim-lang/nimble.git
cd nimble
nim -d:release c -r src/nimble -y install
```

Message:

> Hint: used config file 'src/nimble.nim.cfg' [Conf]
> Hint: system [Processing]
> Hint: nimble [Processing]
> nimble/src/nimble.nim(4, 8) Error: cannot open 'httpclient'

Any idea?

**Comment by dom96** [comment]
Can you compile other pieces of Nim source code? ``httpclient`` is part of the stdlib so something is wrong with your Nim install.

**Comment by mrLSD** [comment]
I remove from

>  /usr/local/bin

 and recompile Nim and Nimble, put it to 

> $HOME/nim/bin

and that's all right.
Really strange.
