### ISSUE TITLE
Document how to test packages

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#246]
When developing a package a certain issue arises. You have a `tests` directory in the root of your project, but then how do your tests import your package?

In Python you solve it like this:
http://docs.python-guide.org/en/latest/writing/structure/#test-suite

**Comment by thompson4822** [comment]
Is there a known way of getting around this? I'm really eager to write some unit tests for my code and my project structure is with the separate src/test directories ...

**Comment by dom96** [comment]
You can place a ``nim.cfg`` file inside the tests directory with ``--path:../src`` inside it.

**Comment by thompson4822** [comment]
Thanks for the feedback. While I wasn't quite able to get this to work, changing my tests task in Nimble did the trick with the argument you suggested. Though it sounds crazy, I'm really excited to start writing tests :-)

**Comment by dom96** [comment]
Glad you got it working :D
