### ISSUE TITLE
could not load: (ssleay64|libssl64).dll

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/nimble#257]
I'm getting this error when running Nimble. I've installed openssl, the best match I see it adding to PATH is called libssl-1_1-x64.dll. Renaming it to libssl64.dll produces `could not import: SSL_library_init`.

I downloaded dlls.zip from nim-lang.org and put ssleay64.dll beside nimble.exe, but this doesn't help.

**Comment by moigagoo** [comment]
UPD: Putting both libeay64.dll and ssleay64.dll beside nimble.exe solves the issue. The error message should point that libeay64.dll is necessary as well.

**Comment by dom96** [comment]
That's a Nim issue, this seems like the most relevant issue: https://github.com/nim-lang/Nim/issues/4849
