### ISSUE TITLE
"Error: unhandled exception: Build failed for package: nimble_test [BuildFailed]" on nimble build

### ISSUE THREAD

**Issue by rishavs** [nim-lang/nimble#266]
Hi

i created a project using "nimble init". 

In it i added a folder called "src" and one called "bin". 
In the src folder, i have a simple nimfile called main.nim which contains 
`echo "test"`
in it. 
i added `srcDir = "src"`
`binDir = "bin"` and `bin = @["main.nim"]` entries in the nimble file. 
i was expecting that using "nimble build" will compile the main.nim in src into main.exe in bin,
but i get 
`Error: unhandled exception: Build failed for package: nimble_test [BuildFailed]`
instead

My project is here
https://github.com/rishavs/nimble_test/

the error stack is:

```
PS C:\Users\rsharan\Documents\GitHub\nimble_test> nimble build
Looking for sdl2 (any version)...
Dependency already satisfied.
Building nimble_test/main.exe using c backend...
Traceback (most recent call last)
nimble.nim(1004)         nimble
nimble.nim(949)          doAction
nimble.nim(605)          build
nimble.nim(323)          buildFromDir
Error: unhandled exception: Build failed for package: nimble_test [BuildFailed]
```

I am on windows 10 anniversary edition.
Nim is:

```
PS C:\Users\rsharan\Documents\GitHub\nimble_test> nim --version
Nim Compiler Version 0.15.2 (2016-10-23) [Windows: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: 5cb50364eb1f70677f619882cfafbd3ede45356f
active boot switches: -d:release
```

**Comment by dom96** [comment]
Works for me on OS X.

I assume compiling the main.nim file manually works, right?

What version of Nimble do you have?

**Comment by rishavs** [comment]
Hi @dom96 

I am assuming this bug is only in windows 10. On Glitter other users on MacOS and Linux didnt get it either.

My nimble version is 

```
PS C:\WINDOWS\system32> nimble -v
nimble v0.7.10 compiled at 2016-10-23 10:31:22
```

**Comment by crohlfs** [comment]
Hi there, I'm also getting this error on Windows 10. After adding extra logging (echoing the error) I got

```'C:\Program' not in PATH.```

After making this change to add quotes around nimBin https://github.com/crohlfs/nimble/commit/4fa4404df831f10e072e872580bca0a57f0a83b5 it seems to be fixed. Not sure if this change would have side effects on other systems or not.

@rishavs let me know if this does the trick for you

**Comment by rishavs** [comment]
@crohlfs 
Chris,
Unfortunately i am still getting the error.

I opened nimble.nim in `C:\Program Files\Nim\dist\nimble\src\nimble.nim`

I changed the line 319 to
`      doCmd("\"" & getNimBin() & "\" $# $# --noBabelPath $# $# \"$#\"" %
`
after saving this change, i redid `nimble build` in my test folder.

I am still getting the unhandled exception.

Is there any step which I missed?

Also, how do i echo the error like you did?

PS. you will need to make the same change in line 631 as well. otherwise the console will show a wrong path.

**Comment by crohlfs** [comment]
I think you will need to make sure to install nimble from source, outlined here: https://github.com/nim-lang/nimble#installation, so that it includes your code changes. After building this version of nimble make sure it takes priority over your existing one.

To echo the error I think it was `echo getLastError()` after `except NimbleError:` before it raises the new exception.

**Comment by rishavs** [comment]
@crohlfs 

all right. your fix works. 

I added your fork of nimble as a package then deleted all existing nimble.exe files in my existing nim installation and replaced them with the newly compiled nimble.exe

`PS C:\Users\rsharan\Documents\GitHub\nimble_test> nimble build
Looking for sdl2 (any version)...
Dependency already satisfied.
Building nimble_test/main.nim using c backend...
Hint: used config file 'C:\Program Files\Nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: main [Processing]
CC: nimble_test_main
CC: stdlib_system
Hint:  [Link]
Hint: operation successful (10368 lines compiled; 2.005 sec total; 15.504MiB; Debug Build) [SuccessX]`

Thanks a lot!. Hope your PR is picked up soon.

Now I have an associated bug.
nimble put the compiled file in the bin folder as "main.nim" instead of "main.exe"
manually changing the extension is enough to run it, but i was perplexed for a moment.
Did you get the same issue?

**Comment by crohlfs** [comment]
Good to hear it did the trick.

Building your test project correctly compiles to main.exe for me:

`Building nimble_test/main.exe using c backend...`

Can't help you there :P

**Comment by rishavs** [comment]
yep. I edited my comment. I was being an idiot and made some changes to the project nimble file

**Comment by rishavs** [comment]
Paging @dom96 

Can we pick this PR on priority? Otherwise, the Build command will be broken for win10 users.

**Comment by dom96** [comment]
Thanks again for investigating the issue and creating a PR to fix it! You guys are awesome :)

Now that #279 is merged I shall close this issue.
