### ISSUE TITLE
`cargo test` like functionality for nimble

### ISSUE THREAD

**Issue by tekjar** [nim-lang/nimble#267]
Cargo has this convenient way of running all the unit tests and integration tests in one go with `cargo test`. Similar feature in nimble would be great.

**Comment by dom96** [comment]
I guess Rust has a built-in unit testing mode. Nim doesn't have anything like that, instead you are expected to write your own scripts which test your software as done in this repository.

This is now documented: https://github.com/nim-lang/nimble#tests

So the idea is that you create a task which defines what should happen when ``nimble test`` is executed. Hope this is good enough!
