### ISSUE TITLE
Simplify dependencies on unofficial packages

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#270]
Consider the use-case of a company or a team that has internal Nim packages hosted on private Git server (pretty common use case for any language/package manager being used in production). As I understand from the documentation, currently there are two nuisances that stand on the way here:

1. Everyone on the team (or in the company) has to create their own configuration with a package list URL after cloning a project that depends on an unofficial package.
2. Someone has to manage a global package list.

Ideally, everyone should be able to just clone the repo and run `nimble build` without any additional steps. Project maintainers should be able to just add the dependency, without having to deal with some external package lists.

So the suggestion is to extend .nimble format to allow easy dependency on internal packages. Ideally, no `packages.json` should be involved. Just being able to specify Git URL directly would be great. This is something that's supported by any existing major package manager.

**Comment by dom96** [comment]
> Just being able to specify Git URL directly would be great. This is something that's supported by any existing major package manager.

This is already supported by Nimble.

**Comment by dom96** [comment]
https://github.com/nim-lang/nimble#nimble-install

> A URL to a repository can also be specified, Nimble will automatically detect the type of the repository that the url points to and install it.

Perhaps we should emphasise this :)

**Comment by endragor** [comment]
So what's the syntax for specifying such dependency? Say, I want a package `foo` located at `https://github.com/foogroup/foo.git` version `1.0.0`. What's the syntax for specifying that in .nimble file?

If it's supported, it makes sense to show the syntax under "Dependencies" section.

**Comment by dom96** [comment]
```
requires "https://github.com/foogroup/foo.git 1.0.0"
```

**Comment by endragor** [comment]
Alright, so the name can be replaced with the link. Thanks a lot!
