### ISSUE TITLE
reverseDeps not properly updated on uninstall of package

### ISSUE THREAD

**Issue by vsajip** [nim-lang/nimble#271]
I had an earlier version of Nim and `nimble 0.7.4`, `compiler 0.14.3` packages installed.

I then upgraded to Nim 0.15.2 and ran `nimble install nimble`, which successfully installed `nimble 0.7.10` and its dependency `compiler 0.15.3`. I then ran `nimble uninstall nimble@0.7.4`, which completed successfully, but then `nimble uninstall compiler@0.14.3` failed because the now-uninstalled `nimble 0.7.4` depends on it. I saw that in `nimbledata.json` under `reverseDeps`, there was still an entry for `0.14.3` under `compiler` with  the `nimble 0.7.4` reference. It seems like either `nimble uninstall` needs to update `reverseDeps` to remove references to packages that get uninstalled, or ignores references to packages that have been uninstalled when checking dependencies.

**Comment by dom96** [comment]
I believe I experienced a similar bug (https://github.com/nim-lang/nimble/issues/201).

What would help is if you tried to reproduce this, from a fresh ~/.nimble directory (you can back up your current one). Then please tell me the steps that you have taken so that I can reproduce it as well.

**Comment by vsajip** [comment]
Will installing an older version of `nimble` also install an older version of `compiler`? I tried installing `nimble@0.7.4` with nimble 0.7.10 and it failed, apparently after pulling the latest `compiler` package.

```
c:\nim\lib\system.nim(1111, 69) Error: ambiguous call; both json.contains(node: JsonNode, val: JsonNode) and tools.contains(j: JsonNode, elem: JsonNode) match for: (JsonNode, JsonNode)
Build failed for 'nimble@0.7.4', would you like to try installing 'nimble@#head' (latest unstable)? [y/N]
```
To test this properly one would need to be able to set up a test repo with specific versions of packages and install from that, is there any simple way of doing this for test purposes?

**Comment by dom96** [comment]
> Will installing an older version of nimble also install an older version of compiler?

No, I believe Nimble has depended on ``compiler#head`` for quite some time, which we should probably change.

Can you reproduce this with a different package? That way we can rule out problems related to different version of Nimble.

> To test this properly one would need to be able to set up a test repo with specific versions of packages and install from that, is there any simple way of doing this for test purposes?

Could you maybe find existing packages that have some tagged versions? (``nimble list --ver``)

**Comment by vsajip** [comment]
Not sure I can do so easily - does nimble not support installing from local directories where I could set up test packages?

**Comment by dom96** [comment]
It does, just run ``nimble install`` in the package's directory.

**Comment by dom96** [comment]
Any luck?

**Comment by dom96** [comment]
I will eventually simplify how reverse dependencies work, this should fix any remaining issues: https://github.com/nim-lang/nimble/issues/287

**Comment by vsajip** [comment]
> Any luck?

Sorry, no, not had a chance to look at it again ... too busy with other work :-(

**Comment by dom96** [comment]
No worries :)

**Comment by dom96** [comment]
I made some changes to how Nimble handles reverse deps. Hopefully this won't be a problem anymore :)
