### ISSUE TITLE
dll dependencies and cmd files

### ISSUE THREAD

**Issue by ephja** [nim-lang/nimble#276]
Running executable files indirectly via cmd files, which is the approach that nimble has taken on Windows, is problematic because it doesn't seem to allow DLL dependencies to be placed in the directory containing the executable file in question. Are there ways around this issue on Windows, or is the only solution to manually add the directory for each individual binary package to the search path, the effect of which would be to refer directly to `nake.exe` for example rather than `nake.cmd` when typing `nake` into a command prompt?

The current solution is actually the standard approach on Windows, but it would be nice to have a shortcut. Perhaps it can be done similarly to how installers do it, either with a nimble flag or implicitly by stating so in a configuration file.

**Comment by dom96** [comment]
Good question. Will need to think about a solution for this.

**Comment by Araq** [comment]
> Running executable files indirectly via cmd files, which is the approach that nimble has taken on Windows, is problematic because it doesn't seem to allow DLL dependencies to be placed in the directory containing the executable file in question.

Huh? Maybe the .cmd files are not generated properly, but this shouldn't be an issue at all. Windows picks up DLLs next to the .exe anyway.

**Comment by dom96** [comment]
@ephja Could you confirm whether this is actually an issue?

**Comment by genotrance** [comment]
Time to close this one if no update.
