### ISSUE TITLE
Cannot install nimble on Ubuntu 16.04

### ISSUE THREAD

**Issue by alekcacko** [nim-lang/nimble#299]
Following this tutorial:

1. git clone https://github.com/nim-lang/nimble.git
2. cd nimble
3. nim c src/nimble
4. src/nimble install

I fail the step 3.

Output:

lib/nim/system.nim(1, 2) Error: redefinition of 'system'

Installed nim version:
Nim Compiler Version 0.12.0 (2015-11-02) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

**Comment by dom96** [comment]
Nim 0.12.0? You need to upgrade to Nim 0.15.2.

**Comment by alekcacko** [comment]
Thank you for the info.
