### ISSUE TITLE
Nimble reads all packages unnecessarily

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#301]
I just updated to the latest nimble version, and nothing works anymore. It seems that launching any tasks makes nimble read all the packages installed by nimble (even previous versions, such as older versions of nimble itself), and failure to do so makes the whole task fail.

This is what happens when I try to launch **any** nimble task

```
  Executing task test in /home/papillon/esperimenti/spills/spills.nimble
  Executing task tests in /home/papillon/esperimenti/spills/spills.nimble
  Verifying dependencies for spills@0.1.1
   Warning: Installed package 'nimsuggest@0.1.0' is outdated or corrupt.
        ... Package did not pass validation: File inside package 'nimsuggest' is outside of permitted namespace, should be named 'nimsuggest.nim' but was named 'sexp.nim' instead. This will be an error in the future.
   Warning: Installed package 'compiler@0.15.3' is outdated or corrupt.
        ... Package did not pass validation: File 'docgen_sample.nim' inside package 'compiler' is outside of the permitted namespace, should be inside a directory named 'compiler' but is in a directory named 'doc' instead. This will be an error in the future.
   Warning: Installed package 'compiler@0.12.0' is outdated or corrupt.
        ... Package did not pass validation: File 'docgen_sample.nim' inside package 'compiler' is outside of the permitted namespace, should be inside a directory named 'compiler' but is in a directory named 'doc' instead. This will be an error in the future.
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Installed package 'nimble@0.7.10' is outdated or corrupt.
        ... More info: Could not read package info file in /home/papillon/.nimble/pkgs/nimble-0.7.10/nimble.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     home/papillon/.nimble/pkgs/nimble-0.7.10/nimble.nimble(1, 21) Error: cannot open 'src/nimblepkg/common'.
      Hint: The corrupted package will need to be removed manually. To fix this error message, remove /home/papillon/.nimble/pkgs/nimble-0.7.10.

```

**Comment by andreaferretti** [comment]
As far as I can tell, this is the consequence of two problems:

* nimble seems to enter into the directory of every version of every package installed ever, and try to validate it - before the latest update, it would only do that for packages listed as dependencies
* for some reason, many existing packages do not pass validation now

**Comment by dom96** [comment]
> nimble seems to enter into the directory of every version of every package installed ever,

Not sure whether that is actually the case or whether the reason is that more warnings are now generated so you notice it.

I don't know when you installed ``nimble@0.7.10`` but it seems to be affected by an issue with its .nimble file (which imports the ``common`` module to remove duplicated version number definitions). The hint given by Nimble is exactly what I would recommend that you do, perhaps move that folder out of there instead of deleting so that you can restore it later (although I can't think of a reason why you'd want to keep an old version of Nimble installed anyway).

**Comment by dom96** [comment]
In any case, I will investigate why Nimble loads all packages when it shouldn't have to.

**Comment by andreaferretti** [comment]
Yeah, I know I could remove the offending packages, but I opened the issue quickly because it seemed quite a major regression. The issue is on a computer which I will not be using for a few days now that I am back from holidays - on the other ones, I can just postpone the update of nimble until this is fixed, so if you need any info I can use that to try and understand what is going wrong.

**Comment by andreaferretti** [comment]
The issue seems to arise [here](https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/packageparser.nim#L343).

Apart from the issue at hand, I don't think it is a good idea to walk and validate the whole package directory, as its content are destined to grow forever

**Comment by dom96** [comment]
Yes, you are correct. Nimble should be loading the package list lazily. This will work around your issue, but it won't change the fact that Nimble cannot read the ``nimble@0.7.10`` package info. It would be good to figure out the cause of that.

What happens when you run the following?

```
/home/papillon/.nimble/pkgs/nimble-0.7.10/nimble list -i
```

**Comment by andreaferretti** [comment]
The command you gave correctly lists the installed packages:

```
bigints  [0.4]
c2nim  [0.9.8]
classy  [0.0.1]
compiler  [0.15.3, 0.12.0, 0.15.2]
memo  [0.2.0]
nimblas  [0.1.1]
nimble  [0.7.0, 0.7.10, 0.6.2, 0.8.0]
nimboost  [0.3.4]
nimfp  [0.3.5]
nimsuggest  [0.1.0]
opencl  [1.0]
pymod  [0.1.0]
random  [0.5.3]
spills  [0.1.1]
```

**Comment by andreaferretti** [comment]
By the way, I found that one of the warnings is:

```
   Warning: Installed package 'nimblas@0.1.1' is outdated or corrupt.
        ... Package did not pass validation: File 'common.nim' inside package 'nimblas' is outside of the permitted namespace, should be inside a directory named 'nimblas' but is in a directory named 'private' instead. This will be an error in the future.
```

Since this is about a package of mine, I figured I should fix it, but I am not sure how.

From what I understand, the convention of using a `private` directory is being deprecated? The suggestion hints that a directory called `nimblas` (like the package itself) should be used. Does this mean that this directory will be made private?

Many of my libraries follow the convention of having various modules under `pkgname/modname.nim` and a single file `pkgname.nim` that just exports all submodules, so that one can do either fine grained imports (such as `import rosencrantz/core`) or import the whole thing at once (`import rosencrantz`). Will this still work in the future or `rosencrantz/core` and such will be private?

**Comment by dom96** [comment]
> The command you gave correctly lists the installed packages:

Oh yes... I just realised that it will do because in that case nimble doesn't read the package's .nimble files (it just looks at the directory names in ~/.nimble/pkgs). What about when you run ``/home/papillon/.nimble/pkgs/nimble-0.7.10/nimble dump /home/papillon/.nimble/pkgs/nimble-0.7.10/nimble.nimble``?

> Since this is about a package of mine, I figured I should fix it, but I am not sure how.

The convention for ``private`` directories remains. But this directory should itself also be namespaced, i.e. it should be moved into a ``nimblas`` directory. Does that make sense?

**Comment by andreaferretti** [comment]
It fails on its own nimble file:

```
Using custom nimscriptapi.nim defined in /home/papillon/.nimble/pkgs/nimble-0.7.10/nimblepkg
Hint: used config file '/home/papillon/.nimvm/versions/devel/config/nim.cfg' [Conf]
FAILURE: Could not read package info file in /home/papillon/.nimble/pkgs/nimble-0.7.10/nimble.nimble;
  Reading as ini file failed with: 
    Invalid section: .
  Evaluating as NimScript file failed with: 
    home/papillon/.nimble/pkgs/nimble-0.7.10/nimble.nimble(1, 21) Error: cannot open 'src/nimblepkg/common'.
```

About private directories: ok, I will just move it then!

**Comment by dom96** [comment]
So Nimble 0.7.10 is showing the exact same issue reading that .nimble file as the latest Nimble?

**Comment by andreaferretti** [comment]
Yes, but apparently before version 0.8 it was not the case that nimble would read and validate all existing packages before doing anything

**Comment by dom96** [comment]
The code for ``processDeps`` is still the same for 0.7.10: https://github.com/nim-lang/nimble/blob/v0.7.10/src/nimble.nim#L258

**Comment by dom96** [comment]
I'm not sure what could have changed between these versions. Are you sure that executing the task works with Nimble 0.7.10?

**Comment by andreaferretti** [comment]
It seems that `getInstalledPkgs` is changed - for instance `pkg = readPackageInfo(nimbleFile, options, onlyMinimalInfo=false)` vs `pkg = readPackageInfo(nimbleFile, options, true)`.

Maybe reading more than the minimal info triggers the error?

I am sure it used to work, as nimble 0.7.10 was the latest version I had and I was using it daily until I executed `nimble install nimble@#head` yesterday

**Comment by dom96** [comment]
oh, I missed that. Nice catch.

This was in fact a bug, ``getInstalledPkgs`` shouldn't return minimal package info (we have ``getInstalledPkgsMin`` for that :)

The definition of Nimble's .nimble is still corrupt though. This issue just didn't surface because its .nimble file was never read. The correct solution is to remove it.

I will improve this code to read packages lazily.

**Comment by andreaferretti** [comment]
Great! :-D
