### ISSUE TITLE
Nimble does not show output when passing flag `--run`

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#303]
I relied heavily on this feature in order to run tests. For instance, trying to clone https://github.com/andreaferretti/patty and running `nimble test` should result in compiling and running that library tests.

With the latest version of Nimble, tests are compiled but not run anymore.

Also, possibly other flags are not passed to the compiler anymore. With the previous design, all flags passed to the `nimble` command used to be passed to the compiler. If they are not passed anymore (I am not sure), it becomes impossible to compile some programs

**Comment by andreaferretti** [comment]
It seems that I was wrong: nimble *does* run the tests, but does not show the output, so for correct test there is nothing shown.

This is definitely less of an issue, but I think it should not swallow the output anyway

**Comment by dom96** [comment]
Output for ``nimble c``, ``nimble cpp``, ``nimble doc`` etc. will now be shown by default. Other output is hidden behind the ``--debug`` flag (unless an error occurs IIRC).

**Comment by andreaferretti** [comment]
Great! The only thing is that nimble changes the output color (unittest was recently updated to use a color scheme that will work on white terminals, while the output of nimble is less readable) but this is a minor issue. A similar issue exists with the output of the compiler, which uses color to display information in a more readable way.

It would be nice if there was an option to show raw output (without buffering it, adding indentation or changing color). It may be useful also to write tasks whose output needs to be predictable (maybe because it is piped in other commands)

**Comment by dom96** [comment]
Please create a separate issue for this.
