### ISSUE TITLE
Error in parsing version

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#304]
With latest nimble, I cannot run any task in [linalg](https://github.com/unicredit/linear-algebra) (e.g even `nimble tasks` fails).

```
Error: unhandled exception: Unexpected char in version range: a [ParseVersionError]
```

The file used to be parseable before, and as far as I can tell there is nothing wrong in the version numbers there

**Comment by dom96** [comment]
This was a good catch :)

**Comment by andreaferretti** [comment]
Thank! :-)
