### ISSUE TITLE
Show raw output

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#305]
Nimble changes the output color and formatting when executing tasks. Some tools, such as `unittest` or  the compiler itself, use color to display information in a more readable way.

It would be nice if there was an option to show raw output (without buffering it, adding indentation or changing color). This may also be useful in order to write tasks whose output needs to be predictable - maybe because it is piped in other commands.

**Comment by andreaferretti** [comment]
After some days of usage, I find the new behaviour really limiting.

Buffering all the output (and mangling it as well) hinders the usage of nimble as a task runner. Some tasks may never return (maybe a nimble task is used to start a server), others may take a long time, during which a user receives no feedback.

The advantages of the new behaviour are, as far as I can tell, only cosmetic, but the problems that the new output creates are real :-(

**Comment by dom96** [comment]
That's fair. I agree, but I think that it should be contextual. i.e. if you are running a custom task then sure, the output should be live. But for things like ``git clone package.git`` I don't think it's important, it's just noise.

**Comment by evacchi** [comment]
As far as I can tell this is still an issue in devel. If you want to see live output you can work it around by resorting to `exec`.

BTW, I don't mind the output being recolored (although, why make it mandatory for every task?) as long as I can get **live streaming output**: this is especially annoying if your task starts a process that may run for a while or not terminate (e.g. interactive I/O).

**Comment by andreaferretti** [comment]
Notice that the workaround with `exec` will only work if you can just call `exec nim somefile.nim` but if you have dependencies there is no way around using nimble.
