### ISSUE TITLE
The pkg suffix rule

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#308]
As described [here](https://github.com/nim-lang/nimble#hybrids):

> One thing to note about library and binary package hybrids is that your binary may share the name of the package. This will mean that you will not be able to put your .nim files in a pkgname directory. The reason you will not be able to do this is because binaries on some operating systems do not have an extension so they will clash with a directory of the same name.

> The current convention to get around this problem is to append pkg to the name as is done for nimble.

I've begun wondering whether this is the best solution. The other solution is to place the binaries in a different directory, but doing so has other issues. For example, if the binary depends on some external data that is stored inside the package directory, accessing it will not be easy.

**Comment by moigagoo** [comment]
It's a good solution, we should stick with it. There are several reasons:
- It does the job. Finding an alternative requires effort and is not guaranteed to be any better.
- It's currently enforced by Nimble (just run nimble list -i and the whole screen is covered in warnings and hints). Seeing all these warnings, my first intention is to fix them all ASAP. Imagine if people do this now and then you change the convention. I bet that would be annoying.

I think, this convention should be loudly articulated in the docs. Also, you probably should update the info if your book. Also, having something like `nimble fix` to do the renamings and movings of files and dirs would be really great.

**Comment by dom96** [comment]
I'm starting to wonder whether it would be best to simply disallow "hybrid" packages, and instead support multiple package in the same repo. That way we can simply have two different packages (one a library, the other a binary package) in the same repo.

Although then those packages wouldn't be able to have the same name which would be odd. Hrm. Just writing down my thoughts in any case.

**Comment by dom96** [comment]
I just got a great idea:

* Add logic to nimble to add a `.bin` file extension to binaries which are being installed.

This way the ``pkg`` suffix won't be necessary.

**Comment by Araq** [comment]
I'd prefer an ``.elf`` file extension (or ``.exe`` *cough*)

**Comment by Calinou** [comment]
In this case, would it still be possible to call them directly using the name of the binary (if the Nimble directory is added to the `PATH`)?

**Comment by dom96** [comment]
> I'd prefer an .elf file extension (or .exe cough)

Sure, ``.elf`` it is.

> In this case, would it still be possible to call installed binaries directly using their original name (if the Nimble directory is added to the PATH)?

@Calinou yes, the symlink would just point to the ``.elf`` file, but its name wouldn't contain the ``.elf`` file extension.

**Comment by genotrance** [comment]
Adding an extension for this is not intuitive - you don't expect binaries on Linux to have an extension. You run `nim c` and get one thing and then `nimble build` and get something else. It might be okay with the symlink/shim but that's not the only way binaries could be used. This relates to the restrictions that nimble places on package structure and organization which is being reconsidered on its own. Yet more magic is not warranted.

It is a general compiled binary challenge beyond Nimble or Nim. You cannot have a folder with the same name as your target binary. We can simply document the `pkg` suffix in the [Project Structure](https://github.com/nim-lang/nimble#project-structure) section as a recommendation and leave it at that.

**Comment by Araq** [comment]
The Nim compiler nowadays uses ``foo.out`` (GCC uses ``a.out``) if ``foo`` is already a directory. So far nobody complained, it works well.
