### ISSUE TITLE
Readme / Nimble conflicting advice

### ISSUE THREAD

**Issue by subsetpark** [nim-lang/nimble#312]
The readme recommends a directory structure like this:

```
Directory	Purpose
.	Root directory containing .nimble file.
./src/	Project source code
./tests/	Project test files
./docs/	Project documentation
```

However,  when using a directory called `src` to store my .nim files I receive this warning on `nimble dump`:

> Warning: File 'ad.nim' inside package 'ad' is outside of the permitted namespace, should be inside a directory named 'adpkg' but is in a directory named 'src' instead. This will be an error in the future.
> Hint: Rename the directory to 'adpkg' or prevent its installation by adding `skipDirs = @["src"]` to the .nimble file.

**Comment by dom96** [comment]
you need to add ``srcDir = "src"`` to your .nimble file in this case. I will add this to the readme.
