### ISSUE TITLE
Aporia fails to install with nimble v0.8.2 

### ISSUE THREAD

**Issue by davidsblog** [nim-lang/nimble#313]
**(Moving from the Aporia repo)**

If I try to install aporia using `nimble install aporia` then I seem to get an empty `aporia` file in `~/.nimble/pkgs/aporia-0.4.1/` rather than an executable.  So if I run:

`nimble install aporia`
`cd  ~/.nimble/pkgs/aporia-0.4.1`
`file aporia`

...the output I see is this:

`aporia: empty`

However, if I then do this:

`cd  ~/.nimble/pkgs/aporia-0.4.1`
`nimble build`
`file aporia`

I then get the expected output:

`aporia: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24...`

So it doesn't look like `nimble install aporia` is correctly triggering a build?

**Comment by dom96** [comment]
Let me know if it works now.

**Comment by davidsblog** [comment]
Yes, it worked when I manually installed the latest version of nimble (which reports itself as `nimble v0.8.3`) thanks.
