### ISSUE TITLE
#head versions are not updated upon nimble install

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#318]
This behavior has changed with recent changes is nimble. Previously nimble would download `#head` every time.

```nim
# foo/foo.nimble
version       = "0.1.0"
author        = "Anonymous"
description   = "foo"
license       = "MIT"
requires "nake#head"
```
First run - nake is downloaded:
```
$ nimble install -dy
  Verifying dependencies for foo@0.1.0
   Warning: No nimblemeta.json file found in /Users/yglukhov/.nimble/pkgs/nimble-#head
 Installing nake@#head
Downloading https://github.com/fowlmouth/nake using git
   Warning: File inside package 'nake' is outside of permitted namespace, should be named 'nake.nim' but was named 'nakefile.nim' instead. This will be an error in the future.
      Hint: Rename this file to 'nake.nim', move it into a 'nake/' subdirectory, or prevent its installation by adding `skipFiles = @["nakefile.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for nake@#head
 Installing nake@#head
   Building nake/nake using c backend
   Warning: Binary 'nake' was already installed from source directory. Will be overwritten.
   Warning: Symlink already exists in /Users/yglukhov/.nimble/bin. Replacing.
   Success: nake installed successfully.
```
Second run - nake is not downloaded:
```
$ nimble install -dy
  Verifying dependencies for foo@0.1.0
   Warning: No nimblemeta.json file found in /Users/yglukhov/.nimble/pkgs/nimble-#head
      Info: Dependency on nake@#head already satisfied
   Warning: File inside package 'nake' is outside of permitted namespace, should be named 'nake.nim' but was named 'nakefile.nim' instead. This will be an error in the future.
      Hint: Rename this file to 'nake.nim', move it into a 'nake/' subdirectory, or prevent its installation by adding `skipFiles = @["nakefile.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for nake@#head
```

**Comment by dom96** [comment]
I think the ``update`` command will take care of this.

**Comment by genotrance** [comment]
I think depending on #head is problematic regardless of whether this issue is fixed or not.

If I install `package1` that depends on `something@#head`, it will pull it at the time of install and probably succeed.

After some time, if I install `package2` which also depends on `something@#head`:
- Current *broken* case - nimble will just try to use the old `something@#head` which probably might not work but at least `package1` still works
- Fixed case - nimble will pull the new `something@#head` and probably `package2` will work but `package1` might now break since it needs to be updated to work with new `something@#head`

**Comment by dom96** [comment]
Depending on ``#head`` is perfectly fine. The problem you are describing is solved using lock files, these will define a commit and "freeze" the dependency in place. Only an explicit ``nimble update`` will update the commit hashes, and allow the user to verify that everything still works.

**Comment by genotrance** [comment]
So does this need to be fixed or can we close?

**Comment by yglukhov** [comment]
It's pretty outdated, I think we can close it, as the lockfiles which are going to be implemented will change the requirements completely.
