### ISSUE TITLE
`nimble c -r` fails on Windows, works on Mac; `nim c -r` works everywhere

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/nimble#320]
Consider this repo: https://github.com/moigagoo/nimcast

`nimble c -r tests/test_db` runs on Mac but crashes in Windows:

```
nimble c -r tests/test_db
   Warning: File 'db.nim' inside package 'nimcast' is outside of the permitted namespace, should be inside a directory named 'nimcast' but is in a directory named 'nimcastpkg' instead. This will be an error in the future.
      Hint: Rename the directory to 'nimcast' or prevent its installation by adding `skipDirs = @["nimcastpkg"]` to the .nimble file.
     Error: Traceback (most recent call last)
        ... nimble.nim(1073)         nimble
        ... nimble.nim(1021)         doAction
        ... nimble.nim(641)          execBackend
        ... Specified file does not exist.
```

`nim c -r tests/test_db` works both on Mac and Windows.

*Note: You can see the warning I mentioned in https://github.com/nim-lang/nimble/issues/319*

*Note: tests/config.nims has `switch("path", ".//src")`. That's a workaround for this issue https://github.com/nim-lang/Nim/issues/5228*

**Comment by dom96** [comment]
``nimble c -r tests/test_db.nim`` should definitely work

**Comment by dom96** [comment]
But I agree, this is inconsistent.

**Comment by moigagoo** [comment]
Thanks for the tip! `nimble c -r tests/test_db.nim` does work.

**Comment by dom96** [comment]
As far as I can tell this is now fixed.
