### ISSUE TITLE
Reinstallation issues when tag and .nimble version doesn't match?

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#322]
https://github.com/ephja/nim-glfw/issues/18

**Comment by RSDuck** [comment]
By the way, after downloading it asks if the newly downloaded files should replace the old ones, but when no gets answered it just aborts the whole build.

**Comment by genotrance** [comment]
Linked repo doesn't exist anymore. Any details available?

**Comment by dom96** [comment]
I think we'll get an error now when this happens from Nimble. So let's close.
