### ISSUE TITLE
'nimble install aporia' produces a empty executable

### ISSUE THREAD

**Issue by Michedev** [nim-lang/nimble#327]
nibmle install aporia produces a 0 byte executable under elementary OS and ubuntu.

I follow the standard procedure for installing nim: download the tar archive and run the commands for build and install, then i digit './koch nimble' for the package manager. I put in terminal 'nimble install aporia' and cd to .nimble/bin for run the binary file but it is a plain text with 0 byte. I think may be only a bug in the bin folder then i switch to pkgs/aporia to find the binary file but it is also an empty plain text. I try also now to download manually the nimble from git but the result is the same

**Comment by dom96** [comment]
This shouldn't be an issue with Nimble 0.8.4. Upgrade to it to fix the problem.

**Comment by Michedev** [comment]
Thank you i forgot to update PATH when i clone from git
