### ISSUE TITLE
Enhanced exception message

### ISSUE THREAD

**Issue by pmetras** [nim-lang/nimble#328]
Because it was a time when you could write `setCommand "c", "tests/all"` and the compiler understood that the file `tests/all.nim` was referred, and that's no more the case, we need to get explicit error messages when nimble raises an exception if it can't find a file.

This change is minor and is not worth attaching a patch file or a pull request. In the `nimble/src/nimble.nim` source file, in `proc execBackend(options: Options) =` around line 646, change

```
  if not fileExists(bin):
    raise newException(NimbleError, "Specified file does not exist.")
```
for
```
  if not fileExists(bin):
    raise newException(NimbleError, "Specified file $1 does not exist." % bin)
```
There are a few other places where error messages could be made more explicit too.

**Comment by genotrance** [comment]
Already fixed.
