### ISSUE TITLE
[Feature request] Allow passing flags to `nimble build`

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/nimble#334]
It would be really useful to be able to pass flags to the compiler with `nimble build`.

For example, when I want to debug the package, I'd launch `nimble build --debugger:native` while keeping `config.nims` clean and suitable for release, for example: `-d:ssl`.

**Comment by dom96** [comment]
Should be easy to implement this in case anyone wants to take a crack at it :)

**Comment by dom96** [comment]
Fixed via #347.

**Comment by weskerfoot** [comment]
Where is the documentation for this feature?
