### ISSUE TITLE
Can't run mac brew as sudo.

### ISSUE THREAD

**Issue by hcorion** [nim-lang/nimble#335]
After updating nimble and running `nimble install nimble`
it says that:
```
Success: nimble installed successfully.
      Hint: This package requires some external dependencies.
      Hint: To install them you may be able to run:
      Hint:   sudo brew install openssl
```
However, you can't run `brew` as sudo, if I try, it says
```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

The text should be fixed to just `brew install openssl` because homebrew only asks for superuser permissions when it actually needs to install.

**Comment by dom96** [comment]
This is an issue in the ``distros`` std lib module: https://github.com/nim-lang/Nim/blob/devel/lib/pure/distros.nim#L228 (just changing that ``true`` to ``false`` should fix it).

Although keep in mind, there is a reason for: "To install them **you may** be able to run". There is no guarantee that this will work, ideas on how to make this more clear welcome.

**Comment by dom96** [comment]
@hcorion Ping ^

**Comment by hcorion** [comment]
Yeah, I'll close the issue. Araq already fixed the sudo issue in the nim master, and Mac comes pre-installed with OpenSSL AFAIK.
