### ISSUE TITLE
Can't build on windows without creating bin folder first

### ISSUE THREAD

**Issue by treeform** [nim-lang/nimble#344]
Fails to compile on window 64bit from source
```
kosh nimble 
Error: unhandled exception: The system cannot find the path specified.
 [OSError]
```
But if i create the bin folder
`mkdir bin`
It works fine:
```
kosh nimble
Hint: operation successful (107473 lines compiled; 8.921 sec total; 509.961MiB peakmem; Debug Build) [SuccessX]
```
See here:
```
ls bin
    Directory: C:\p\nimble\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/11/2017   7:46 PM        6459010 nimble.exe
```

**Comment by dom96** [comment]
This isn't a Nimble issue. Please report it in the [Nim](https://github.com/nim-lang/nim) repository.

The ``bin`` folder should be there already though, how come it's missing for you?

**Comment by treeform** [comment]
There is no bin folder in this repository, git can't have empty folders, maybe a folder with an empty.txt or some thing. The Nim repository seems to do it that way: https://github.com/nim-lang/Nim/tree/devel/bin but nimble repository does not. 

I don't think I should create an issue with Nim that nimble.git does not have a `bin` folder when you check it out? I am probably missing some thing though :(

**Comment by dom96** [comment]
``koch`` is in the Nim repo, why are you running it in Nimble's repo?

**Comment by treeform** [comment]
I guess its just the mentality of all other projects. Checkout repo, cd into repo and build it there?

I think I should have used `nim c` instead of `koch`. I'll try it when I am again close to my windows machine and see if that was my mistake.

**Comment by dom96** [comment]
Perhaps the installation instructions could be a bit clearer, but they do state:

> This will clone the Nimble repository, compile Nimble and copy it into Nim's bin directory.

And ``koch`` is in the Nim repository, not in the Nimble repository.

**Comment by treeform** [comment]
Yes you are right. I just used the `koch` tool wrong. Thanks!
