### ISSUE TITLE
TMPDIR variable ignored by nimble

### ISSUE THREAD

**Issue by NastyRigger** [nim-lang/nimble#355]
A recent [change in termux](https://github.com/termux/termux-app/commit/c26315185f0e26db2521dfac64029f797346a229) started exporting the `TMPDIR` variable which points to a direcory inside home.

Unfortunately that made no difference and nimble still fails to operate correctly in termux.

**Comment by dom96** [comment]
This isn't a Nimble issue but a Nim one. The ``getTempDir`` procedure is defined in the Nim standard library, although I'm not sure whether the ``TMPDIR`` environment variable is used enough to warrant the addition. In any case, please create an issue in the Nim repo.
