### ISSUE TITLE
`nimble install` keeps srcDir in copied .nimble

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/nimble#358]
$ nimble --nimbleDir=LOCAL install
    $ ls LOCAL/pkgs/htslib-0.1.0
    htslib/  htslib.nimble  nimblemeta.json

So it copied `htslib.nimble`, which was used for installation. But `htslib.nimble` has `srcDir="src"`, which does not exist in the installation. Will that be a problem? What is the installed copy of `htslib.nimble` used for?

**Comment by dom96** [comment]
This option is only used when installing so I don't think so.
