### ISSUE TITLE
How to make Nimble show me each exec() call

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/nimble#359]
I would like to know all the system calls, for debugging. How can I get Nimble to show me is actually run for each `exec()` call?

These did not work:

    nimble --listCmd test
    nimble --verbose test
    nimble --debug test

Could this be done via some config file?

**Comment by pb-cdunn** [comment]
And btw, I notice that a top-level `exec()` runs things twice. E.g.
```
task test, "dazz_db wrapper":
    echo "hi"
exec("echo QQQQQQQQQQQQQQQQQQQQ")
echo "HHHHHHHHHHHHH"
```
```
$ nimble tasks
QQQQQQQQQQQQQQQQQQQQ
       Info Hint: used config file '/software/n/nim/0.17.0/nim/config/nim.cfg' [Conf]
test                 Test dazz_db wrapper
QQQQQQQQQQQQQQQQQQQQ
HHHHHHHHHHHHH
```

**Comment by dom96** [comment]
You can't AFAIK, but it might be a good idea to implement this behind the ``debug`` flag.

**Comment by genotrance** [comment]
Nim commands show up with `--verbose` and others show up with `--debug`.
