### ISSUE TITLE
nimble refresh out of memory on Appveyor

### ISSUE THREAD

**Issue by mratsim** [nim-lang/nimble#374]
This may be related to https://github.com/nim-lang/nimble/issues/352 which is on Arch.

I get reproducible out of memory error on Appveyor: https://ci.appveyor.com/project/mratsim/arraymancer/build/27

The offending commit https://github.com/mratsim/Arraymancer/commit/cf1c09b89faecd3868576a1a32113b1b4267e6b7 just removes `installDirs = @["src"]` from my package.nimble file.

Build before that commit did not have such an issue: https://ci.appveyor.com/project/mratsim/arraymancer/build/20

**Comment by mratsim** [comment]
I reverted the commit and now `nimble refresh` in Appveyor does not OOM https://ci.appveyor.com/project/mratsim/arraymancer/build/29

**Comment by dom96** [comment]
Do you have a lot of files that don't need to be installed inside your project's directory?

**Comment by dom96** [comment]
That's what #352's issue was. I'm still not sure why it happens though.

**Comment by mratsim** [comment]
It's really really strange.
I have a benchmark folder with 5 files (4 nim and 1 ruby), and a test folder with 10 nim files.

**Comment by dom96** [comment]
I'm guessing this is now fixed via #385. Reopen if not.
