### ISSUE TITLE
'nimble' fails with "could not import: SSL_library_init"

### ISSUE THREAD

**Issue by deech** [nim-lang/nimble#375]
Hi all,
I'm running Arch and after an upgrade `pacman -Syu`, all `nimble` commands now fail with: `could not import: SSL_library_init`. This is `nimble` from the tip of of the `Nim` master branch.  Here's my SSL libraries:
```
/usr/lib$ ls -alh *libssl*
-rwxr-xr-x 1 root root 354K Jun  9 12:35 libssl3.so
lrwxrwxrwx 1 root root   13 May 25 11:48 libssl.so -> libssl.so.1.1
-r-xr-xr-x 1 root root 491K May 25 11:54 libssl.so.1.0.0
-rwxr-xr-x 1 root root 428K May 25 11:49 libssl.so.1.1
```

**Comment by dom96** [comment]
You might have to ask the Arch user's about this. Maybe they've changed openssl to libressl and it doesn't export the ``SSL_library_init`` function?

**Comment by def-** [comment]
I'm also on Arch, x86_64. Can't reproduce. Have you tried rebuilding nimble? I also happen to have openssl-1.0 installed, not sure if that's related.

**Comment by deech** [comment]
Yes, a `git pull` followed by `./koch nimble` seems to have fixed the issue. Thanks!
