### ISSUE TITLE
lib/nim/system.nim(1, 2) Error: redefinition of 'system'

### ISSUE THREAD

**Issue by codenoid** [nim-lang/nimble#377]
hi, i already have a nim installed in my machine, but when i want to install nimble..

```
ayam@laptop:~/Documents/dev$ git clone https://github.com/nim-lang/nimble.git
Cloning into 'nimble'...
remote: Counting objects: 2563, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2563 (delta 0), reused 1 (delta 0), pack-reused 2561
Receiving objects: 100% (2563/2563), 868.72 KiB | 282.00 KiB/s, done.
Resolving deltas: 100% (1586/1586), done.
Checking connectivity... done.
ayam@laptop:~/Documents/dev$ cd nimble
ayam@laptop:~/Documents/dev/nimble$ nim c src/nimble
Hint: system [Processing]
Hint: nimble [Processing]
lib/nim/system.nim(1, 2) Error: redefinition of 'system'
```

i got that error with exit `lib/nim/system.nim(1, 2) Error: redefinition of 'system'`

  * Ubuntu 16.04 64bit
  * Nim Compiler Version 0.12.0 (2015-11-02) [Linux: amd64]
ubuntu 16.04 Nim Compiler Version 0.12.0 (2015-11-02) [Linux: amd64]

**Comment by dom96** [comment]
If you've installed Nim via a package manager or some other way into /usr/bin then that is likely the cause of your issue.

But the real question is: why are you compiling Nimble in the first place?

**Comment by codenoid** [comment]
what the mean of `first place?`

**Comment by dom96** [comment]
Why are you doing it? The Nim distribution now includes Nimble so you shouldn't need to compile it yourself.

**Comment by codenoid** [comment]
someone say , i have a old nim compiler

```
ayam@laptop:~$ nim -v
Nim Compiler Version 0.12.0 (2015-11-02) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by dom96** [comment]
How did you install that old compiler?

I would suggest the following:

* Remove the old compiler
* Install a new one using [choosenim](https://github.com/dom96/choosenim#installation)

**Comment by dom96** [comment]
@codenoid did that help?
