### ISSUE TITLE
Install dependencies when invoking a custom task

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#380]
Is it possible to tell Nimble to just install dependencies of the project without building anything? Or else make nimble resolve dependencies when a custom task is executed. I'd like to build the application without nimble messing with anything, so I make a custom task, but then Nimble doesn't resolve dependencies when I execute the task.

**Comment by dom96** [comment]
Not currently. You have to call `nimble c`, `nimble build` or `nimble install` to resolve deps. Such features are planned though.

**Comment by dom96** [comment]
Now that I'm re-reading, this popped into my head: you can call ``nimble install --depsOnly`` (which will only install the package's dependencies), maybe that's what you want?

**Comment by genotrance** [comment]
I think this should be closed. `--depsOnly` is what is needed here.
