### ISSUE TITLE
Version in packages.json

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#381]
So I broke @FedericoCeratto's package site by introducing the new package aliasing.

He suggested that we should introduce a version field into the packages.json field to make it easier to detect changes and handle them in the future better.

**Comment by Araq** [comment]
That's way more fragile than simply making the JSON processing more robust ("fieldExists" etc.).

**Comment by euantorano** [comment]
So this `version` field would need to be updated via PR whenever a developer pushes and tags a new version in their version control system? That seems like a bit of a hassle to maintain for people with access to merge these PRs.

**Comment by dom96** [comment]
No. A version field to keep track of the packages.json format version.

**Comment by euantorano** [comment]
Ah, that makes much more sense then. Similar to how HTTP API responses are often versioned.

**Comment by genotrance** [comment]
Is this really still required?

**Comment by dom96** [comment]
I'm still skeptical and think @Araq's approach should work fine. If we end up creating a brand new format then we can introduce a version field.

**Comment by Araq** [comment]
No, even with a "brand new format" we should test for features, not versions. Version numbers have no meaning anyway.

**Comment by FedericoCeratto** [comment]
@dom96 I suggested introducing a format version in future formats (if any). The current one, unfortunately, cannot include this kind of data because it contains only an array of packages.
"features" in a file format are not expressive enough to represent changes in semantics efficiently.

**Comment by Araq** [comment]
> "features" in a file format are not expressive enough to represent changes in semantics efficiently.

Yes it does, all you need to do is to rename your object fields should the semantics change. Still much better than magic numbers.

**Comment by FedericoCeratto** [comment]
That is often not efficient. It can require scanning through the entire content to validate its compatibility. It prevents giving meaningful errors to the user e.g. "Unsupported format version 6. Only versions between 2, 3 and 4 are supported". It removes the ability to detect the version from generic 3rd party tools e.g. /usr/bin/file or visual inspection, or guarantee compatibility across applications without doing hand-on tests.

**Comment by Araq** [comment]
That's not useful information for the user, it's technical cruft exposed to the user. Let's just agree to disagree. ;-)
