### ISSUE TITLE
Nimble prefers HEAD to tagged release

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#384]
If HEAD has version of the last tagged release, Nimble will select HEAD, even though the tagged version should be selected.

**Comment by dom96** [comment]
Can you elaborate?

Nimble should install the tagged version if one exists.

**Comment by endragor** [comment]
Hmm, seems you are right and it works as expected. I saw report on the forum which implied nimble installed HEAD instead of released version, but looks like the problem was somewhere else (or, which is unlikely, it's environment-specific).
