### ISSUE TITLE
#head is not kept up to date

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#386]
Perhaps there is a different syntax, but specifying a dependency as `package#head` doesn't make Nimble check every time if the package is up to date with upstream repository, it just outputs "dependency already satisfied", even though there are newer commits.

**Comment by dom96** [comment]
Related to https://github.com/nim-lang/nimble/issues/332

**Comment by Araq** [comment]
In a Posix shell ``#head``  is a comment. Maybe the problem here?

**Comment by dom96** [comment]
Nah, it's a known issue. Still not entirely worked out how to best solve it.

**Comment by yglukhov** [comment]
#318?

**Comment by dom96** [comment]
Duplicate of #318.
