### ISSUE TITLE
Nimble installation exited with code 1, basicopt.txt nim.cfg

### ISSUE THREAD

**Issue by codenoid** [nim-lang/nimble#388]
i run
```
git clone https://github.com/nim-lang/nimble.git
cd nimble
nim c src/nimble
src/nimble install
```

and when `src/nimble install`
i got https://pastebin.com/Zk5GguiM

**Comment by dom96** [comment]
I've already told you in the previous issue to try installing via ``choosenim``: https://github.com/nim-lang/nimble/issues/377#issuecomment-317250650

You shouldn't be compiling Nimble yourself. It's packaged with Nim.

**Comment by codenoid** [comment]
`nimble: command not found`

**Comment by dom96** [comment]
Did you install using ``choosenim``?

**Comment by codenoid** [comment]
what `choosenim` ? :/

**Comment by dom96** [comment]
It's a tool that makes it easier to install Nim. All you need to do is execute the command shown [here](https://github.com/dom96/choosenim#unix).

Just make sure to read what `choosenim` outputs as it installs Nim :)

**Comment by codenoid** [comment]
thanks @dom96

**Comment by dom96** [comment]
Yay, is it all working now? :)

**Comment by codenoid** [comment]
```
ayam@laptop:~/Documents/myapp/hofesh$ nimble -v
nimble v0.8.6 compiled at 2017-08-12 18:14:52
```

Work like a charm :sparkles:
