### ISSUE TITLE
Give a good error message when stdlib is missing

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#390]
Context: https://irclogs.nim-lang.org/13-08-2017.html#20:08:24

Possibly also try to cover the case described in these logs.

Related code: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/nimscriptsupport.nim#L191

**Comment by genotrance** [comment]
Nimble no longer cares where the stdlib is, it just calls Nim.
