### ISSUE TITLE
Declare task dependencies in nimble file

### ISSUE THREAD

**Issue by couven92** [nim-lang/nimble#392]
It should be possible to have tasks depend on each other, so that invoking a nimble taks with dependencies would prompt nimble to first execute all dependent tasks first.
* if a dependant task fails, the entire invocation fails
* if multiple tasks in the execution graph depend on the same task, that task should only be executed once

To cause least conflict with exiting `.nimble`-syntax I propose, the following alternatives to declare dependencies:
``` nim
dependantTask build, makeBinDir
dependantTask test, [makeBinDir, build]
```
When dependencies are specified as an array or sequence, the order should be taken into consideration (however, task dependencies take precedence)

Alternative name for lazy typing could be: `depTask`. Alternate name for better explicitness could be: `dependencyFor` or `dependenciesFor`

**Comment by dom96** [comment]
I don't think this is necessary. You can execute other tasks from tasks. I believe it's just ``<taskName>Task()``.

**Comment by dom96** [comment]
@couven92 have you been able to try what I suggested?

**Comment by couven92** [comment]
@dom96 works splendidly! :)
