### ISSUE TITLE
nimble develop makes nim unable to import package

### ISSUE THREAD

**Issue by dandevelo** [nim-lang/nimble#395]
I am installing my package using `nimble install` from the package dir

then, in another file in another location on my system (let's call it `testimport.nim`), I import my package using

`import mypkg/myfile`

where `myfile.nim` is part of mypkg. Everything worked OK at this point.

Then I tried using [nimble develop](https://github.com/nim-lang/nimble#nimble-develop) so that I don't need to reinstall mypkg whenever I make a change to mypkg. However, as soon as I type nimble develop in my package dir, the import statement in `testimport.nim` fails and it seems like it can not find the package anymore.

`testimport.nim(1, 13) Error: cannot open 'mypkg/myfile'`

As I previously ran `nimble install` prior to running `nimble develop`, I now have two packages listed by nimble list -i 

`mypkg  [#head, 0.1.0]`

As soon as I uninstall the #head version by typing nimble uninstall mypkg@#head then the import statement works again but it uses the 0.1.0 installed version of mypkg which defeats the purpose of `nimble develop`.

What could be the issue?

**Comment by dom96** [comment]
This is a really new feature that I just landed, nice to see you using it so fast :)

Sadly because it is so new the Nim compiler hasn't got support for it yet. As such it is not aware of these `develop`-linked packages yet. But what you can do for now is use ``nimble`` for compilation: ``nimble c testimport.nim``.

**Comment by dandevelo** [comment]
Hi @dom96 ,

Just tried that but I get an error: 

`Error: Specified directory does not contain a .nimble file.`

Is there any solution that would work for arbitrary .nim files (without having to create any nimble files in the directory) ?

**Comment by dom96** [comment]
Not right now, but there will be once @Araq implements it in the compiler.

**Comment by dandevelo** [comment]
Thanks @dom96 @Araq Looking forward to that. Keep up the good work!

**Comment by dom96** [comment]
Just implemented this in Nim devel :)

https://github.com/nim-lang/Nim/commit/90fa64501f0eba487182a760fde98f7bb955c3d7
