### ISSUE TITLE
publishing fails with bad error report

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimble#398]
This error message is not very informative, please write something that help to detect what I actually did wrong.

```
$nimble publish
       Info Hint: used config file '/home/arne/proj/nim/Nim/config/nim.cfg' [Conf]
      Info: Using GitHub API Token in file: /home/arne/.nimble/github_api_token
   Success: Verified as krux02
    Cloning packages into: /tmp/nimble-packages-fork
   Updating the fork
    Prompt: Whitespace separated list of tags?
    Answer: gui rendering opengl
    Pushing to remote of fork.
       Info Creating PR
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```

**Comment by dom96** [comment]
This seems to be a recent regression. I'm guessing GitHub changed something :\

**Comment by edubart** [comment]
I'm also getting this error

**Comment by bogen** [comment]
I just now tried to publish 2 packages, same error.

**Comment by Gooseus** [comment]
I'm also having this issue trying to publish a package - nimble v0.8.8

**Comment by genotrance** [comment]
Since nothing was being pushed (due to nil pw used in push step), the PR failed (there was nothing to pull on remote. I've pushed a fix along with proxy support for publish.
