### ISSUE TITLE
Nimble silently uses $NIM_LIB_PREFIX 

### ISSUE THREAD

**Issue by subsetpark** [nim-lang/nimble#407]
Here's a confusing error message:

```
[i] master! ~/code/lang/nim/threadpools ; nimble build
       Info Hint: used config file '/etc/nim.cfg' [Conf]
     Error: Could not read package info file in /home/zax/code/lang/nim/threadpools/threadpools.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     Error: cannot open '/home/zax/.choosenim/toolchains/nim-#head/lib/system.nim'.
```

This failed because I had cleaned out my ~/.choosenim folder. It turns out that `NIM_LIB_PREFIX` was still pointing at it. It would be useful if Nimble logged that that's where it was getting the lib location from.

**Comment by dom96** [comment]
This is now fixed. Here is the line that shows the message: https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/nimscriptsupport.nim#L198
