### ISSUE TITLE
Foreign characters input with nimble init are escaped

### ISSUE THREAD

**Issue by mjoud** [nim-lang/nimble#410]
`nimble init` will escape "foreign characters" since `strutils.escape` is used. This leads to a surprising `.nimble` file.

```
$ nimble init test
      Info: In order to initialise a new Nimble package, I will need to ask you
        ... some questions. Default values are shown in square brackets, press
        ... enter to use them.
    Prompt: Initial version of package? [0.1.0]
    Answer: 
    Prompt: Your name? [My name]
    Answer: Mañana
    Prompt: Package description?
    Answer: Blött vått slätt    
    Prompt: Package license? [MIT]
    Answer: 
    Prompt: Lowest supported Nim version? [0.17.2]
    Answer: 
   Success: Nimble file created successfully
       Info Hint: used config file '/etc/nim.cfg' [Conf]

$ cat test.nimble 
# Package

version       = "0.1.0"
author        = "Ma\xC3\xB1ana"
description   = "Bl\xC3\xB6tt v\xC3\xA5tt sl\xC3\xA4tt"
license       = "MIT"

# Dependencies

requires "nim >= 0.17.2"


```

**Comment by DestyNova** [comment]
This is affecting me too... I have to manually fix my name in the .nimble file after every `nimble init`. Can we just not call `strutils.escape` when populating those fields? I'm not sure what it's trying to guard against.

**Comment by dom96** [comment]
@DestyNova it's making sure that any non-printable characters are escaped, but you're right, this is unlikely to happen for names. Happy to accept a PR that remove ``strutils.escape``.

**Comment by DestyNova** [comment]
PR opened :smiley:

**Comment by DestyNova** [comment]
(Note: I also removed escaping of the package description because I can easily imagine non-English characters being used there.)

**Comment by genotrance** [comment]
This is fixed.
