### ISSUE TITLE
latest Nimble hangs on Windows 10

### ISSUE THREAD

**Issue by matkuki** [nim-lang/nimble#412]
Hi,
I installed Nim from the Github devel repository and Nimble with:
```sh
koch nimble
```
Then tried installing a package on Windows 10 using:
```sh
nimble install 'package_name'
```
This crashes the *Windows Command Prompt* but **nimble.exe** still remains active (is still visible in the task manager).
It seems to install the package and dependencies correctly. Below is a screenshot at the moment just before it crashed:
![nimble_screenshot](https://user-images.githubusercontent.com/10289651/31249287-139bb7d0-aa17-11e7-997d-47053a403c69.png)

Specs:
- Windows 10
- Nim Compiler Version 0.17.3 (2017-10-05) [Windows: i386]
- MinGW GCC 7.10 (gcc (i686-win32-sjlj-rev2, Built by MinGW-W64 project) 7.1.0)

Any ideas?

**Comment by matkuki** [comment]
It seems to be a MinGW issue. Running the **nimble.exe** executable with the default MinGW installation give the following errors:
```sh
could not load: libeay32.dll
```
and
```sh
could not load: (ssleay32|libssl32).dll
```
If I put these dll's (which are in the MinGW installation folder's **/opt/bin/** directory) on the PATH then nimble works, but apparently not correctly.

**Comment by Yardanico** [comment]
@matkuki you should get those dll's from https://nim-lang.org/download/dlls.zip

**Comment by matkuki** [comment]
Hey @Yardanico , 
Thanks for the link, but the behaviour is the same with these dll's.
Commands like *nimble update* and *nimble search* work fine, while *nimble install 'package'* hangs nimble and closes/crashes the command prompt.

I'll try to get another windows 10 machine and report back.

**Comment by Yardanico** [comment]
@matkuki nimble works perfectly for me on win10 though..

**Comment by dom96** [comment]
Another thing to try is to remove your Nim installation completely and use ``choosenim`` to install it all again.

**Comment by matkuki** [comment]
Hey @dom96 ,
Downloaded and executed ```choosenim``` executable installer, but get:
```sh
Downloading DLLs (openssl, pcre, ...)
Traceback (most recent call last)
choosenim.nim(155)       choosenim
choosenim.nim(136)       performAction
choosenim.nim(74)        choose
choosenim.nim(57)        chooseVersion
download.nim(17)         downloadDLLs
download.nim(169)        downloadFile
download.nim(154)        downloadFileNim
httpclient.nim(1256)     downloadFile
httpclient.nim(951)      parseBody
httpclient.nim(892)      recvFull
httpclient.nim(866)      reportProgress
download.nim(150)        onProgressChanged
terminal.nim(657)        showBar
terminal.nim(396)        eraseLine
system.nim(2724)         sysFatal
Error: unhandled exception: over- or underflow [OverflowError]
The system cannot find the path specified.
        0 file(s) copied.
            Work finished.
            Now you must ensure that the Nimble bin dir is in your PATH:
              C:\Users\matic\.nimble\bin
```

**Comment by matkuki** [comment]
Hey @Yardanico ,
Can you tell me your specs?
I'm on Windows 10 x64 with all updates and tried Nim with mingw-w64 7.10 x86_64 and installed Nimble with ```koch nimble```. I also tried it with mingw-w64 7.10 x86, but the crash/hang is still there.

I have TortoiseGit x64 with git 2.14.2 x64 installed on the system, could this also be a problem?

**Comment by dom96** [comment]
Oh right. You had that problem I remember.

Regarding Nimble: maybe ``git`` is waiting for some stdin? Run it with the `--debug` flag and see what command it's trying to run, then run it manually and see if it works.

**Comment by matkuki** [comment]
Hi @dom96 ,
The ```--debug``` switch shows:
```sh
Executing git clone --recursive --depth 1 https://github.com/nim-lang/sdl2 C:\Users\matic\AppData\Local\Temp\nimble_8680\githubcom_nimlangsdl2
```
when it hangs.
Running the command manually clones the repository without problems. Wierd.
I have no idea what's going on here.

**Comment by dom96** [comment]
No idea either. Next step would be to try using the ``osproc`` module to run the same command and see if it works.

**Comment by matkuki** [comment]
Just tried using ```osproc.startProcess``` and get the same crash!
So it's not a nimble thing.
I will close this issue when @Yardanico gives me the specs of his windows installation.

**Comment by Yardanico** [comment]
@matkuki Microsoft Windows [Version 10.0.15063]
gcc version 7.1.0 (x86_64-win32-seh-rev2, Built by MinGW-W64 project)
```
Nim Compiler Version 0.17.3 (2017-10-07) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 9b1a23c554209772106ac9d4f7fd5d5c062c1d17
active boot switches: -d:release
```

```
nimble v0.8.8 compiled at 2017-10-07 16:29:30
git hash: 968e1a20beaee369ec30a06268ebc1ae5a09254a
```

Close this issue probably, and open an issue in main nim repo (about osproc)?

**Comment by Yardanico** [comment]
@matkuki I have official git client, not TortoiseGit

**Comment by matkuki** [comment]
Thanks @Yardanico!
I will investigate further.

**Comment by matkuki** [comment]
Yardanico , good catch!
It wasn't ```TortoiseGit``` but the ```git``` installation itself! 
**Do not install git with the default options for 'Windows Shell Integration' (Git Bash Here & Git GUI Here)!**
Disabling these options during installation fixes the issue.

Thanks @Yardanico , @dom96

**Comment by dom96** [comment]
That's pretty bad :\

I wonder what this Windows Shell integration does.
