### ISSUE TITLE
Feature request: create repo structure with nimble init

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#413]
nimble init could set up the right repo structure according to https://github.com/nim-lang/nimble#project-structure interactively or using options e.g.:

```
Prompt: Package name?
Prompt: Create project directory (Y/n)?
Prompt: Create library, multi-module library, application (L/m/a)?
Prompt: Create tests directory (Y/n)?
Prompt: Initialize git repository (Y/n)?
...
```

If options like --init-git --no-init-git --library --application --multi-module --create-project-dir --no-create-project-dir are passed the questions are skipped as in #288

**Comment by dom96** [comment]
I like this idea. We can do this when a name is specified to the ``init`` command: ``nimble init myProject``.

**Comment by FedericoCeratto** [comment]
Related: this tool creates a project structure and add "template" files - https://github.com/FedericoCeratto/nim_project_maker

(It's not meant to replace "nimble init". On the contrary, parts of it could be merged into Nimble if there's interest)
