### ISSUE TITLE
make the version in the nimble file optional

### ISSUE THREAD

**Issue by krux02** [nim-lang/nimble#419]
The version can be inferred from the git tags already, so also specifying the version in the nimble file is redundant.

**Comment by FedericoCeratto** [comment]
There might be cases where people cannot use VCS tags. Perhaps #413 can add a commented-out version field or a special value to use the git tag.

**Comment by genotrance** [comment]
A git tag is for a specific commit so if you checkout a repo which has a tag for `HEAD~1` but nothing for `HEAD`, what is the version? Should it still be the same as `HEAD~1`?

`git describe --tags` returns `v0.5.0` when it is the exact tag. If there isn't a tag for this specific commit, it shows `v0.5.0-1-gc60a8cd`. In either case, we could split by `-` and use `[0]`.

Another corner case is when you have an initial repo and it has no tags nor version field. Do we assume `v0.1.0` then?

**Comment by dom96** [comment]
IMO this feature has far too many subtle possible ways that it can go wrong. @genotrance already mentioned some and we need to consider ``hg`` as well + packages that have no VCS at all. It's much better to be explicit for this.

I'm going to close this.
