### ISSUE TITLE
Multiple nimble packages in the same repo

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#421]
It should eventually be possible to support multiple nimble packages in the same repo.

It'd be nice if we could encode the separate sub-directories in the GIT URL, for example:

* https://github.com/dom96/jester/my-sub-package

But I don't think that will be possible.

**Comment by bluenote10** [comment]
Maybe by using a special separator like `https://github.com/dom96/jester@subdir/subpackage`?

**Comment by dom96** [comment]
Yes, but it would have to be a different separator.

**Comment by dom96** [comment]
High priority because it's needed by https://github.com/zserge/webview/pull/111#issuecomment-367561320 :)

**Comment by TheSimpleZ** [comment]
Does this feature exists? Are there any instructions? Reading this section:
https://github.com/nim-lang/nimble/blob/master/readme.markdown#project-structure
Makes me believe it's not possible since the .nimble file must be in the root of the repo.

**Comment by dom96** [comment]
@TheSimpleZ yeah, it's possible. See https://github.com/nim-lang/nimble#package-urls
