### ISSUE TITLE
suggestion for versioning

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/nimble#422]
nimble currently appends the version number to the package name. 
I think it is better to start a new directory for every tag version.
The package directory can have a file specifying which version to use (by default).
if that file doesn't exist, assume the latest.
Add a command to nimble: `nimble set pkg 0.2.7-stable` or whatever the syntax is, to create that file.
Another option is to pass this info when compiling in a project-specific manner (information in the working folder)
a few ideas for consideration

**Comment by dom96** [comment]
> I think it is better to start a new directory for every tag version.

What would that improve? What's wrong with the current approach?

Just so you know, this was suggested before and I rejected it (IIRC) :)

**Comment by dom96** [comment]
Closing due to lack of response. (I am still curious to know your thoughts so feel free to reopen).

**Comment by kobi2187** [comment]
sorry didn't notice your reply. Yes, there is no major advantage, it is only cleaner in my opinion, and perhaps easier to update (when that feature is implemented), maybe it's easier to switch between git version and release version. But that really depends on your implementation. 
IOW, there is no inherent advantage, just seems easier to reason or implement.
