### ISSUE TITLE
Make `nimble install nimble` reproducible and robust

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#425]
Currently nimble has a `#head` dependency w.r.t. the compiler. This has a few issues:

- `nimble install nimble` is not reproducible, i.e., it is unclear which nimble versions require which version of the compiler.
- `nimble install nimble` (without having nimble installed already) can break at any time with an upstream change in compiler.
- `nimble install nimble` (with having nimble installed already) updates nimble, but does not seem to update the compiler dependency as well, i.e., it can break nimble because it now uses functionality which is not yet available in the `compiler#head` version in `pkgs`.
- The `compiler#head` installed in `pkgs` can become incompatible with the actually installed Nim compiler.

I'm wondering if all these issues could be avoided by just depending on the `compiler` module which actually comes with the Nim compiler instead of installing it as a redundant (and possible inconsistent) installation in `pkgs`.

**Comment by dom96** [comment]
This will be fixed once lock files are implemented.

That said, installing nimble using this method isn't that common so it shouldn't be a common problem.
