### ISSUE TITLE
`nimble path` shows different path than actually used?

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#426]
Probably a minor issue, but a bit confusing:

```
$ nimble path nimble
/home/fabian/.nimble/pkgs/nimble-0.6.2/src
```

However I'm pretty sure that this is not the path that nimble actually passes in as compiler search path. I have these versions installed:

```
$ ll -d /home/fabian/.nimble/pkgs/nimble*
drwxrwxr-x 3 fabian fabian 4096 Nov 12 14:55 /home/fabian/.nimble/pkgs/nimble-#head
drwxrwxr-x 3 fabian fabian 4096 Mai  2  2015 /home/fabian/.nimble/pkgs/nimble-0.6.0
drwxrwxr-x 3 fabian fabian 4096 Sep 23  2015 /home/fabian/.nimble/pkgs/nimble-0.6.2
drwxrwxr-x 3 fabian fabian 4096 Nov 12 14:53 /home/fabian/.nimble/pkgs/nimble-0.8.8
```

And it looks like nimble is using either the `0.8.8` or the `#head` version.

Is there another way to find out which path is really added as compiler search path? Does `nimble path` have a different purpose?

**Comment by dom96** [comment]
I think this was fixed here https://github.com/nim-lang/nimble/commit/d00f59708a532a9c841361b325b2654cf36798b6
