### ISSUE TITLE
nimble path doesn't work if using nimble develop

### ISSUE THREAD

**Issue by genotrance** [nim-lang/nimble#430]
If a package is setup using ```nimble develop```, the ```nimble path xyz``` command doesn't work:

```
Error: At least one of the specified packages was not found
```

**Comment by dom96** [comment]
Might need more info. I do have a test for this and it passes: https://github.com/nim-lang/nimble/blob/master/tests/tester.nim#L563

**Comment by genotrance** [comment]
Not sure what's special about my nimgen derivative modules, can you please check nimssl or nimbass? If I run nimble develop after cloning one of those, the path command doesn't work.

**Comment by FedericoCeratto** [comment]
@dom96 "nimble install nimbass", when run on a host without nimgen installed, fails by attempting to install nimbass without installing nimgen first

**Comment by genotrance** [comment]
@FedericoCeratto: that's actually #280 - my fix needs some work so that before install is called after dependencies are installed. I'm working on that.

**Comment by dom96** [comment]
Cannot reproduce.

**Comment by genotrance** [comment]
Verified cannot reproduce with latest nim.
