### ISSUE TITLE
`Cannot satisfy the dependency` problem

### ISSUE THREAD

**Issue by vegansk** [nim-lang/nimble#432]
The project depends on package via `tempfile#head` which is of version 0.1.5, and have transitive dependency on the same package: `tempfile >= 0.1.5`. `nimble install -d` raises an error:

```
Error: Cannot satisfy the dependency on tempfile #head and tempfile 0.1.5
```

**Comment by dom96** [comment]
If there is a transitive dependency on ``tempfile >= 0.1.5`` then that shouldn't be a problem. Are you sure it's ``tempfile >= 0.1.5`` and not ``tempfile 0.1.5``?

Another possible issue could be that ``tempfile#head``'s version is actually < 0.1.5.

**Comment by dom96** [comment]
On the other hand, I can see this being a bug. But please verify, and if you can create a project that reproduces this.
