### ISSUE TITLE
nimble search error: package in packages.json does not contain a url field

### ISSUE THREAD

**Issue by drsneed** [nim-lang/nimble#434]
First I run nimble refresh. It downloads the official package list successfully. Next I run nimble search glfw and nimble throws the following error:
nimble search glfw
Traceback (most recent call last)
nimble.nim(1007)         nimble
nimble.nim(945)          doAction
nimble.nim(645)          search
packageinfo.nim(157)     getPackageList
packageinfo.nim(106)     fromJson
packageinfo.nim(97)      requiredField
Error: unhandled exception: Package in packages.json file does not contain a url field. [NimbleError]

I'm on Windows 8.1 64 bit using the version of nimble installed with nim 0.17.2.

**Comment by dom96** [comment]
You have a corrupted packages.json file inside ``~/.nimble``?

**Comment by drsneed** [comment]
I assumed this would be the case. I deleted both packages_official.json and packages_temp.json. nimble refresh downloaded these files again. nimble search resulted in the same error. I would attach the json files but github does not allow it.

**Comment by drsneed** [comment]
[packages_temp.txt](https://github.com/nim-lang/nimble/files/1493374/packages_temp.txt)
[packages_official.txt](https://github.com/nim-lang/nimble/files/1493375/packages_official.txt)

Here, I've renamed the package files .txt instead of .json so I can attach them.

**Comment by dom96** [comment]
What's the Nimble version? ``nimble -v``

**Comment by drsneed** [comment]
nimble v0.7.8 compiled at 2016-09-30 23:41:03

**Comment by dom96** [comment]
That's very old. You need to upgrade your Nimble. You should check where
the Nimble in your PATH is located using `which nimble `

**Comment by drsneed** [comment]
Ahh, this solved the problem. I had an old nim compiler in my PATH that I was unaware of. After removing it, nimble search works as expected now. Thank you.
