### ISSUE TITLE
Ability to depend on OS packages

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#44]
It would certainly be a nice feature to be able to specify OS-level dependencies and to install them. For example the gtk2 bindings can depend on the corresponding gtk packages. Problem is that all Linux distros have different package names and different package managers etc... Windows doesn't have an official package manager, maybe we could support links to zip files? Mac OS X I have no idea.

It's still a nice thought though.

**Comment by ReneSac** [comment]
0install uses [PackageKit](http://www.freedesktop.org/software/PackageKit/) to work around the different linux distributions: http://0install.net/distribution-integration.html

And 0install itself is a package manager that works on Windows and Mac OS X too.

**Comment by dom96** [comment]
My current plan is to provide post-install hooks via NimScript (what @yglukhov mentioned). A package can then be created which implements a NimScript-friendly API for installing OS dependencies.

**Comment by dom96** [comment]
@Araq began working on this https://github.com/nim-lang/nimble/pull/283

**Comment by dom96** [comment]
This has been implemented :D
