### ISSUE TITLE
`nimble remove packagename` fails if nimble-link file points to a missing file

### ISSUE THREAD

**Issue by ghost** [nim-lang/nimble#440]
Steps to reproduce -
Do `nimble develop packagename`
Move/Rename/Delete the cloned folder.
Do `nimble remove packagename`
It gives -
```
Error: The .nimble-link file is pointing to a missing file
```

IMO, it should remove the .nimble-link file and other associated files.

**Comment by nc-x** [comment]
One fix is to change https://github.com/nim-lang/nimble/blob/6354132959f3018883d7b93dbd6af8bbddff5b0e/src/nimblepkg/packageinfo.nim#L312-L317 to 
```nim
  if result.splitFile.ext == ".nimble-link":
    let path = result.splitFile.dir
    # Return the path of the real .nimble file.
    result = readNimbleLink(result).nimbleFilePath
    if not fileExists(result):
      result = ""
      removeDir(path)
```

But I haven't checked whether this change would have any side effects.
If this fix is correct I can make a PR.

**Comment by dom96** [comment]
That would be dangerous, a procedure called ``findNimbleFile`` shouldn't be removing packages...

**Comment by dom96** [comment]
Fixed here: https://github.com/nim-lang/nimble/commit/225a0ef661b48973f43a0a47ece18076fe30caa7
