### ISSUE TITLE
`listPaths()` uses wrong logic for finding whether a package is installed

### ISSUE THREAD

**Issue by nc-x** [nim-lang/nimble#449]
https://github.com/nim-lang/nimble/blob/6354132959f3018883d7b93dbd6af8bbddff5b0e/src/nimble.nim#L628 checks only if the path **startsWith** the package name and does not match the complete package name which may lead to getting the path for wrong package.

**Comment by dom96** [comment]
This was fixed in here: https://github.com/nim-lang/nimble/commit/d00f59708a532a9c841361b325b2654cf36798b6

**Comment by nc-x** [comment]
Then should this issue be closed or as per your comment in https://github.com/nim-lang/nimble/pull/454#issuecomment-361621892 should this remain open?

**Comment by dom96** [comment]
Let's close it, this logic will do for now :)
