### ISSUE TITLE
Importing the Terminal module in a nimble file results in an error.

### ISSUE THREAD

**Issue by flenniken** [nim-lang/nimble#457]
To reproduce, add "import Terminal" to the top of a nimble file and run it.

You will see the error:
```
Error: undeclared identifier: 'float128'
```

**Comment by dom96** [comment]
This isn't really a Nimble problem. I bet the same thing happens for a .nims file

**Comment by flenniken** [comment]
It works fine in a nim file.

**Comment by dom96** [comment]
.nims != .nim

Does it work well in a NimScript file?

**Comment by dom96** [comment]
Closing as this isn't a nimble-specific problem.
