### ISSUE TITLE
nimble check can't find .nimble line is confusing.

### ISSUE THREAD

**Issue by treeform** [nim-lang/nimble#460]
```me@lane:/p/n/useragents> nimble check
Error: Specified directory does not contain a .nimble file.
me@lane:/p/n/useragents> cat .nimble
# Package

version     = "0.1.0"
author      = "Andre von Houck"
description = "Parses user agents in nim."
license     = "MIT"

# Deps

requires "nim >= 0.17.3"⏎                                                                                             ```

**Comment by treeform** [comment]
Can that error be changed to `Specified directory does not contain a {path/file its looking for}.nimble file.` ? I though it wanted a literal `.nimble` file.

**Comment by dom96** [comment]
It looks for any file with a ``.nimble`` file extension, but yeah, we can improve that.

**Comment by treeform** [comment]
I remember being stuck on this message last time. Spent like 15 minutes to figure it out. Then I forgot and was stuck on it again. If it looks for any file, maybe saying `*.nimble` is enough?

**Comment by genotrance** [comment]
Is this really required? Message has been updated to show the directory but is *.nimble really required?

**Comment by dom96** [comment]
What's the current message? In any case, this should be an easy thing to fix.

**Comment by genotrance** [comment]
`"Specified directory ($1) does not contain a .nimble file." % dir`.
