### ISSUE TITLE
Limited license selection in `nimble init`

### ISSUE THREAD

**Issue by euantorano** [nim-lang/nimble#468]
When running `nimble init`, it asks the user to choose a license. It currently [only supports a very small selection of licenses](https://github.com/nim-lang/nimble/blob/7e3058657c4ff3ca70288595fc2a21f791c50f7c/src/nimble.nim#L770):

- MIT
- BSD 2 Clause
- GPL v3
- LGPL v3
- Apache 2

I noticed this as I usually choose a BSD 3 Clause license for my projects. There should be an option to either specify a custom license, or this list should be expanded upon (I would vote for the first option).

**Comment by Calinou** [comment]
The [SPDX license list](https://spdx.org/licenses/) could be used for validation.

**Comment by dom96** [comment]
Fixed in https://github.com/nim-lang/nimble/commit/cc71c6f80e696d7c6f93e49e8de2bca5c3eb4957
