### ISSUE TITLE
`nimble build -r` doesn't output program messages

### ISSUE THREAD

**Issue by rvlander** [nim-lang/nimble#478]
When compiling and launching a program using `nimble build -r`, output from the launched program is not redirected to the terminal.

Moreover the ability to add the `-r` flag to the build command is not documented.

**Comment by dom96** [comment]
I'm fairly sure the ``-r`` flag doesn't work in that context...

Do you mean ``nimble c -r``? That will give you output as well.

**Comment by rvlander** [comment]
> I'm fairly sure the `-r` flag doesn't work in that context...
Yet it does launch the compiled executable.

`nimble c -r` works as expected.

**Comment by dom96** [comment]
I don't recall implementing that :)

**Comment by rvlander** [comment]
I have looked in the code and you didn't, but it seems like you pass additional options directly to the nim command.
The `-r` option might be directly redirected to the compiler command.

As for why it does not show output in the first case and does in the second, i may have an explanation.
The first uses `buildFromDir` procedure and the second `execBackend` procedure.
Both do a call to `doCmd` but in the second case `showOutput = true` is passed while it is not passed in the first case.

Maybe `buildFromDir` could call `execBackend`. I did not look into details.

**Comment by dom96** [comment]
The fact that ``build`` doesn't show the output is by design, that it supports ``-r`` isn't (and that must have been added through a PR).

**Comment by rvlander** [comment]
What is the problem with `build` outputting?

**Comment by dom96** [comment]
It hides Nimble's messages. When I am installing a binary package which needs to be built (via ``nimble build``) I don't want to see a bunch of Nim compiler messages and miss out on important messages from Nimble.

**Comment by rvlander** [comment]
Maybe there could be a `-v` and `-vv` options to respectively display output when compiling source from current package and to display all build outputs.

**Comment by genotrance** [comment]
With the recent changes around verbosity, this now works as expected and `-r` will print to output.
