### ISSUE TITLE
nimble init stuck on licence

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/nimble#487]
I get stuck on `nimble init` if I dont choose a copyright from the list.

![nim-lice](https://user-images.githubusercontent.com/1189414/39916505-08155c20-54e1-11e8-9621-e5b51f9830ab.png)

:cat2:

**Comment by dom96** [comment]
This should be fixed now.

**Comment by juancarlospaco** [comment]
Yes, seems Fixed, thanks for all the work.
