### ISSUE TITLE
Where do these warnings come from?

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/nimble#490]
Everything is working, but I see a bunch of nimble warnings even though I am not (yet) using Nimble at all:
```
nim --threads:on --threadAnalysis:off --verbosity:2 -d:release  --tlsemulation:on --out:fc_consensus.exe c fc_consensus.nim
config/nim.cfg(47, 3) Hint: added path: '/home/UNIXHOME/cdunn/.nimble/pkgs/compiler-#head' [Path]
    nimblepath="$home/.nimble/pkgs/"
    ^
config/nim.cfg(47, 3) Hint: added path: '/home/UNIXHOME/cdunn/.nimble/pkgs/c2nim-0.9.13' [Path]
    nimblepath="$home/.nimble/pkgs/"
    ^
config/nim.cfg(47, 3) Hint: added path: '/home/UNIXHOME/cdunn/.nimble/pkgs/argument_parser-0.4.0' [Path]
    nimblepath="$home/.nimble/pkgs/"
    ^
...
```
- Where do they come from?
- How do I suppress them?

**Comment by dom96** [comment]
This isn't a Nimble issue, but a Nim one. 

> Where do they come from?

config/nim.cfg

> How do I suppress them?

``--hints:off`` IIRC

**Comment by pb-cdunn** [comment]
Do you know why it's using nimble at all? I don't see where that happens. I will use Nimble eventually, but not yet.

**Comment by dom96** [comment]
Because the compiler sets it internally. Pretty sure this ``nimbabel`` symbol is only there for backward compatibility with older Nim compilers.

**Comment by pb-cdunn** [comment]
Ok. Thanks, Dom.
