### ISSUE TITLE
Nimble does not execute tasks anymore

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#491]
I updated Nimble this morning - I use to run `git pull; koch boot; koch tools` every day to keep up to date with devel.

Now, every time I try to run a nimble task, I just get the list of avilable tasks. That is, if I have a project where - say - the task `test` is defined, running `nimble test` has the exact same effect as running `nimble tasks`.

This happens consistently across all projects

**Comment by andreaferretti** [comment]
Forgot to add

```
djerzinski:~ andrea$ nimble --version
nimble v0.8.11 compiled at 2018-05-16 11:23:30
git hash: 02945e57b5abf0ff303d5d722f1fba4006717d21
```

**Comment by dom96** [comment]
CC @Araq

**Comment by andreaferretti** [comment]
Great!
