### ISSUE TITLE
Nimble does not execute tests when `nimble test` if there are requires for GitHub' repository.

### ISSUE THREAD

**Issue by loloiccl** [nim-lang/nimble#493]
Nimble does not execute tests when `nimble test` if there are requires for GitHub' repository.

Example:
https://github.com/loloiccl/nimly/tree/5b69ecda2d7cb6a16ccde71fe3ed1748a6d42b30

executing `nimble test` in this repository,
Output:
 ```
  Executing task test in /Users/loloiccl/Work/Git/nimly/nimly.nimble
  Verifying dependencies for nimly@0.1.0
      Info: Dependency on https://github.com/loloiccl/nimltype@>= 0.1.0 already satisfied
```

and no tests are executed.

**Comment by dom96** [comment]
You can specify your own ``test`` task as a workaround.

**Comment by genotrance** [comment]
I could not reproduce this on Linux or OSX.
