### ISSUE TITLE
Local `nimble install` should initialize git modules

### ISSUE THREAD

**Issue by matkuki** [nim-lang/nimble#498]
Currently when cloning a package repository to your local computer and installing the package via `nimble install` does **not** initialize the git modules. Git modules are only initialized if a packege is installed from a remote repository , for example `nimble install mypackage`. 
This functionality should be added.

**Comment by dom96** [comment]
Hmmm, I'm not sure I agree. You've cloned the Git repo, it should be your responsibility to initialise any submodules.
