### ISSUE TITLE
Latest tag resolution seems to be broken for some projects

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/nimble#499]
I have created a new tag (v0.3) in the nim-glfw project. Nimble can find the new tag when I use this command:

```
% nimble search nim-glfw --ver
...
nim-glfw:
  url:         https://github.com/ephja/nim-glfw (git)
  tags:        library, glfw, opengl, windowing, game
  description: A high-level GLFW 3 wrapper
  license:     MIT
  website:     https://github.com/ephja/nim-glfw
  versions:    0.2, v0.3, v0.21
```

Yet when I try to install the package, it insists on installing a previous version:

```
% nimble install nim-glfw
...
Downloading https://github.com/ephja/nim-glfw using git
  Verifying dependencies for glfw@0.2.1
 Installing glfw@0.2.1
    Prompt: glfw@0.2.1 already exists. Overwrite? [y/N]
    Answer: y
   Success: glfw installed successfully.
```

This doesn't make any sense to me, what is happening? I tried many stupid things over the last hour to no avail, I just cannot get it to work correctly...

Verbose mode doesn't give me any useful info either that would help troubleshooting the issue.

**Comment by genotrance** [comment]
Not 100% sure but I'm guessing it's because your tags are 0.21 and 0.3 (instead of 0.2.1 and 0.3.0) and 21 > 3. If you change your latest tag to 0.30, it might work. You might want to match your tags to the versions in your `glfw.nimble`.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/version.nim#L52

**Comment by dom96** [comment]
Yep, v0.21 > v0.3. This isn't a bug AFAICS.

**Comment by Araq** [comment]
Agreed, 21 is greater than 3.

**Comment by johnnovak** [comment]
Okay, I think it it makes sense now. I have "inherited" this project and I haven't created nimble packages before... I guess what confused me was that in the nimble file "0.2.1" and "0.3.0" are specified as version, but tags are indeed "v0.21" and "v0.3" and nimble just looks at the tags to determine the latest version. I'll try to clean up the project, thanks guys.
