### ISSUE TITLE
removing a project can break any future usage of nimble because of a nimble link.

### ISSUE THREAD

**Issue by curioussavage** [nim-lang/nimble#501]
While working on a nimble project removed a directory containing a different nimble project and now after making a new one and trying to run nimble install I get `The .nimble-link file is pointing to a missing file: /home/<username>/projects/nim-app/lua/lua.nimble`

This was fixed by removing a nimble-link file in  `.nimble/pkgs/lua-#head

**Comment by Araq** [comment]
This is not a high priority bug. It has a clear error message and an easy manual solution. But hey, what do I know.

**Comment by curioussavage** [comment]
ugh. Sorry for the crappy issue description. I'm glad you guys seem to understand the problem anyways. 

As a newcomer to Nim the message seemed a little unclear especially since the file path in the message just goes to my deleted project. If nimble knows that the file in pkgs/lua-#head is the problem why not print out that in the message? 

I read the readme section a out nimble-link. Maybe I could add a note there to explain where these files are stored? Also I am pretty sure I never ran `nimble develop` maybe it was run during install of a package? In any case not having done that manually its even less likely I have the context.
