### ISSUE TITLE
Nimble looking for inexistant lib folder on Linux

### ISSUE THREAD

**Issue by breakfast1** [nim-lang/nimble#502]
For the record:

```
~/nim-experiments$ nimble -v
nimble v0.8.10 compiled at 2018-06-14 16:21:57
git hash: 6a2da5627c029460f6f714a44f5275762102fa4b

~/nim-experiments$ nim -v
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release
```

I am confronted to the following error messages:

```
~/nim-experiments$ nimble path compiler
     Error: Nimble cannot find Nim's standard library.
        ... Last try in:
        ...   - /home/[...]/.nimble/pkgs/lib

~/nim-experiments$ ls ~/.nimble/pkgs/lib
ls: cannot access '/home/[...]/.nimble/pkgs/lib': No such file or directory
```
But `.nimble/pkgs` exists.

How can I fix this error ? Because I don't know where `lib` is (I suspect it doesn't exist at all), I setting `NIM_LIB_PREFIX` won't fix my issue.

**Comment by breakfast1** [comment]
It was because I installed with `choosenim`.

Fix: `export NIM_LIB_PREFIX=$HOME/choosenim/toolchains/nim-0.18.0`

**Comment by JohnAD** [comment]
Just FYI for others seeing this: in linux, choosenim prefixes the directory with a period, so I put:

```
export NIM_LIB_PREFIX=$HOME/.choosenim/toolchains/nim-0.18.0
```
into my `~/.profle` for *bash*.
