### ISSUE TITLE
Make nimble init generate the Nimble project dir too

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nimble#503]
Right now, `nimble init foo` generates `src/foo.nim`, etc. directly in the current directory.

I would expect that to generate those but **first create a `foo` directory** and then generate those inside that.

https://gitter.im/nim-lang/Nim?at=5b22b38dc277fb705dce91fa

**Comment by euantorano** [comment]
Rust's `cargo` solves this by having two commands:

- `cargo new`: `Create a new cargo package at <path>`
- `cargo init`: `Create a new cargo package in an existing directory`

That way both options are provided.

**Comment by kaushalmodi** [comment]
Thanks. Having `nimble new` would be good too.

**Comment by Araq** [comment]
Maybe we can come up with more descriptive names though, ``nimble fill``?

**Comment by euantorano** [comment]
@Araq Sure. I assume `nimble fill` would be in place of `cargo init` where it fills the current directory and `nimble new` (or `nimble create` or something similar) would be in place of `cargo new` where it creates a new directory and fills it?

**Comment by dom96** [comment]
Is there really a need for a new command name for this?

**Comment by euantorano** [comment]
@dom96 I suppose `init` could be extended to `nimble init foo`, with `foo` being `.` implicitly...

**Comment by stefanos82** [comment]
All we need is an extra sub-flag with init: `nimble init --new foo`, which means "initialize directory named foo and if this directory does not exist, then create it and then initialize it".
