### ISSUE TITLE
Feature: adding a 'type' field to .nimble file spec

### ISSUE THREAD

**Issue by JohnAD** [nim-lang/nimble#508]
I'm using nimble for both public projects as well as personal ones. And, I'm writing various ad-hoc tools for managing them.

And, in general, each project is one of three kinds:

1. Apps (aka stand-alone executables)
2. Libraries
3. App/Library Hybrids (rare)

So, if I write some quick script that manages my various projects, they might behave different depending on whether I'm writing an app or a library. But, right now, there is nothing in the library that bluntly determines what kind of project it is. For now, I'm using an ad-hoc private method for determining it, but it would be nice if there were a way to explicitly declare this in the nimble file. I suspect other folks could use it universally for other projects.

So, my feature suggestion is to allow such an indicator in the .nimble file. The nimble app need not use it; but possibly could in the future. It's potential values should be locked down, however. Perhaps strictly only allowing `app`, `library`, or `hybrid` for target values. Adding more if the community finds a new category.

examples:

```
# Package
version       = "0.1.0"
author        = "Wil Smith"
description   = "MIB tracker"
license       = "MIT"
srcDir        = "src"
type          = "app"
```

or

```
# Package
version       = "0.4.3"
author        = "T Stark"
description   = "Jarvis API module"
license       = "MIT"
srcDir        = "src"
type          = "library"
```

**Comment by dom96** [comment]
I'd rather not do this. Why do you need to determine this in your tool?

**Comment by JohnAD** [comment]
First a caveat: I'm perfectly okay with the community saying "no" to this feature. Work-around is easy (such a "nimble-details.json" file.)

PERSONAL USE

I've got a tool that I keep expanding on called `docnimble` that generates documentation in RST and Markdown formats for GitHub hosting and PDF/epub/etc. export; using both the RST comments in source and with support documents in `/docsrc` subdirectory.

So, when I run `docnimble <project>.nimble` in the root of the project, it reads the nimble file and grabs useful information in it, including `srcDir`.

If the project is a **library**; it generates documentation for the intended audience: other programmers wanting to use the library.

* This includes the intro from `/src/<project>.nim` and a chapter for each `/src/<project>/<*>.nim` file.
  * Plus, a reference appendix providing the RST equivalent of `nim doc <project>.nim`.
* A chapter for the LICENSE
* The title page features the version prominently as well as repo details.
* A tiny TOC table at the bottom of each chapter/appendix.

If the project is an **app**; it generates different documentation for the intended audience: end users wanting to use the app (or play the game.)

* A graphical cover for the epub/PDF version. 
* License information and other details in smaller print on the inside cover equivalent.
* A big-standalone table of contents after the cover.

And, of course, if it is an app, it does not have the references appendices. That would be a confusing thing to add :).

GENERIC USE # 1

I suspect that this might become useful for reference tools like the **nimble.directory** web site. While most of the packages on that web site are libraries; there isn't (as far as I can tell) a way of technically separating those things. Or a way to add that criteria to the search. When a user is looking for "xyz" he/she probably already knows whether they want a library or an app already.

Just to pick on one app randomly:
  https://nimble.directory/pkg/ndf

After I `nimble install ndf`; do I put `import ndf` into my source code? (Well, actually, technically I *could*. But that really isn't the point of that package.)

GENERIC USE # 2 

This would also be of use for anyone who try to solve the OS-dependent "system-wide install" for a distribution or a stand-alone tool. That flag would help prevent applying such a solution to a library.

Sorry about the long response. Like I said, I'm perfectly okay with "no". I'm not even pushing it hard. I just have a sneaky suspicion that making app vs library distinctions might become increasing important.

**Comment by dom96** [comment]
So this is the reason why Nimble is available as a library as well. I think you should be using it to enumerate the Nim source files inside a specific package, this can be done using this function: [``iterInstallFiles``](https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/packageinfo.nim#L478).

The API isn't really documented all that well so feel free to ask me how to make use of this function if it's unclear. The package type can then be determined by checking whether the ``PackageInfo`` has a ``bin`` specified:

* ``bin`` + install files present -> Hybrid
* ``bin`` + no install files -> App
* Install files present -> library

----

The Nimble package directory can use the same method, but what will be better is if all packages are tagged appropriately with ``library`` or ``app`` (many already have these tags).

**Comment by JohnAD** [comment]
Ah, so the details are there already. Perfect.

I can't use nimble as a library right now as it crashes. I suspect it's becuase I'm using nim 0.18.0 and nimble is pulling in compiler#head. No biggy, I'll just use it for guidance in parsing the .nimble file.

But if you have time to answer: if the `.nimble` file does not specify `skip...` and `install...` directives; does that mean it automatically installs all the files in the package? In other words, a package is a library by default (because it has install files), unless you specifically exclude all the install files? An app's `.nimble` file should be something like:

```
# Package
version       = "0.1.0"
author        = "Wil Smith"
description   = "M.I.B. tracker"
license       = "MIT"
srcDir        = "src"
installDirs   = @[]
bins          = @["mibtracker"]
```

(Way off topic: is the .nimble file actually source code? That would make for interesting security border cases.)

**Comment by JohnAD** [comment]
Thanks for the help! I'll mark this as closed.
