### ISSUE TITLE
Cross-compiling

### ISSUE THREAD

**Issue by ehmry** [nim-lang/nimble#510]
It would be nice to fetch a packet to `.nimble` and then cross-compile to a local directory, with a local nimcache and local outputs. I'm willing to make this happen but I would like to know if anyone else is interested in such a feature.

**Comment by dom96** [comment]
If you create something like this then please do so as a separate program. It's IMO outside of Nimble's scope.

**Comment by ehmry** [comment]
Supporting platforms that aren't self-hosting is out of scope?
