### ISSUE TITLE
directed acyclic graph (DAG) dependencies cause a pkg to be installed twice, prompting a user prompt, causing travis to timeout

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#511]
/cc @dom96
all the context is given here: https://github.com/nim-lang/Nim/issues/8227#issuecomment-403190112
the root cause of travis failing on my PR seems to be a DAG that causes a pkg to be installed twice, causing a prompt "already exists. Overwrite?" after `nimble install`, causing travis to timeout and fail

**Comment by dom96** [comment]
Indeed. It's a known bug.

**Comment by dom96** [comment]
Duplicate of #184.
