### ISSUE TITLE
catching vcpkg c/c++ packages

### ISSUE THREAD

**Issue by develooper1994** [nim-lang/nimble#513]
Can we catch vcpkg packages in nimble to use as c++ backend. It will extent package number. So we can automaticlly use boost, opencv, qt, ...

**Comment by dom96** [comment]
What do you mean "catch"?

**Comment by develooper1994** [comment]
Catch means using vcpkg packages inside nim. If there is a bridge between vcpkg and nimble nim package numbers will become so many.
Like;
Nimble install boost-hana:x86-windows-static

**Comment by develooper1994** [comment]
Catch means using vcpkg packages inside nim. If there is a bridge between vcpkg and nimble nim package numbers will become so many.
Like;
Nimble install boost-hana:x86-windows-static

**Comment by dom96** [comment]
Sorry but Nimble won't be supporting vcpkg packages.
