### ISSUE TITLE
quoting wrong when parsing flags

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#514]
this seems to be an error with nimble syntax; not sure if this is the right place to post this or if it belongs to Nim repo:

in https://github.com/mratsim/Arraymancer for example here: https://github.com/mratsim/Arraymancer/blob/0605c7fcd34e216623a891f4963d2a4ef98882b1/arraymancer.nimble#L112

change:
--nimcache: "nimcache" to --nimcache: "nimcache withspace" in code below:

```nim
proc test(name: string, lang: string = "c") =
  if not dirExists "build":
    mkDir "build"
  if not dirExists "nimcache":
    mkDir "nimcache"
  --run
  --nimcache: "nimcache"
  switch("out", ("./build/" & name))
  setCommand lang, "tests/" & name & ".nim"
```
and run nimble test: it'll fail with: `Error: cannot open 'nimcache2.nim'`
which is due to wrong quoting applied to nimcache argument,

it's obviously a contrived example, but it's not contrived with another flag, eg:
```nim
  --name: "bob morton"
```

NOTE: I originally got suspicious after seeing `nimble test` fail with following error message: 
 Error: Execution failed with exit code 35584
        ... Command: "/Users/timothee/.nimble/bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/nimblas-0.2.1" --path:"/Users/timothee/.nimble/pkgs/nimlapack-0.1.1" --path:"/Users/timothee/.nimble/pkgs/nimcuda-0.1.5" --path:"/Users/timothee/.nimble/pkgs/nimcl-0.1.3" --path:"/Users/timothee/.nimble/pkgs/opencl-1.0" --path:"/Users/timothee/.nimble/pkgs/clblast-0.0.1" --path:"/Users/timothee/.nimble/pkgs/opencl-1.0" --path:"/Users/timothee/.nimble/pkgs/stb_image-2.1" "--out:./build/tests_cpu" "--run" "--nimcache:"nimcache""  "tests/tests_cpu.nim"

which showed wrong quoting for `"--nimcache:"nimcache""` (should've been `"--nimcache:\"nimcache\""` or anything equivalent)

**Comment by dom96** [comment]
Nimble uses parseopt for parsing command line arguments so this is likely a stdlib issue.

**Comment by pb-cdunn** [comment]
@dom96, Could you switch **Nimble** to `parseop2`, which handles quotes and spaces properly?

**Comment by dom96** [comment]
``parseopt2`` is deprecated so no. Please report the issues that plague ``parseopt`` so we can fix it.

**Comment by pb-cdunn** [comment]
I agree with everything c-blake has posted on `parseopt`.
