### ISSUE TITLE
wrong path handling in error message

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#516]
* suppose ~/.config is a symlink to /Users/timothee/myconfig
* add any invalid flag in ~/.config/nim.cfg, eg: `--hint[unexistant]=on`

git checkout //github.com/status-im/nim-ranges
cd nim-ranges

```
nimble --verbose check
    Setting Nim stdlib prefix to
    Setting Nim stdlib path to /Users/timothee/git_clone/nim/Nim/lib
       Info Users/timothee/myconfig/nim.cfg(1, 3) Error: unknown hint: unexistant
       Info   --hint[unexistant]=on
     Error: Could not validate package:
        ... Could not read package info file in /Users/timothee/git_clone/nim/nim-ranges/ranges.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
```

* BUG1: the error message strips leading `/` : `Users/timothee/...` instead of `/Users/timothee/...`
* BUG2: the symlink is resolved, it should not:
ideal msg should show this path: `/Users/timothee/.config/nim.cfg`

this may either originate in a bug in ospaths.nim (see https://github.com/nim-lang/Nim/issues/8177), or be a misuse of it, not sure

**Comment by Araq** [comment]
What is wrong with resolving symlinks? Don't want to be reminded of the indirections you've created yourself?

**Comment by dom96** [comment]
IMO this is:

* Not a nimble bug
* So minor that if it bothers you you should create a PR instead of creating issues for it.

**Comment by timotheecour** [comment]
> BUG1: the error message strips leading / : Users/timothee/... instead of /Users/timothee/...

this has been fixed in the meantime
