### ISSUE TITLE
Question: what's the need for multiple module versions?

### ISSUE THREAD

**Issue by stefanos82** [nim-lang/nimble#523]
I have checked my `$HOME/.nimble/pkgs/` and found out two versions of a specific module.

My question is the following based on a security hypothesis: if version 0.0.1 has a serious vulnerability and a newer version 0.0.2 gets released, why should I still retain the affected module?

What's the actual point of having multiple versions?

**Comment by dom96** [comment]
Because version 0.0.1 might be required by another package. Maybe 0.0.2 introduces a breaking change.
