### ISSUE TITLE
Running "nimble install package2" in package1's directory runs the install task for package1 as well

### ISSUE THREAD

**Issue by genotrance** [nim-lang/nimble#524]
Using @dom96's workaround for installing nimgen dependencies before package install:

```
# nimscintilla.nimble

before install:
   exec "nimble install nimgen -y"            # <==== infinite loop
   exec "nimgen nimscintilla.cfg"
```

If you `nimble install -y` in the `nimscintilla` folder, nimble recurses forever since it installs the nimscintilla.nimble file again and again instead of just installing nimgen.

**Comment by dom96** [comment]
For reference: the issue here appears to be that ``nimble install foobar`` will read the .nimble in the current directory and execute any tasks. So because the .nimble in @genotrance's case has a `before install` it gets executed, it shouldn't be executed.

**Comment by genotrance** [comment]
Workaround for this specific use case:

```
before install:
    withDir "..":
        exec "nimble install nimgen -y"
    exec "nimgen nimscintilla.cfg"
```

**Comment by jyapayne** [comment]
@genotrance awesome, that's a pretty easy workaround

**Comment by genotrance** [comment]
Unfortunately, this workaround isn't without issues. The `nimble install nimgen -y` downloads and installs nimgen every single time you do an install, even if nimgen is already installed at the latest version. That's probably because it has to download and check the nimble file for versioning but it also builds the binary every single time.

**Comment by dom96** [comment]
Sure, it's not perfect. My plan to implement task-level requirements should fix those issues.
