### ISSUE TITLE
Adding a specifier for the compiler version to use

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/nimble#529]
Either a specific version, or perhaps a version range, or a specific git hash, etc.

So that when you run 'nimble install' or 'nimble build' it can also do 'choosenim' to use the correct version of the nim compiler that's known to work well with this package.

I'm more or less looking at how Haskell's "stack" utility works, alongside it's LTS/nightly releases. Or eg at Nix, with the reproducible builds.

Have been bit a few times with being unable to compile nim libraries and utilities due to compiler incompatibilities (most recent eg: c2nim, while my globally-installed/available version of the Nim compiler is at the latest dev version).

**Comment by dom96** [comment]
I don't think getting Nimble to change the Nim version by using ``choosenim`` is a good idea. Mainly because that will also change the Nimble version.

Nimble will already report the Nim version that is required for packages so that should be good enough.
