### ISSUE TITLE
`-y` flag doesn't work for `test`

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/nimble#540]
ostensibly, `nimble test` is supposed to install dependencies, but there's no way to disable the prompts with the `-y` flag

**Comment by dom96** [comment]
`test` is just a task. If you want to disable prompts then define a task that does so.

We can make the default `test` task support this in the long term.

**Comment by arnetheduck** [comment]
I'm looking at it from a user point of view:
Case 1:
* I type `nimble install`
  * nimble reads dependencies
  * downloads missing ones
  * asks questions
  * runs the rest of install
  

Case 2:
* I type `nimble test`
  * nimble reads dependencies
  * downloads missing ones
  * asks questions
  * runs the task
  
notice how they're the same, including the question-asking bit. I don't see why `-y` should work in one case and not in the other.

**Comment by dom96** [comment]
I think this was fixed in cd5db600dc7cd3a3306e5c0c4c56f2c399af29e1
