### ISSUE TITLE
Error during listing nimble package versions

### ISSUE THREAD

**Issue by stefanos82** [nim-lang/nimble#546]
Specs:
```
OS: Debian testing 64-bit, fully updated
```
```
Nim Compiler Version 0.19.0 [Linux: amd64]
Compiled at 2018-09-28
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: d993b9420bcf49f8e49acbb8169ff24f46bfc8df
active boot switches: -d:release
```

I run `nimble list --ver` and while was fetching the entire list, it threw the following error message:

![image](https://user-images.githubusercontent.com/1777466/46181898-10c37b00-c2d1-11e8-8859-fd0b1544045d.png)

**Comment by Araq** [comment]
Does it fail always or just sometimes?

**Comment by stefanos82** [comment]
Since the latest pulling, I get this issue. I don't remember getting this error before.

**Comment by dom96** [comment]
Do you run ``nimble list --ver`` often? Why?

**Comment by dom96** [comment]
All this needs doing is to improve the error message. I think Stefanos got rate limited by GitHub here or something or just got an intermittent network failure.

**Comment by genotrance** [comment]
Is `nimble list --ver` even relevant anymore? We have more than 1k+ packages now.
