### ISSUE TITLE
Can't pass compiler flags to `nim build`

### ISSUE THREAD

**Issue by ndarilek** [nim-lang/nimble#547]
Hey, Nim newbie here. I've been scouring the docs and haven't found a solution for this, so if there is one then perhaps it can be documented more visibly. :)

I have a project which I primarily test by running natively, but my main goal is compiling to webassembly via Emscripten. I have the following nim.cfg snagged from the forum:

```
@if emscripten:
  cc = clang
  clang.exe = "emcc"
  clang.linkerexe = "emcc"
  clang.options.linker = ""
  cpu = "i386"
  passC = "-s WASM=1 -s 'BINARYEN_METHOD=\"native-wasm\"' -Iemscripten"
  passL = "-s WASM=1 -Lemscripten -s ALLOW_MEMORY_GROWTH=1"
@end
```

I also have a config.nims which does something similar.

Here's where my newbie flag flies high. :) I assume I want to put my project in a Nimble package, even if I don't publish it, so I can use Nim dependencies. If I want to build my code with those dependencies, I have to run `nimble build`. But as of now, I see no way to run something like `nimble build -d:emscripten` so the environment is correctly set up for Emscripten builds. I can use `nim c -d:emscripten ...` just fine, but then I won't be able to use Nim native dependencies. And maybe `nimble c ...` works, but again, I don't see that I can pass `-d:emscripten` for the times when I'm ready to build to wasm.

It seems my choice is either use Nimble, Nim dependencies, and pick one target, or use `nim c`, no Nim dependencies, and have the flexibility to switch targets. Is that accurate, or is there some hidden flag to pass command line parameters to `nimble build`? :)

Or should I not be using defines for this?

Thanks.

**Comment by dom96** [comment]
If you want a choice then create a task:

```
task emscripten, "Builds with emscripten":
  exec "nimble c -d:emscripten file.nim"
```

(Untested, but should give you the basic idea)

If your package should always be compiled via emscripten then don't use the defines.

**Comment by AchalaSB** [comment]
How can I pass `wasm32-unknown-unknown` without `emscripten` ?? I mean by using `clang`?

**Comment by dom96** [comment]
@AchalaSB are you just trying to use Nim with emscripten in general? If you google around you should be able to find plenty of pointers on how to do that.

**Comment by AchalaSB** [comment]
@dom96 No I'm asking without emscripten.. 
is this pass `nimble build --target: wasm32-unknow-unknown` correct?? 
If no what is correct approach??

**Comment by genotrance** [comment]
I believe this is what @Araq was asking for as well.

**Comment by dom96** [comment]
This should be resolved now. You can use ``--passNim`` to pass flags to Nim when using ``nimble install`` (for example ``nimble install --passNim:-d:danger``) and when running ``nimble build`` any flag you pass is passed to Nim (for example ``nimble build -d:danger``).
