### ISSUE TITLE
 "Cycle with 'Tab', 'Enter' when done" does not work on windows.

### ISSUE THREAD

**Issue by treeform** [nim-lang/nimble#551]
Related to this: https://github.com/nim-lang/nimble/pull/441

Maybe just use the old method on windows? Command line sucks on windows.

I am using windows 10 64 bit.

**Comment by nc-x** [comment]
Works for me in cmd, powershell, and cmder on Windows 10 x64 1903.

**Comment by dom96** [comment]
Awesome, so we can close. @treeform reopen if it's still broken for you.

**Comment by nc-x** [comment]
@dom96 
Thinking more about this issue, the console and related stuff on Windows is now continuously being worked on, so you need to always be on the latest windows version, and in the future, use the new windows terminal.
Maybe, old windows version have this issue. 
So you will have to decide whether nimble supports the latest windows 10 version *only* or whether older builds are supported. 
IMO the best approach would be to check the windows build, keep this code for latest windows, and for older windows 10 builds, or older windows like 7, 8 etc, it would be required to implement a fallback mechanism.
