### ISSUE TITLE
Add a `nimble clean` command to clean up build files.

### ISSUE THREAD

**Issue by davidgarland** [nim-lang/nimble#555]
Having a built-in `nimble clean` command that cleans up any test or binary files that have been built via for instance `nimble build` would be nice. Not quite as pressing of an issue now that nimcache in the local directory isn't a thing, but it would still be a huge improvement over having to write

```Nimble
task clean, "Cleans up files":
  exec "rm <project_binary_name_here>"
```

for every project.

**Comment by jabbalaci** [comment]
I just noticed that "nimble test" creates a binary file for every test file in the `tests/` folder. It would be nice if `nimble test` could do a cleanup, for instance via an option: `nimble test --clean`.

**Comment by epasveer** [comment]
The latest "pull" works well for me.
