### ISSUE TITLE
`nimble develop` ends up in detached state instead of a branch (eg master)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#556]
```
nimble develop jester
cd jester
git branch|cat
* (no branch)
```

## maybe related:
[Manually checks out the branch/tag after git clone. by gradha · Pull Request #70 · nim-lang/nimble](https://github.com/nim-lang/nimble/pull/70)
which seems (haven't looked carefully) that the intent was to checkout a branch

**Comment by dom96** [comment]
``nimble -v``?

**Comment by timotheecour** [comment]
nimble -v
nimble v0.8.11 compiled at 2018-08-29 02:50:24
git hash: 57f73ea2688047ed47889ce6b9029247b387cee9

**Comment by timotheecour** [comment]
ok works after rebuilding via `./koch tools` 

nimble -v
nimble v0.9.0 compiled at 2018-10-11 19:56:06
git hash: f7373e03d58a4d0da2f236d5f9979ffa953dd621
