### ISSUE TITLE
My package won't install its library files

### ISSUE THREAD

**Issue by ndarilek** [nim-lang/nimble#561]
I'm trying to improve https://github.com/ndarilek/napibindings and to use it from other code. Unfortunately, running `nimble install` from within this package only installs the napibuild binary. It doesn't copy sources from src such that other code can use it.

What am I missing? To the best of my knowledge, this should compile and copy src/napibindings.nim and its dependencies into the package's install location.

Thanks.

**Comment by genotrance** [comment]
Binary packages won't copy source files. Perhaps add installExt for Nim files or check out :

https://github.com/nim-lang/nimble/blob/master/readme.markdown#hybrids

**Comment by dom96** [comment]
Yes, docs are outdated. This was changed recently.

**Comment by dom96** [comment]
Yes, it is. See changelog: https://github.com/nim-lang/nimble/blob/master/changelog.markdown#090---19092018

**Comment by pb-cdunn** [comment]
Let's mention `installDirs` in the "Hybrids" section. Then close this Issue.

But make it extremely clear, with a reference to a working example. The exactly proper way to do this is not obvious.

I have files `./src/daligner/*.nim`, and here are my `.nimble` settings:
```
srcDir = "./src"
installDirs = @["daligner"]
bin = @["daligner/LA4Falcon"]
```
That works!

**Comment by vinitextos800** [comment]
Other files will be copied in the same way as they are for library packages.

Binary packages should not install .nim files so include |skipExt =
@["nim"]| in your .nimble file, unless you intend for your package to be
a binary/library combo.

So looks like installing other .nim files is opt-*out*, not *in*. I'll
give your suggestion a shot, but as of now things don't appear to work
as documented. Você pode ver mais no [Duralong Bula](https://www.maesabetudo.com.br/duralong/)

**Comment by dom96** [comment]
Exposing a library should be intentional. I think it's better that the library is not exposed, rather than exposed by accident.

**Comment by genotrance** [comment]
Docs have been updated, closing this.
