### ISSUE TITLE
Binary in subdirectory generates wrong output path

### ISSUE THREAD

**Issue by ndarilek** [nim-lang/nimble#564]
My package has a binary in src/napibindings/napibuild.nim. In the .nimble file I have:

```
bin  = @["napibindings/napibuild"]
```

When this builds, however, on the command line I see:

`-o:"/sysroot/home/nolan/src/napibindings/napibindings/napibuild"`

And the link fails because src/napibindings/napibindings doesn't exist. Seems to be double-concatenating the package name. I tried leaving napibuild.nim directly in src, but this threw a warning.

I recognize this isn't the documented project layout, but it seems like this case should either generate a warning if it isn't supported, or fail out-right without generating a bad command line. I'm also not sure how a package can ship multiple binaries and a library if putting files in the same directory throws warnings, but putting them in subdirectories generates bad compiler flags.

Thanks.

**Comment by dom96** [comment]
Indeed, this is a bug. Make sure you've got the latest Nimble though please, you shouldn't be getting warnings unless you've also got ``installExt`` (or similar) in there.

**Comment by dom96** [comment]
I made an attempt to reproduce this but couldn't. I added a test of what I tried. Assuming that this has been fixed in the meantime.
