### ISSUE TITLE
`nimble build` should display warnings produced by the nim compiler

### ISSUE THREAD

**Issue by nc-x** [nim-lang/nimble#572]
For eg. I use the now deprecated `.this` pragma in this project - https://github.com/nc-x/crafty
   
`nim c src\crafty.nim` shows the expected warnings -
```
Warning: the '.this' pragma is deprecated [Deprecated]
```
`nimble build` does not show any warnings while compiling the project.

**Comment by dom96** [comment]
Hmmm, that's up for debate.

Note that you can use `nimble c src/crafty` which should show you warnings.

**Comment by Araq** [comment]
There are few reasons Nimble should ever swallow Nim's messages IMO.

**Comment by dom96** [comment]
`nimble build` is for end-users of Nim software. Because of that I disagree that it should show Nim's warnings. If you want warnings then you can use `nimble c`, I think that's fair.
