### ISSUE TITLE
nimble allows installing package with same name

### ISSUE THREAD

**Issue by tim-st** [nim-lang/nimble#573]
When installing two packages from different sources and different authors but with same name, it works if the package which gets installed has a greater version number.
~~The~~ One problem is that `nim` doesn't support loading the package anymore.

Example:
1) `nimble install https://github.com/ephja/lzma` installs `lzma@0.1.0`
2) `nimble install https://github.com/tim-st/nim-lzma@#test-nimble-version` installs `lzma@0.1.1`
3) in nim `import lzma` fails with `cannot open file lzma` now.

**Comment by dom96** [comment]
Any proposals on how to fix this?

**Comment by tim-st** [comment]
The easiest way would be to not allow to install the package if a package with same name and different author (is the author name unique enough?) already exists. Of course this has downsides but I don't see a better solution when importing by url scheme (like Go supports) is not supported (`import "github.com/user/package"`).

For the referenced issue I think it should be allowed and if author is same and package version is greater install normal way, if package author is different then only the package which explicitly depends on the package by url should load this dependency.

When "importing by url scheme as string" would be supported only packages that were installed by package name should be importable by package name (because they came from nimbles official list and are unqiue there) all others woud be forced to import by url scheme.

**Comment by alehander42** [comment]
can't we specify an alias on nimble level?

**Comment by dom96** [comment]
Import by url would require a major change in the Nim language.

**Comment by dom96** [comment]
I'm going to merge this into #574, these issues are pretty similar. I've put my thoughts on how to fix this in there (I think we should look at repo URL for uniqueness).
