### ISSUE TITLE
Don't throw an error when a command fails, just quit

### ISSUE THREAD

**Issue by coolreader18** [nim-lang/nimble#583]
When I'm prototyping/developing something, especially something like a macro, I don't usually need to see the whole stack trace through nimble when compilation fails. I think it'd be good to change the `raise` in [tools.nim](https://github.com/nim-lang/nimble/blob/22aa3c1d1392d7878d039250ecf0ffeadf3ba0cc/src/nimblepkg/tools.nim#L28) to just an `quit(errMsg)` or something of the like.

**Comment by dom96** [comment]
The reason you see a stack trace is because Nimble was compiled in debug mode. In release mode it doesn't show a stack trace.
