### ISSUE TITLE
`nimble develop https://github.com/ba0f3/scram.nim` doesn't strip extension; nimble develop scram strips extension

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#584]
oftentimes nimble packages start out using just a url so installation is `nimble develop https://github.com/ba0f3/scram.nim`  ; this installs to scram.nim  (actuall ba0f3/scram.nim but that's a separate issue covered in https://github.com/nim-lang/nimble/issues/577)

then when they get published to nimble packages, preferred installation becomes `nimble develop scram` ; this installs to scram instead of scram.nim
this is inconsistent (scram vs scram.nim)

**Comment by dom96** [comment]
Maybe you could tell people to name their repo the same as their package? ;)

In all seriousness. It sucks, but ok, we can clone the repo into /tmp, find the name of the package and then move it to the appropriate directory. Shouldn't be too hard to do. I do hate this extra complexity though.

**Comment by timotheecour** [comment]
> Maybe you could tell people to name their repo the same as their package? ;)

that may not always be possible, for disambiguation (eg if you have https://github.com/myorg/foo.nim and https://github.com/myorg/foo.py )
also, I did a search before posting this, IIRC there were about 500 packages with an extension, so we can't just ignore this issue

**Comment by dom96** [comment]
Honestly, this is such a minor issue that I don't think it deserves an issue. If you want to get around it just clone the repo yourself and name it whatever you want, then use `nimble develop`.
