### ISSUE TITLE
make `task` string msg optional: most ppl just have a useless name

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#585]
a lot of taks are written as:
```nim
task test, "Test":
  ...
```
or 
```nim
task test, "":
  ...
```

so how about making that string optional, allowing however wants to have a useful string to write it, and others to just use:
```nim
task test:
  ...
```

**Comment by dom96** [comment]
The idea is to document what the task does. Making this optional would mean that no one would write docs for users so no, I don't think this should be allowed.
