### ISSUE TITLE
nimble doesn't download related files in the root directory of the github repository

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/nimble#586]
running:
nimble install nimx@#head

I get 3 folders: nimx, nimblemeta.json, and nimx.nimble
However the repository also has the folders docs, test, editor and other files.

Is that something the package is responsible for, or just an unintended consequence of what nimble expects from the directory structure? or just a bug?

**Comment by dom96** [comment]
Nimble only installs what is necessary for the package. Perhaps you want to use ``nimble develop`` instead?

**Comment by kobi2187** [comment]
I'm not sure but I think it does use the templates in test folder.
So, that's something the package owner can modify?
Thanks, and sorry if I posted in the wrong place
