### ISSUE TITLE
Pressing Enter on question with [y/N] does not trigger default (N), instead quits Nimble

### ISSUE THREAD

**Issue by Swader** [nim-lang/nimble#598]
# Scenario

Nimble asks something like `Prompt: eth_keys@0.0.2 already exists. Overwrite? [y/N]`

## Expectation

Pressing Enter triggers default (N, as indicated by uppercase letter) and continues.

## What actually happens

Nimble quits without any feedback.

**Comment by Swader** [comment]
Yes. When installing a project's dependencies, this question gets asked. Then pressing enter will cancel the whole process.

**Comment by dom96** [comment]
Unfortunately I'm going to need more info to reproduce this. I've tried to create a sample project that I thought would repro but all the dependencies are detected and there is no attempt to overwrite them. Can you share which project you were trying to install and the command-line you've used?

**Comment by Swader** [comment]
Try to install https://github.com/status-im/nimbus dependencies.

It's easy to repro if you depends on package X and on package Y which also depends on package X.

**Comment by dom96** [comment]
Just installed nimbus via ``nimble develop https://github.com/status-im/nimbus`` (no prompts and installation was successful). Also then tried `nimble install --depsOnly` in Nimbus' directory: also no prompts.

**Comment by Swader** [comment]
Interesting, must have changed in the meanwhile. Okay, let me find another example and post back.

**Comment by genotrance** [comment]
@Swader - any update on this issue?

**Comment by Swader** [comment]
Nope
