### ISSUE TITLE
allow to forward nim cmd line params to nimble: `nimble build|install [nimble options]  -- [nim options]`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#599]
as discussed on IRC
https://irclogs.nim-lang.org/04-01-2019.html#22:42:20

currently impossible to pass un-supported options, eg : `--debugger:native` ; instead all nim options should be passable as-is (without further checks, nimble shouldn't care about verifying it) after `--`

IIRC parseopt supports passing remaining args

EDIT(2019-01-29):
I was going to open another issue to make `nimble build --verbose` (ditto w install) more informative (currently no way to tell what it's doing when building a binary, besides the vague `Building nimterop/nimterop/toast using c backend` which doesn't tell me anything about options being used (eg doesn't tell if `-d:release` is used ; turns out its used for install but not build)  ; however I realized the best approach is just to fix this (#599), which enables more flexibilty; eg it would allow: `nimble build -- --verbosity:2 --hints:off` to address this particular point

**Comment by dom96** [comment]
Implemented in https://github.com/nim-lang/nimble/commit/5ec2ecea77434798133e5a1ec5f1a437d3947128

**Comment by timotheecour** [comment]
example (for reference):
```
nimble install -y -p:-u:release https://github.com/genotrance/nimgen
```
however, even with `--verbose`, nimble doesn't show the actual command used and instead shows the un-informative:
```
   Building nimgen/nimgen.exe using c backend
```
ideally it should simply show the command used, eg
nim c -o:nimgen/nimgen.exe -u:release nimgen/nimgen.nim
