### ISSUE TITLE
`nimble init` sometimes creates nimble package under a new root directory instead of under `cwd`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#611]
* running `nimble init` iniside a dir foo creates directly foo/foo.nimble => good
* running `nimble init` iniside a dir nim-foo creates directly nim-foo/nim_foo/nim_foo.nimble => BUG
it should just create it under `nim-foo` and ask the user to name the nimble in this case; a user then might say: `foo`, and it shall create `nim-foo/foo.nimble`, so it would be consistent with 1st scenario

**Comment by dom96** [comment]
Gonna merge this into #581. (No need to copy the contents of this issue there)
