### ISSUE TITLE
nimble c -r does not respect binDir

### ISSUE THREAD

**Issue by arnavb** [nim-lang/nimble#614]
When I run `nimble c -r <some_file.nim>`, the resulting binary is placed right next to the file instead of in the binary directory specified through `binDir`. This makes it difficult to immediately commit things to source control without cleaning up build artifacts. `nimble build` does what I want, but then I can't run the binary in the same command.

TBH, I wish `nimble` followed [cargo](https://github.com/rust-lang/cargo), which generates a `target` folder for all build files instead of placing them in arbitrary locations. This makes it easy for the folder to be gitignored.

On the other hand, if you want to keep the semantics of `nimble c`, then instead implement a command called `nimble run`, analogous to `cargo run`, which respects `binDir`.

**Comment by dom96** [comment]
Happy to make ``binDir = "bin"`` the default. Also, happy to fix the ``nimble c`` issue.

**Comment by dom96** [comment]
On second thought I think `nimble run` will be better, I'd rather keep `nimble c` as just a thin wrapper over `nim c`.
