### ISSUE TITLE
Issues for nimble publish

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimble#618]
I guess I have just successfully published my minmaxheap package in the second try, first try failed with this message:

```
Info Creating PR
../../../lib/pure/httpclient.nim(224) httpError
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]

```

Two additional notes:

```
Prompt: Whitespace separated list of tags?
```

The question mark is very misleading, as general answer is yes/no. Better use a : at the end, or even better use this message: "Please enter a whitespace separated list of tags:"

And for this prompt, line editing works not that well, I was unable to use backspace key. (Linux Bash shell)

**Comment by dom96** [comment]
AFAIK this was resolved in latest Nim. Feel free to create a PR to improve the message. There is another issue for the lack of arrow keys support.
