### ISSUE TITLE
Crash trying to install nimble on OSX

### ISSUE THREAD

**Issue by hiteshjasani** [nim-lang/nimble#62]
Trying to install nimble on OSX tonight resulted in a crash.

``` bash
...
clang -c  -w -O3  -I/usr/local/src/Nimrod/lib -o /usr/local/src/nimble/src/nimcache/download.o /usr/local/src/nimble/src/nimcache/download.c 
clang -c  -w -O3  -I/usr/local/src/Nimrod/lib -o /usr/local/src/nimble/src/nimcache/config.o /usr/local/src/nimble/src/nimcache/config.c 
clang -c  -w -O3  -I/usr/local/src/Nimrod/lib -o /usr/local/src/nimble/src/nimcache/compat.o /usr/local/src/nimble/src/nimcache/compat.c 
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message
Traceback (most recent call last)
nimble.nim(810)          nimble
nimble.nim(785)          doAction
nimble.nim(569)          install
nimble.nim(475)          installFromDir
nimble.nim(424)          buildFromDir
tools.nim(18)            doCmd
Error: unhandled exception: Execution failed with exit code 256 [ENimble]
Error: execution of an external program failed
```

If I comment out the command at `nimble.nim:424` then the install works fine.  However the command it's trying to execute `nimrod c -d:release --noBabelPath  "/usr/local/src/nimble/src/nimble.nim"` shouldn't crash.

Here are my install steps:
- `git clone https://github.com/nimrod-code/nimble.git`
- `cd nimble`
- `nimrod c -r src/nimble install`

Software
- `Nimrod Compiler Version 0.9.6 (2014-10-21) [MacOSX: amd64]` built from 'devel' branch source
- `Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)`
- `OSX Yosemite Version 10.10`

**Comment by tastyminerals** [comment]
Hey guys, I stumbled upon this thread as I am getting the same error right now.
`nimble install aporia@#head`
`Error: unhandled exception: /home/user/.nimble/packages.json(1, 0) Error: { expected JsonParsingError]`
nim compiler version is 0.11.2

**Comment by dom96** [comment]
Your packages.json is likely empty. Can you try ``nimble update``?

**Comment by tastyminerals** [comment]
Submitted an issue in `nimble` issues. 
```
Downloading package list from https://github.com/nim-lang/packages/raw/master/packages.json
Error: unhandled exception: 404 Not Found [HttpRequestError]
```
