### ISSUE TITLE
Nimble cannot find nimscriptapi in certain cases

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#620]
This seems to be affected by the current working directory:

```
        ... Could not validate package:
        ... Could not read package info file in /Users/dom/.nimble/pkgs/nimble-0.9.0/nimble.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     /Users/dom/.nimble/pkgs/nimble-0.9.0/nimble.nimble(33, 1) Error: undeclared identifier: 'task'.
```

`nimble check` works in Nimble dir, but not if I `cd ~/.nimble/pkgs/nimble-0.9.0`

**Comment by dom96** [comment]
The bug is that the Nim VM doesn't load the `nimscriptapi` file because it's in two of its search paths. If I remove `~/.nimble/pkgs/nimble-0.9.0/nimblepkg/nimscriptapi.nim` then it works :/

**Comment by dom96** [comment]
I couldn't even work around this. I'm guessing Nim HEAD has an issue here, can you take a look @Araq? https://github.com/nim-lang/nimble/compare/issue-620

**Comment by jangko** [comment]
failed on windows too [here](https://ci.appveyor.com/project/jangko/nim-noise/builds/23179412/job/cvuome78am6dx3l2)
but sometimes it also [works(https://ci.appveyor.com/project/jangko/nim-noise/builds/23179412/job/68lt985slnv3uekr)], weird.

**Comment by Araq** [comment]
Has been fixed in the compiler but nimble install nimble bugs should never be "High priority", the way to install/update nimble is koch nimble and has been for years.

**Comment by genotrance** [comment]
@Araq - agree for using nimble as a binary but `nimble install nimble` is required for nimble as a library. For example, choosenim uses some portions of nimble and runs into this issue.

**Comment by Araq** [comment]
@genotrance Good to know, I was aware.

**Comment by dom96** [comment]
yes, and we also have to be able to develop Nimble. Not being able to is worthy of "high priority"
