### ISSUE TITLE
Passing command line arguments to a task

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/nimble#633]
It would be nice if nimble tasks could be parameterized by the user via the command line. For example: `nimble myTask --verbose` and the task could handle the `--verbose` switch.

Not sure if this is already possible, but I couldn't figure out how.

**Comment by xmonader** [comment]
I think it's already possible
```nim

task dmdm, "dmdm":
    echo paramCount()
    echo paramStr(2)
```

```bash
nimble dmdm --abc
2
--abc
```

**Comment by genotrance** [comment]
This makes sense for standard tasks like `build` but for custom tasks, the packager needs to do it themselves like @xmonader says.

**Comment by binhonglee** [comment]
@genotrance @xmonader I think this is a regression. It used to work on 0.17.2 for me but it doesn't anymore on 0.20.2.

Here's the task code and output of it:

```nim
task dmdm, "dmdm":
    echo paramCount()
    for i in countup(0, paramCount(), 1):
        echo paramStr(i)
```

```text
nimble dmdm --abc
  Executing task dmdm in /home/binhong/wings/wings.nimble
7
/home/binhong/.choosenim/toolchains/nim-0.20.2/bin/nim
e
--hints:off
--verbosity:0
-p:/tmp/nimblecache
/home/binhong/wings/wings_21085.nims
/tmp/nimble_21085.out
dmdm
```

As you can see `--abc` is nowhere to be seen. It just ends at `dmdm` which is the name of the task.

**Comment by jxy** [comment]
This is really a regression, as it used to work fine as @xmonader 's comment, but lately `paramStr` gives more entries, and it does this with the extra parameters of the task completely ignored.

**Comment by genotrance** [comment]
https://github.com/nim-lang/nimble/pull/686 is the fix, I just need to add tests.

**Comment by zajrik** [comment]
Any insight as to when this will land in a release?

**Comment by genotrance** [comment]
Just use `koch --latest nimble` to get this.

**Comment by dom96** [comment]
@genotrance this instruction might have problems for many (especially if they installed via choosenim): they won't know what ``koch`` is or where to find it. The "proper" command is ``nimble install nimble@#head``, but it relies on the fact that you have a working Nimble installed.

**Comment by genotrance** [comment]
I'd argue `nimble install nimble@#head` is bad for choosenim which creates shims in `~/.nimble/bin` which change when you pick different versions of Nim. If you use the nimble method, it will create a symlink to a fixed version of nimble in the same directory and choosenim will grumble about the symlink every time.

**Comment by dom96** [comment]
yes, but at least you'll be able to get Nimble installed. :)

**Comment by zajrik** [comment]
@genotrance I installed Nim manually per https://nim-lang.org/install_windows.html on my current system (same way I had installed it on my old system, I believe, prior to the long break I've taken from Nim). I had heard of choosenim at some point while doing some reading on Nim again before I picked it back up but I forgot about it when the time came to actually reinstall Nim. I do not appear to have `koch` in my `%NIMPATH%\bin`. Is this meant to come with Nim when installing manually?

Because I did not install via choosenim, I should be able to safely update Nimble via Nimble itself with `nimble install nimble@#head`, correct?

**Comment by zajrik** [comment]
Thank you. Reordering my path is no problem. I should ask, though, what would be the recommended way to update nimble from a manual nim install? Should I consider an alternative way to install and upgrade nim? I'm not opposed to just dropping in new versions.

**Comment by genotrance** [comment]
I'm an active user of choosenim since I want to make my libraries work across multiple versions of Nim. If that's not your use case, you can just download and install like you are. You could also use something like [scoop](https://scoop.sh/).

**Comment by bluenote10** [comment]
Thanks for the fix!

What I had in mind originally: Instead of accessing raw params we could implement some a function `getTaskParams()` which automatically strips away the Nimble executable, the arguments going to Nimble, and the task argument itself. In other words, an API that contains only what is relevant for the task, and doesn't require to re-implement the extraction logic in every task.

This would allow to make passing argument to tasks consistent, choosing one of the two common conventions:
- All arguments up to `mytask` are Nimble arguments, all arguments after `mytask` are task arguments.
- All arguments up to `--` are Nimble arguments, all arguments after `--` are task arguments (like npm handles it).

With exposing the raw arguments we may end up with implementations of both conventions and it wouldn't be clear for users which convention a task uses.

**Comment by genotrance** [comment]
Seems like a good idea. We can add to nimscriptapi.nim and it will be available to nimble files. Only thing is that there is no documentation for nimble specific procs and it doesn't make sense to add this to nimscript either. I'll let @dom96 share his opinion as well.

It should be easy to decipher task args from the first option since they are appended after the task name already.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/nimscriptwrapper.nim#L44

**Comment by dom96** [comment]
Agree with @bluenote10, I've been wanting a Nimble-specific API for this for a while. I think it makes a lot of sense to do it this way.

Personally I would prefer the first convention.

**Comment by bluenote10** [comment]
> Only thing is that there is no documentation for nimble specific procs and it doesn't make sense to add this to nimscript either.

As an alternative to having a getter proc might be to enable this syntax for task definitions:

```
task hello, "This is a hello task", args:
  echo "Task arguments: ", args
```

> Personally I would prefer the first convention.

Me as well, because it better fits to how `nim c -r` handles arguments, and making `--` mandatory can be tedious.

**Comment by gohryt** [comment]
Is there any progress with this issue after five years? I am learning nim and i really need it
![image](https://github.com/user-attachments/assets/357d3e18-d315-4d52-937f-560a1c6ae90d)
![image](https://github.com/user-attachments/assets/589d8ea0-3d24-4768-bb33-c27af20c351d)
