### ISSUE TITLE
getProxy() doesn't handle proxies properly

### ISSUE THREAD

**Issue by trialism** [nim-lang/nimble#651]
[Forum thread](https://forum.nim-lang.org/t/4790).

[Problematic line](https://github.com/nim-lang/nimble/blob/f17eaef7957da23aab6e375400b37227394a632a/src/nimblepkg/options.nim#L408).

`return newProxy($parsed, auth)`

`$parsed` will always return with something like:

```
(scheme: "http", username: "", password: "", hostname: "10.10.10.10", port: "8080", path: "", query: "", anchor: "", opaque: false)
```

instead of a real URL. `parseUri` [is working with real URLs](https://github.com/nim-lang/Nim/blob/7f3b686b81f3f7ec060b5de9029e3234f24aa372/lib/pure/uri.nim#L164).

[Choosenim is also affected.](https://github.com/dom96/choosenim/blob/121133ba06b0954e058d38743a18fe1ad1f817f2/src/choosenim/utils.nim#L121).

@dom96 lets discuss the solution. I could create a MR with `return newProxy(url, auth)` where url could be prefixed with `http://` if the scheme was empty in the condition before it.

**Comment by trialism** [comment]
We could also overload `newProxy()` to accept an `Uri` too.

**Comment by dom96** [comment]
> $parsed will always return with something like: [...]

How? ``$`` for ``Uri`` is defined in the `uri` module: https://nim-lang.org/docs/uri.html#%24%2CUri

**Comment by trialism** [comment]
Oh, I see! So Nim's `$` strikes again(me thinking it's a virtual method)! Probably importing the whole module needs to be a Nim "good practice" because in other languages it's the opposite.

**Comment by trialism** [comment]
In the forum thread I had `from uri import parseUri`.

**Comment by dom96** [comment]
oh damn. I can see the confusion, and indeed, it's subtle. Not sure what we could really do here to prevent this mistake.

**Comment by trialism** [comment]
The ones preventing this would either impact performance(vtables everywhere) or make it really uncomfortable(disabling the default `$` for types in general - would need to import it). This issue affects pretty much every non-OO language so it might be a good idea to make it the linters' job.

**Comment by Araq** [comment]
@trialism We have some ideas about how to prevent this without a vtable overhead but this is not the place to discuss it, see https://github.com/nim-lang/RFCs/issues/139
