### ISSUE TITLE
Git tagging nimble package repo with "0.5.0" instead of "v0.5.0" caused a random package version to get fetched

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nimble#666]
The [parsetoml][1] .nimble file has this version string: [`version = "0.5.0"`][4].

When that version got updated in the .nimble file, git tag **0.5.0** (without "v" prefix) got applied to it. That caused `nimble install` from within the repo dir on Travis to fetch a 0.3.2 version of parsetoml:

>  Verifying dependencies for parsetoml@0.3.2

[travis log][2]

The interesting piece is that a version 0.3.2 has never been git-tagged, but that "version" string in .nimble was last set to "0.3.2" back in May 2018 (https://github.com/NimParsers/parsetoml/commit/17c6c5103b5e0c56946908fa57e9ca2e2c9712f0).

---

That caused other issue like failing to find a nimble task that was actually being defined in the `parsetoml.nimble` file.

See the messages on IRC describing this confusion: https://irclogs.nim-lang.org/10-06-2019.html#17:20:09

---

By fluke, I thought of removing the **0.5.0** and retagging it with **v0.5.0**, and it worked!

Now `nimble install` fetched the correct version ([see travis log][3]) and there's no false failure related to not finding the `run_toml_tests` task.

---

Can this behavior be explained?

## `nimble` version
```
nimble v0.10.2 compiled at 2019-06-10 13:40:01
git hash: d15c8530cb7480ce39ffa85a2dd9819d2d4fc645
```

## `nim` version
```
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 485b008433ba8e96c572f30925eebdea45bb6d92
active boot switches: -d:release
```

[1]: https://github.com/NimParsers/parsetoml
[2]: https://travis-ci.org/NimParsers/parsetoml/builds/543805185#L1351
[3]: https://travis-ci.org/NimParsers/parsetoml/builds/543840143#L1360
[4]: https://github.com/NimParsers/parsetoml/blob/329cc618fe27a6c89708d1fa17ddc72f8da97e08/parsetoml.nimble#L3

**Comment by dom96** [comment]
Travis caching issue? If you're installing a local package then git tags are not consulted.

I also never seen `--accept` in this context: ``nimble install --depsOnly --accept``. Does it actually do something?

**Comment by kaushalmodi** [comment]
> If you're installing a local package then git tags are not consulted.

You are correct. Yesterday I had tried running `nimble install parsetoml` locally and it fetched a "0.3.2" version:

![image](https://user-images.githubusercontent.com/3578197/59271135-30ad8b80-8c21-11e9-88eb-aa3b53caa100.png)


When the latest git tag was "0.5.0", `nimble install` installed "0.3.2" version. Once I changed the tag to "v0.5.0", `nimble install parsetoml` started fetching the expected version.

> Does it actually do something?

Yes, without `--accept`, I remember `nimble` stalling on Travis because it waits for some user prompt about should it download the whole package database.

**Comment by dom96** [comment]
> You are correct. Yesterday I had tried running ``nimble install parsetoml`` locally and it fetched a "0.3.2" version:

That's not installing a local package. It's possible Nimble ignored `0.5.0` because of the lack of 'v' prefix.

> Yes, without --accept, I remember nimble stalling on Trav...

Oh, I totally forgot ``--accept`` is an alias for ``-y``: https://github.com/nim-lang/nimble/blob/0e873c2702d6fde8bcc86a7942497d2ad3989db5/src/nimblepkg/options.nim#L105

**Comment by genotrance** [comment]
I don't think this has anything to do with Nim or Nimble. Note how the repo is being checked out by Travis using git in the first place. `nimble install` in the local directory is only going to act on what's been checked out. Like @dom96 said earlier, there's no git tags to check here, it is a local dir install.

In [failing](https://travis-ci.org/NimParsers/parsetoml/builds/543805185#L161) build:
```
$ git clone --depth=50 --branch=0.5.0 https://github.com/NimParsers/parsetoml.git NimParsers/parsetoml
Cloning into 'NimParsers/parsetoml'...
$ cd NimParsers/parsetoml
$ git checkout -qf 0.5.0
```

In [passing](https://travis-ci.org/NimParsers/parsetoml/builds/543840143#L161) build:
```
$ git clone --depth=50 --branch=v0.5.0 https://github.com/NimParsers/parsetoml.git NimParsers/parsetoml
Cloning into 'NimParsers/parsetoml'...
Note: checking out '329cc618fe27a6c89708d1fa17ddc72f8da97e08'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
$ cd NimParsers/parsetoml
$ git checkout -qf v0.5.0
```

It is unclear what git really checked out here and the fact that we don't know what `0.5.0` really pointed to before it was deleted, it is hard to tell anything.

**Comment by genotrance** [comment]
Can we close this?

**Comment by kaushalmodi** [comment]
It's a confusing bug though. Somewhere it needs to be documented that the git tags cannot begin with a number.

**Comment by genotrance** [comment]
We can add a line somewhere in the Nimble docs but I am not sure who will notice :D

**Comment by kaushalmodi** [comment]
I agree. There's not much value leaving this issue open. Closing it.

**Comment by dom96** [comment]
This seems to still be a bug. See https://irclogs.nim-lang.org/22-10-2019.html#21:18:09

**Comment by dom96** [comment]
So @disruptek's assertion:

> if you've been using the v and you stop using it, your tags sort out of order.

Doesn't seem to be correct, or maybe I've tested it incorrectly. In any case, I'll create a PR to add some more tests for this, if someone can break the sorting logic please comment.

**Comment by disruptek** [comment]
I'm sorry, I just saw this; I was referring to the git behavior:

```
$ git tag --list
1.4.50
1.4.6
1.4.9
goats
v1.4.35
v1.4.37
```
or
```
$ git tag --sort=version:refname
1.4.48
1.4.49
1.4.50
goats
v1.4.35
v1.4.37
v1.4.38
```

**Comment by dom96** [comment]
Right. I'm not sure why that is a problem for you.
