### ISSUE TITLE
Nimbe pulls incorrect submodule version from a non master branch

### ISSUE THREAD

**Issue by lmariscal** [nim-lang/nimble#675]
Due to some version changes in the library I'm binding it is required to have different branches with different submodule versions from the `master` branch.

`1.0` branch: https://github.com/nimgl/nimgl/tree/1.0/src/nimgl/private
`master` branch: https://github.com/nimgl/nimgl/tree/master/src/nimgl/private

They both target different cimgui commit hashes, the issue comes when a user wants to install the branch `1.0` with `nimble install nimgl@#1.0`, it correctly downloads all files that are in the repo but fails at correctly updating the submodule, instead it just keeps the version that is referenced in the `master` branch which causes a SEGFAULT when trying to reference incorrect data: https://github.com/nimgl/nimgl/issues/25.
My naive idea of the error would be that doing the same with just the git cli actually requires an extra command: `git pull --recurse-submodules` after checkout the desired branch, which nimble lacks. 

This issue is not happening in a "mirror" repo that is kept as an independent package: https://github.com/nimgl/imgui it correctly downloads the desired submodule version.

**Comment by dom96** [comment]
Does using ``git pull --recurse-submodules`` have any downsides?

**Comment by lmariscal** [comment]
Well, `--recurse-submodules` was introduced in version `2.13` which was released in 2017-05-10. It can be a bad idea to depend on it because of compatibility with older versions. [More info](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules)

Nimble has a `doClone` [method](https://github.com/nim-lang/nimble/blob/d606867da636e3377cb5c8d55e9653388e1121cb/src/nimblepkg/download.nim#L44) which uses the `--branch`(-b) argument that would resolve this issue. But in the [proc](https://github.com/nim-lang/nimble/blob/d606867da636e3377cb5c8d55e9653388e1121cb/src/nimblepkg/download.nim#L150) `doDownload` the argument `branch` is never used with the correct proc, instead it is [calling](https://github.com/nim-lang/nimble/blob/d606867da636e3377cb5c8d55e9653388e1121cb/src/nimblepkg/download.nim#L182) the `doCheckout` [proc](https://github.com/nim-lang/nimble/blob/d606867da636e3377cb5c8d55e9653388e1121cb/src/nimblepkg/download.nim#L19) which does generate this issue as it does not checks out the correct submodule versions. I think the solution would be to properly call `doClone` with the correct branch argument since it correctly calls the git clone command with the branch argument which correctly checks out the correct version.

**Comment by dom96** [comment]
IIRC the ``--branch`` flag had issues of its own, we switched away from it. You might be able to find that in the blame/history
