### ISSUE TITLE
Nimble test suite should change PATH so that Nimble exe is in there for certain tests

### ISSUE THREAD

**Issue by bobeff** [nim-lang/nimble#676]
I started to work on this [issue](https://github.com/nim-lang/nimble/issues/127) and as a first step, I run the tests to see whether they pass, but there was a problem. One of the tests is failing `[FAILED] issues #280 and #524`  and also after the last test, the tester exits with an error:
```
[Suite] Module tests
  [OK] version
  [OK] reversedeps
  [OK] packageparser
  [OK] packageinfo
  [OK] cli
Error: execution of an external program failed: '/home/bobeff/projects/Nim/dist/nimble/tests/tester '
stack trace: (most recent call last)
/tmp/nimblecache/nimscriptapi.nim(164, 16)
/home/bobeff/projects/Nim/dist/nimble/nimble_83013.nims(30, 10) testTask
/home/bobeff/projects/Nim/lib/system/nimscript.nim(246, 7) exec
/home/bobeff/projects/Nim/lib/system/nimscript.nim(246, 7) Error: unhandled exception: FAILED: nim c -r tester
     Error: Exception raised during nimble script execution
```
This happens with the latest commit in master, as well with the latest tagged commit, both on Windows and Linux. I want to know whether this is expected behavior with the current Nimble? I looked that there is no other tests after the last one reported. Maybe the error at the end is due to the single failing test above, but it is misleading , because I wasn't sure whether there are more tests after it. I checked that the last passed test is really the last defined test, but in the beginning my impression was, that the testing procedure is halted somewhere in the middle. Maybe this should be fixed to report the number of passed and failed tests and to always exit with success?

**Additional information:**
```
$ nim --version
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-12
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 2895ad70c8e65cd6c220cf06c5e04ce7adfd29bd
active boot switches: -d:release
```
```
$ nimble --version
nimble v0.10.2 compiled at 2019-07-12 15:13:17
git hash: d15c8530cb7480ce39ffa85a2dd9819d2d4fc645
```

The result is the same on Windows, and with the latest Nimble commit in the `master` branch: ` 5e72840336c03ef66557f96623fedddece53083d `

**Comment by dom96** [comment]
> Maybe this should be fixed to report the number of passed and failed tests and to always exit with success?

The message can be improved, but we should never exit with a success when the tests fail.

----

As far as this test failure goes, perhaps it's caused by a change in Nim? The CI succeeded on the following branches: https://github.com/nim-lang/nimble/blob/master/.travis.yml#L8-L10. Can you verify whether these work?

**Comment by bobeff** [comment]
After more detailed investigation and looking at what the test actually do, I found that the problem is in my machine. I didn't add the path to the Nimble `bin` directory to the system path. Sorry for the unnecessary alarm.

**Comment by dom96** [comment]
> I didn't add the path to the Nimble bin directory to the system path.

huh, that shouldn't be necessary. Does the test expect this?

**Comment by genotrance** [comment]
This test expects nimble in the path:

https://github.com/nimble-test/issue280and524/blob/master/issue280and524.nimble

**Comment by dom96** [comment]
I see. The test suite should add Nimble into the PATH for this case.

**Comment by genotrance** [comment]
This isn't trivial. As part of our CI for example, we build and install Nim so nimble is already in the path. Fixing this would mean removing the system-wide nimble from the path but keeping the system-wide Nim in place since nimble needs `nim e`.

**Comment by dom96** [comment]
> As part of our CI for example, we build and install Nim so nimble is already in the path.

We should probably remove the installed Nimble, this sounds like it can cause all sorts of problems. We could have tests testing an old version of Nimble for example. This should just be a simple case of `rm`'ing the installed Nimble, no?

**Comment by genotrance** [comment]
Fixing this with https://github.com/nim-lang/nimble/pull/714. Using an env var `NIMBLE_TEST` to propagate the right nimble binary to use.

Also see https://github.com/nimble-test/issue280and524/pull/4.
