### ISSUE TITLE
Clear build warnings

### ISSUE THREAD

**Issue by bobeff** [nim-lang/nimble#680]
I have desire to clear all build warnings form Nimble, but I'm not sure what to do with deprecation warnings. It seems that Nimble is still being tested against an older version of Nim - [0.19.6](https://github.com/nim-lang/nimble/blob/7c2b9f612e6a42609f28f8f51de4ab6949ced4a0/.travis.yml#L8). Half of the warnings are of this type:
```
Warning: Deprecated since v0.20, use 'initHashSet'; initSet is deprecated [Deprecated]
```
and fixing them will break backward compatibility with an older Nim. Is such compatibility still required?

The other half of the warnings are from the type:
```
Warning: imported and not used: 'sets' [UnusedImport]
```

and they are caused by the new feature for detecting unused imports. I suspect that it will be completely safe to remove them.

There are also some hints for dead code like:
```
Hint: 'getSpecificDir' is declared but not used [XDeclaredButNotUsed]
```

Can I remove such unused functions or they are left intentionally?

**Comment by bobeff** [comment]
If the compatibility with an older Nim before version 0.20.x is still required, I can fix it this way:
```nim
when NimMajor == 0 and NimMinor < 20:
  import sets

  template initHashSet*[A](initialSize = 64): HashSet[A] =
    initSet[A](initialSize)

  template toHashSet*[A](keys: openArray[A]): HashSet[A] =
    toSet(keys)
```

**Comment by cheatfate** [comment]
@bobeff it is better to use `compiles` e.g:
```nim
when compiles(initHashSet):
  # After 0.20.0 Nim's stdlib version
  result.handles = initHashSet[AsyncFD]()
else:
  # Pre 0.20.0 Nim's stdlib version
  result.handles = initSet[AsyncFD]()

when compiles(initHeapQueue):
  # After 0.20.0 Nim's stdlib version
  result.timers = initHeapQueue[TimerCallback]()
else:
  # Pre 0.20.0 Nim's stdlib version
  result.timers = newHeapQueue[TimerCallback]()
```

**Comment by dom96** [comment]
You don't need ``compiles`` for this, ``declared`` is more direct and should work (https://nim-lang.org/docs/system.html#declared%2Cuntyped).

**Comment by dom96** [comment]
> Can I remove such unused functions or they are left intentionally?

Sure, feel free to remove them. If it turns out to be important we'll flag it in PR reviews.

**Comment by bobeff** [comment]
It came to my mind that the clearing of the warnings will not be very useful if they are being introduced again in the future. Is it okay to add some kind of check of the build output in Travis that the build doesn't have warnings?

**Comment by bobeff** [comment]
And one more question. It seems that `nimscriptwrapper.nim` is the new version of the `nimscriptsupport.nim`, and the older file is not used any more. May I delete the old file?

**Comment by genotrance** [comment]
> And one more question. It seems that `nimscriptwrapper.nim` is the new version of the `nimscriptsupport.nim`, and the older file is not used any more. May I delete the old file?

I left it in for the near term. I'll let @dom96 decide if it should be tossed.

**Comment by dom96** [comment]
Sure, delete it if it's not used. We've got it in git history if necessary.
