### ISSUE TITLE
Windows 10: stuck in "Building" step

### ISSUE THREAD

**Issue by mantielero** [nim-lang/nimble#681]
I am trying to install `nimterop` in a coorporate Windows 10 machine. I did:
```
choosenim 0.20.2
```
and everything went fine.

And now:
```
c:\folders>nimble --verbose install nimterop@#head
    Reading official package list
Downloading https://github.com/genotrance/nimterop using git
  Verifying dependencies for nimterop@#head
    Reading official package list
   Checking for regex@>= 0.10.0
      Info: Dependency on regex@>= 0.10.0 already satisfied
  Verifying dependencies for regex@0.11.2
    Reading official package list
   Checking for unicodedb@>= 0.7.0
      Info: Dependency on unicodedb@>= 0.7.0 already satisfied
  Verifying dependencies for unicodedb@0.7.1
    Reading official package list
   Checking for unicodeplus@>= 0.5.0
      Info: Dependency on unicodeplus@>= 0.5.0 already satisfied
  Verifying dependencies for unicodeplus@0.5.0
    Reading official package list
   Checking for unicodedb@>= 0.7
      Info: Dependency on unicodedb@>= 0.7 already satisfied
  Verifying dependencies for unicodedb@0.7.1
    Reading official package list
   Checking for cligen@>= 0.9.17
      Info: Dependency on cligen@>= 0.9.17 already satisfied
  Verifying dependencies for cligen@0.9.31
 Installing nimterop@#head
   Building nimterop/nimterop/toast.exe using c backend
```
It gets stuck there.

**Comment by dom96** [comment]
Sounds like a nimterop problem to me. Do other packages install fine?

**Comment by genotrance** [comment]
Can you check if the C/C++ compiler is hanging or git? You can check in task manager. ProcExp might help better since it provides a process tree.

Regardless, this isn't a nimble issue.

**Comment by mantielero** [comment]
It is the C/C++ compiler.
![tasks](https://user-images.githubusercontent.com/1116064/61928665-7c21bc00-af79-11e9-88d8-2e46e80aecfd.png)

**Comment by genotrance** [comment]
When you kill the cc1 process, it will print a bunch of stuff to the console showing an issue.

Can we move this issue to the nimterop tracker somehow?

**Comment by dom96** [comment]
> Can we move this issue to the nimterop tracker somehow?

This only works for repos in the same org AFAIK

**Comment by mantielero** [comment]
Moved to [nimterop issue 138](https://github.com/nimterop/nimterop/issues/138)
