### ISSUE TITLE
I don't have permissions to transfer test repository to nimble-test

### ISSUE THREAD

**Issue by bobeff** [nim-lang/nimble#687]
I just have joined the [nimble-test](https://github.com/nimble-test) organization, but it seems that I don't have permissions to transfer the ownership of the [bobeff/issue678](https://github.com/bobeff/issue678) repository to it. When I go to the repository settings and I press the *transfer ownership* button, GitHub responds with the following message:
> You don’t have the permission to create repositories on nimble-test

**Comment by dom96** [comment]
Bah. GitHub permissions are a mess. Try again please, I've enabled a setting which should enable you to do this.

**Comment by bobeff** [comment]
Thanks, everything seems alright now.
