### ISSUE TITLE
Nimble cannot disable networking

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/nimble#699]
It's common practice to disable network interactions in package installers when used in buildbots. This is used to ensure that a build can run with the local contents and does not depend on external services, also for security and to ensure reproducibility.
Nimble has no flag to disable networking.
A hacky workaround such setting HTTP/S proxies to localhost (see #637 ) does not work because Nimble does not handle the Git-over-ssh use-case.

**Comment by dom96** [comment]
This is a feature, not a bug.

I'm happy to accept a switch that disables the networking and fails with an error as soon as an attempt to access the network is made.

**Comment by FedericoCeratto** [comment]
Thanks!
