### ISSUE TITLE
Compile Time Echo

### ISSUE THREAD

**Issue by SrMordred** [nim-lang/nimble#716]
How to show static outputs during build/run with nimble?

```
static:
  echo "Compiling 1. set of macros..."

```
(not shown on console)

**Comment by 3n-k1** [comment]
From the readme:

Another great feature is the ability to define custom Nimble package-specific commands. These are defined in the .nimble files of course.

```nim
task hello, "This is a hello task":
  echo("Hello World!")
```

You can then execute nimble hello, which will result in the following output:

```
Executing task hello in /Users/user/projects/pkg/pkg.nimble
Hello World!
```

**Comment by SrMordred** [comment]
@3n-k1 
I'm referring to compile-time code in source files.

**Comment by 3n-k1** [comment]
I see, my apologies

**Comment by 3n-k1** [comment]
Alright, I found it. [This line](https://github.com/nim-lang/nimble/blob/0ed8e6403c8a826e776f36484e2e6ae0e9df9c4f/src/nimble.nim#L256) Calls `doCmd` without `output=true`. Passing that second argument prints output.

I'll send a PR in a few minutes.

**Comment by dom96** [comment]
This is by-design. The ``run`` and ``build`` commands are meant to swallow this output, use `--verbose`` to get it or alternatively use `nimble c -r your_file.nim` to compile and run your program.
