### ISSUE TITLE
Windows proxy problem while installing packages.

### ISSUE THREAD

**Issue by rahul-gj** [nim-lang/nimble#717]
I am completely novice in nim and nimble or system programming. I come from python background where just pip install module works just fine without any issue.

now I have this specific issue.

I do the following and the output is:

```
>nimble install nake
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Refresh failed
        ... Could not download: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I have read this: https://github.com/nim-lang/nimble/issues/86; 
and could not find what exactly needs to be done to run nimble on windows behind proxy.

some of the suggestion from above:

1. download the packages.json file manually:

I tried downloading the file and put in the following locations without any luck.
```
nim_installation_dir\bin\packages.json
C:\Users\username\.nimble\packages.json
C:\Users\username\.nimble\bin\packages.json
```

2. NIM_LIB_PREFIX.
Where on earth I use this thing and how? I googled it but it doesn't give useful results.

there should be something like nimble set http_proxy="http://proxy.com:0000"

**Comment by dom96** [comment]
You should be able to just set `http_proxy` and/or ``https_proxy``, I think you're seeing a bug in Nim's httpclient's proxy implementation.

Anyway, you can just rename C:\Users\username\.nimble\packages.json to C:\Users\username\.nimble\packages_official.json and it should work.

**Comment by rahul-gj** [comment]
Thanks. I added packages_official.json and that step just worked.
After that nimbe uses git for downloading libraries and setting git proxy just worked fine.
