### ISSUE TITLE
Avoid creating temporary files in project root dir

### ISSUE THREAD

**Issue by filcuc** [nim-lang/nimble#720]
Executing `nimble tasks` causes the creation of temporary .nims files.
This seems to be caused by the use of `nim -e` and the need for preserving the import paths.
This however causes trouble to IDE plugins watching the project directory through a file system watcher. In general temporary files should be created in a temporary directory or at least a configurable path.

**Comment by genotrance** [comment]
WIP in #768 

cc @alaviss
