### ISSUE TITLE
'nimble install' doesn't install latest version

### ISSUE THREAD

**Issue by matkuki** [nim-lang/nimble#721]
Using the `install` command for the `opengl` library with:
```
nimble install opengl
```
always installs version `1.2.2` even though the library has been upgraded to `1.2.3` two months ago!

What controls which version of a library gets downloaded?

I'm on Windows with Nimble v0.11.0 compiled at 2019-09-26.

**Comment by genotrance** [comment]
There's only 1.2.3 in the nimble file but no tag for it. So nimble will install the latest tag which is 1.2.2.

**Comment by matkuki** [comment]
Right, thanks.
