### ISSUE TITLE
`nimble run` doesn't pass all options/arguments to the binary

### ISSUE THREAD

**Issue by sschwarzer** [nim-lang/nimble#725]
I created a `.nimble` file for my binary package. `nimble build` works as expected.

`nimble run mybinary` works in that it prints the help text of my binary and exits with exit code 1.

However, when I run `nimble run mybinary --help`, this doesn't pass the `--help` option to my program as I expected. Instead `nimble` seems to understand the `--help` as its own option and prints the Nimble help without running my program.

I suppose Nimble shouldn't assume that anything following the name of the binary is intended for Nimble. Instead, everything after the name of the binary should be passed as options/arguments to the binary.

**Comment by dom96** [comment]
Nimble version?

Also, do other flags work?

**Comment by sschwarzer** [comment]
The Nimble version is 0.11.0. The Nim version is 1.0.0.

It seems it only happens with `--help`. I just tried `--version` and `--verbose`, which are passed to my program.

**Comment by yuchunzhou** [comment]
hi all,  i have fixed this problem in #731 @dom96  @sschwarzer
