### ISSUE TITLE
use ~/.config/nimble instead of .nimble

### ISSUE THREAD

**Issue by rapha8l** [nim-lang/nimble#730]
Thanks for your work

As many people complain about $HOME being a mess of dotfiles, I'd suggest using $XDG_HOME_CONFIG
Have a nice day

**Comment by SolitudeSF** [comment]
that almost as bad. `$XDG_DATA_HOME` is a proper place.

**Comment by dom96** [comment]
Nimble's default is a common default for package managers. If you wish to change it, you can modify Nimble's config.

**Comment by rapha8l** [comment]
Ok thanks
