### ISSUE TITLE
How to install older versions of packages?

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/nimble#734]
It may be documented somewhere, and it may be able to guess. But it should be stated at a more prominent place.

From  https://github.com/nim-lang/nimble we have for latest commit:

```
$ nimble install nimgame@#head
$ nimble install nimgame@"> 0.5"
```

gintro is tagged v0.6.0 for latest, version before was v0.5.5. How to get v0.5.5? My guesses

```
nimble install gintro@#=v0.5.5
nimble install gintro@#=0.5.5
nimble install gintro@#v0.5.5
nimble install gintro@#0.5.5
```

I assume at least one of these should work. Or no, maybe we have to remove the #

**Comment by SolitudeSF** [comment]
`nimble install gintro@0.5.5`

**Comment by StefanSalewski** [comment]
Really without the v prefix?

Found Miram reply on IRC:

https://irclogs.nim-lang.org/16-07-2019.html#16:14:37

salewski: `nimble install pkgname@tag`

So when my tag is v0.5.5 then I would assume

`nimble install gintro@v0.5.5`

**Comment by SolitudeSF** [comment]
you can verify it just by running the command?

**Comment by SolitudeSF** [comment]
for a tag you would use `gintro@#v0.5.5`. And nimble would identify it as a tag, not a 0.5.5 version. i think.

**Comment by StefanSalewski** [comment]
Yes, but it may destroy my install of latest v0.6.0 which I did yesterday.

I would try if I would need it myself -- but only my customers need it, and maybe other people may need it too when they ever want to install older version. So I suggest adding documentation -- maybe for githash also. Latest install is documented well, but latest is for experts, they know it always before.

**Comment by SolitudeSF** [comment]
why would it destroy it?

**Comment by StefanSalewski** [comment]
I don't know, I never install more of one release of a package. I generally do 'uninstall package' followed by 'install package'. I do not want to pollute my computer with cruft, so I never use choosenim, only plain nim install from git. When I have 0.6 and nimble install 0.5.5 later -- how can I be sure which one is used? Well maybe I can learn that, but for gintro development I like to be sure that really latest tagged version is used by me, so I can verify that it works. Have to do some work now, bye.

**Comment by SolitudeSF** [comment]
latest one will be used, unless you limit it explicitly in .nimble file.

**Comment by dom96** [comment]
> nope. you can never be sure what nimble assumes.

Why not? Your assumption is correct, and even the documentation explains this ([link](https://github.com/nim-lang/nimble#nimble-install)):

> A branch, tag, or commit hash may also be specified in the place of head.
