### ISSUE TITLE
Installing selected binaries

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/nimble#737]
`nimble install` should allow building/installing only specified binaries.

**Comment by genotrance** [comment]
Can you please elaborate on this? Today, you define binaries with `bin` in the `.nimble` file. All of them get installed.

What are you asking for here?

**Comment by SolitudeSF** [comment]
i want to choose what binaries get installed. sometimes i dont need every single one of them.

**Comment by dom96** [comment]
Just remove them from the `bin` field then?

**Comment by SolitudeSF** [comment]
its not my package?

**Comment by Calinou** [comment]
@SolitudeSF Can you link to the package(s) in question that install too many binaries to your liking?

**Comment by dom96** [comment]
> i dont understand what is there to understand.

Oh, as an end-user. That's what was left to understand... :)

Do package managers generally allow picking and choosing which binaries are installed?

**Comment by SolitudeSF** [comment]
i guess not
