### ISSUE TITLE
StaticRead does force a recompile if static file changes.

### ISSUE THREAD

**Issue by treeform** [nim-lang/nimble#739]
Have a nim file:
```nim
const msg = staticRead("test.txt")
echo msg
```

Put some thing in `test.txt`, compile it. Change some thing in test.txt and compile again. It will not recompile and display old message. Only `nim c -f` will force a recompile.

It really annoying when working with shaders always having to wait with `nim c -f` while just a single nim file needs a recompile.

**Comment by Araq** [comment]
Please report this as a Nim issue.
