### ISSUE TITLE
Nimble build errors aren't as friendly as nim

### ISSUE THREAD

**Issue by MatthewScholefield** [nim-lang/nimble#741]
From what I understand, the standard practice is to build nim projects with the `nimble build` command. However, this strips colors from the compiler output and adds some extra indentation. Given that a large percent of the time `nimble build` errors will contain output from `nim`, I think it'd make sense to have it display errors nicely. Here's a comparison of with `nimble build` vs with `nim c`:

Nimble:
![image](https://user-images.githubusercontent.com/5875019/68856713-d53b6a00-06a6-11ea-9d10-c16143bc9cc8.png)

Nim:
![image](https://user-images.githubusercontent.com/5875019/68856730-db314b00-06a6-11ea-8774-8251dfa28b72.png)

Let me know if this makes sense.

**Comment by SolitudeSF** [comment]
`nimble build` should pass compiler output transparently and do it by default, without `debug` flag.

**Comment by MatthewScholefield** [comment]
The problem most likely lies in nim detecting it's no longer outputting to a tty. This could probably be solved by passing `--colors on` to nim (provided `nimble`, itself is run in a tty)

**Comment by dom96** [comment]
> This could probably be solved by passing --colors on to nim (provided nimble, itself is run in a tty)

Sounds good.
