### ISSUE TITLE
Cant install certain hybrid packages

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/nimble#747]
Any hybrid package with structure of
```
srcDir/pkgname/...
srcDir/pkgname.nim
```
will fail to install with `Error: unhandled exception: Is a directory [OSError]` since it tries to put extensionless binary in the same directory as library component of the package.

**Comment by genotrance** [comment]
Both choosenim and nimble use a pkg extension to avoid this: `src/choosenimpkg` and `src/nimblepkg`.

What's could be considered as a fix for this?

**Comment by SolitudeSF** [comment]
placing binaries in separate folder? placing them into bin directly instead of symlinks? idk

**Comment by genotrance** [comment]
Dup of #308, closing.
