### ISSUE TITLE
permission denied to ~/.nimble/pkgs is fatal

### ISSUE THREAD

**Issue by disruptek** [nim-lang/nimble#748]
I cannot use commands such as `test`, `dump`, `check`, `doc`, etc. when Nimble doesn't have permission to `~/.nimble/pkgs`.

**Comment by disruptek** [comment]
Ditto `$TMPDIR`.

**Comment by genotrance** [comment]
I just set `~/.nimble/pkgs` to be owned by root and was able to run all the above commands as a regular user.

$TMPDIR is a different story though since nimblecache lives there.

**Comment by disruptek** [comment]
How is that useful?

**Comment by genotrance** [comment]
To test whether `~/.nimble/pkgs` being inaccessible makes any difference to Nimble, and it did not. Not for the commands you mentioned at least. An error snippet would help to figure out what's going on.

**Comment by disruptek** [comment]
Here's a reproduction that demonstrates my problem:

```bash
$ chmod 0 ~/.nimble
$ nimble dump
oserr.nim(94)            raiseOSError
Error: unhandled exception: Permission denied
Additional info: "/home/adavidoff/.nimble/pkgs" [OSError]
$ nimble test
oserr.nim(94)            raiseOSError
Error: unhandled exception: Permission denied
Additional info: "/home/adavidoff/.nimble/pkgs" [OSError]
```

When I cannot control the behavior of software I do not trust, I do not use that software.

**Comment by genotrance** [comment]
PR #768 will fix the issue around the `pkgs` directory. nimble needs to get package info for dependencies and currently copies a nims file in each dep to get pkg info. The PR will no longer need files to be copied around.

However, we still rely on $TMPDIR for nimblecache so that has no real fix.

**Comment by Araq** [comment]
> When I cannot control the behavior of software I do not trust, I do not use that software.

Sure but forbidding Nimble access to ``~/.nimble/pkgs`` is deliberately breaking Nimble. "Won'f fix"?

**Comment by disruptek** [comment]
Either Nimble is intended to require read access to ~/.nimble or it isn't.

Since you asked, I think `nimble dump` should work regardless of whether Nimble can read/write my ~/.nimble.  Ditto other operations on the local project, such as `test`, `check`, and so on.

I am fine with closing this ticket if this is the intended behavior; I just felt that the error message suggested otherwise.
