### ISSUE TITLE
Hide hints during tests running

### ISSUE THREAD

**Issue by lamartire** [nim-lang/nimble#749]
Hello! Is there any way to hide hints and other messages which not relates to test suites and cases?

Running just with `nimble test`, without `verbose` flag.

![image](https://user-images.githubusercontent.com/13414205/70916268-70b85580-202c-11ea-8b6b-a46b4721e300.png)

**Comment by dom96** [comment]
No way to ask Nimble for this right now, but you might be able to do a hack: create a nim.cfg file with `--verbosity:0` to make `nim` output nothing (or at least less messages).

**Comment by lamartire** [comment]
Oh, okay. It nice, what we have at least one way to solve that :)
Thank you!
May be you need help with that? Where I can find any contribution notes about nimble cli?

**Comment by dom96** [comment]
Sure, contributions always welcome. Here is the code for the `test` command: https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L1041

Note that this command can be overwritten with ``task test: ...`` in a .nimble file.

**Comment by genotrance** [comment]
Is this the same as #757?

**Comment by lamartire** [comment]
@genotrance may be partially

**Comment by maxgrenderjones** [comment]
The issue is `nim doc` and `nim rst2html` seem to fundamentally ignore the `--hints:off` switch. e.g.:

```
> nim rst2html --hints:off README.rst
Hint: used config file '/Users/.../.choosenim/toolchains/nim-1.2.0/config/nim.cfg' [Conf]
Hint: 320 LOC; 0.092 sec; 4.629MiB peakmem; Debug build; proj: /Users/.../.cache/nim/README_d/README/README_snippet_101.nim; out: /Users/.../.cache/nim/README_d/README/README_snippet_101 [SuccessX]
Hint: /Users/.../.cache/nim/README_d/README/README_snippet_101
... snip snip...
```

Similarly:
```
> nim doc --hints:off src/therapist.nim
Hint: used config file '/Users/.../.choosenim/toolchains/nim-1.2.0/config/nim.cfg' [Conf]
Hint: 320 LOC; 0.085 sec; 4.629MiB peakmem; Debug build; proj: /Users/.../.cache/nim/therapist_d/therapist/therapist_snippet_101.nim; out: /Users/.../.cache/nim/therapist_d/therapist/therapist_snippet_101 [SuccessX]
Hint: /Users/.../.cache/nim/therapist_d/therapist/therapist_snippet_101  [Exec]
... snip snip...
```

**Comment by genotrance** [comment]
This is the default going forward - any Nim command called by Nimble will run with `--hints:off` which is pretty much silent on devel. However, warnings and deprecations will show up guiding the user to clean up as required.

Running with `--verbose` will show the regular Nim output. See #828.
