### ISSUE TITLE
Run only specified test

### ISSUE THREAD

**Issue by lamartire** [nim-lang/nimble#750]
Hello! Is there any functionality to run specified test?
For example:

```
nimble test tests/test_foo.nim
```

In huge projects it is not very convenient to run all tests on each change.

**Comment by SolitudeSF** [comment]
this is the same as doing `nimble c -r tests/test_foo.nim`

**Comment by lamartire** [comment]
Hm, looks like something, which not relates to tests.
May be make some alias for test command?

**Comment by SolitudeSF** [comment]
thats what tests are, just compiling and running a file, why add more magic? the point of `test` was just to do it in batch.

**Comment by lamartire** [comment]
Ok, agree with you.
