### ISSUE TITLE
Watch mode in tests

### ISSUE THREAD

**Issue by lamartire** [nim-lang/nimble#751]
Hello! I guess `watch` feature is not present in current nimble implementation.
But I think it would be really great feature.

For example:

```
nimble test --watch
```

Or running specified test:

```
nimble test --watch tests/test_foo.nim
```

It would be really awesome and useful during debugging or TDD.

**Comment by genotrance** [comment]
`nimble test` already prints a bunch of output. What extra output do you expect with `--watch`?

**Comment by lamartire** [comment]
I didn't mean anything about output, I told about restart tests on each dependent file's change

**Comment by genotrance** [comment]
Okay, makes sense. Really doesn't feel like something nimble should do but I'll let @dom96 decide that.

Would need nimble to monitor all src and test files. And might be too much to be smart enough to run specific tests depending on what exactly changes.

**Comment by dom96** [comment]
Yeah, no, create another program to do this if you really want it. This is outside Nimble's scope.

**Comment by lamartire** [comment]
Thanks, understood :)
