### ISSUE TITLE
Running tests by mask

### ISSUE THREAD

**Issue by lamartire** [nim-lang/nimble#752]
What do you think if we add ability to run tests by custom mask?

For example:
```
nimble test *.test.nim
```

I think it can add some flexibility to run any tests suites placed everywhere user want.

**Comment by Araq** [comment]
Just mark some tests via ``when defined(stressTest)`` and then don't pass ``-d:stressTest`` to the Nimble test command. The idea is to use a programmable environment so that we don't have to implement millions of little features and Nimble can remain simple.

**Comment by lamartire** [comment]
Understood, thank you :)
