### ISSUE TITLE
Support for virtual environments

### ISSUE THREAD

**Issue by JordyScript** [nim-lang/nimble#754]
Many package managers and programming languages support the use of virtual environments to separate different versions of the same library used in different projects. Wouldn't Nim/Nimble need a way to create virtual environments as well? 

I'm new to Nim, and I've tried to look through the documentation of both Nim and Nimble, and I've searched the issues for Nimble on Github, but i cannot find any statement confirming that you either already support virtual environments or any explanations for why they might not be needed in Nim (maybe you solved the problem in a different way).

Maybe this issue can serve to kick off a discussion about Virtual Environments if it's not already implemented or otherwise unnecessary.

**Comment by disruptek** [comment]
So-called "virtual environments" are already supported in Nimble via use of the NIMBLE_DIR environmental variable (or the --nimbleDir command-line option).  Nimph supports arbitrary mixed-source environments natively.

**Comment by dom96** [comment]
As far as I know, the virtual environments in Python exist because two different versions of the same Python package cannot be installed in the same environment. Nimble does not have this limitation, each package is stored in `~/.nimble/pkgs/` with the version appended to the directory name:

```
$ ls ~/.nimble/pkgs
AntTweakBar-1.0.2                                    nimble-0.8.10
BN-1.0.0                                             nimble-0.8.11
NimBorg-0.0.2                                        nimble-0.8.2
PPM-0.1.0                                            nimble-0.8.3
PackageA-#head                                       nimble-0.8.4
PackageA-0.2.0                                       nimble-0.8.5
PackageA-0.6.0                                       nimble-0.8.6
PackageB-0.1.0                                       nimble-0.8.7
PackageBin2-0.1.0                                    nimble-0.8.8
RingBuffer-0.1.2                                     nimble-0.9.0
about-0.1.1                                          nimble-0.9.1
```

Maybe there is another problem that virtual environments solve that I'm not aware of, if so do let me know and feel free to reopen this issue so we can discuss further.
