### ISSUE TITLE
Very poor error messages when evaluating .nimble files

### ISSUE THREAD

**Issue by dom96** [nim-lang/nimble#756]
As I just discovered: https://irclogs.nim-lang.org/23-12-2019.html#19:33:44

I've got a .nimble file which imports a module, I modified that module to have a `staticExec` call. This caused my `nimble clientsdl` task to stop working:

```
     Error: Could not read package info file in /Users/dom/projects/stardust/stardust.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     /Users/dom/projects/nim/lib/pure/streams.nim(274, 9) Error: undeclared identifier: 'copyMem'
        ... printPkgInfo() failed.
```

Of course, I imported that module a long time ago inside my .nimble file so I didn't connect the dots and the error message makes no reference to the .nimble file. We really need some breadcrumbs here.

**Comment by genotrance** [comment]
What do you propose to improve this?

**Comment by dom96** [comment]
I don't know. But ideally we should have a trail like: 

```
pkg.nimble(4, 1): import here
myModule.nim(5,1): import here
streams.nim(274, 9) Error: undeclared identifier: 'copyMem'
```

So that I know which import is causing the failure at least.

**Comment by Vindaar** [comment]
Yes, just got *really* confused by a related error too. It failed with 

```nim
        ... Could not read package info file in /home/basti/src/nim/arraymancer/arraymancer.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     /home/basti/src/nim/arraymancer/arraymancer_14906.nims(242, 21) Warning: imported and not used: 'docs' [UnusedImport]
        ... printPkgInfo() failed.
```

when the actual issue was that within `docs` `paramCount` and `paramStr` were not imported when `NimScript` is defined.

So if anyone would be willing to try to improve those messages, I'd appreciate it! :)

**Comment by genotrance** [comment]
This should be better now - the stack trace will refer to the nimble file after #826.

**Comment by genotrance** [comment]
Closing, if this needs to be improved further, please reopen.
