### ISSUE TITLE
Pass compiler options to `nimble test`

### ISSUE THREAD

**Issue by jromero** [nim-lang/nimble#757]
I'm trying to pass options to the compiler when running the `nimble test`. I've tried the following:

via CLI:
```
nimble test --define:TEST_ITERATIONS=100
```

via overriding task:
```
task test, "Test Application.":
    switch("define", "TEST_ITERATIONS=100")
    setCommand "nop"
```

via delegation task:
```
task test2, "Test Application.":
    switch("define", "TEST_ITERATIONS=100")
    setCommand "test"
```

None of them propagated the options to `nim c ...`. The closest was the delegation task but it only passes the option `nim e` which makes sense (kind of).

**Comment by dom96** [comment]
This isn't supported right now AFAIK. What you can do however is put your options in a `nim.cfg` file and place that in your tests dir.
