### ISSUE TITLE
running nimble on Fedora

### ISSUE THREAD

**Issue by mdickison** [nim-lang/nimble#76]
Hi,

I'm trying to install nimble on Fedora 64-bit, on a MacBook. It compiles fine (Hint: operation successful (36532 lines compiled; 8.298 sec total; 95.973MB) [SuccessX]), but when I try to run it I get:

Traceback (most recent call last)
httpclient.nim(279)      httpclient
net.nim(202)             newContext
alloc.nim(784)           dealloc
alloc.nim(730)           dealloc
alloc.nim(612)           rawDealloc
alloc.nim(309)           isSmallChunk
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

I've tried this with nim versions 0.9.6, github-stable and github-devel, with all the same results.
I have no idea what the issue is, or whether I should be reporting this somewhere else... Please let me know and thanks!

Michael

**Comment by dom96** [comment]
I'm going to assume that this is now fixed. Reopen if not.
