### ISSUE TITLE
[feature request] update package to possible newest version while keeping least copy

### ISSUE THREAD

**Issue by retsyo** [nim-lang/nimble#763]
I don't know whether I missed something in document. I am saying, is it possible to update pacakge and its supporting pacakge(s) to possible newest version, and delete unnecessary old version automatically via, for example `nimble update xx`?

I know
1. we can use `nimble uninstall xx@1.2.3` to remove xx version 1.2.3 by hand. But I mean if we do `nimble update xx` then `nimble` removes all old version by itself. Currently, I find there may be multi-version of some pacakges on my windows, so I have to remove them by hand.

2. some old package is used by others, so `nimble update xx` does not remove the old one.

I hope I have stated it clear. Thanks

**Comment by genotrance** [comment]
Nimble runs based on a specific project and its dependencies. Cleaning up the global repo based on that one project is not prudent. Unless nimble knows all other projects it should consider and their dependencies, there's no way to know what to delete unless user explicitly deletes.
