### ISSUE TITLE
Nimble Install Fails

### ISSUE THREAD

**Issue by schmidh** [nim-lang/nimble#765]
I'm having problems with the installation of many packages. Seems to be a problem with the nimble file format.

e.g. `nimble install https://github.com/alehander92/gara`
generates following error message:

```
Downloading https://github.com/alehander92/gara using git
     Error: Could not read package info file in /tmp/nimble_11228/githubcom_alehander92gara/gara.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     [Package]
        ... version: """0.2.0"""
        ... author: """Alexander Ivanov"""
        ... description: """Macro-based pattern matching library."""
        ... license: """MIT"""
        ... srcdir: """src"""
        ... backend: """c"""
        ... [Deps]
        ... requires: "nim >= 0.18.1"
        ... /tmp/nimble_11228/githubcom_alehander92gara/gara_11228.nims(1, 8) Warning: imported and not used: 'system' [UnusedImport]
        ... /tmp/nimble_11228/githubcom_alehander92gara/gara_11228.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
        ... printPkgInfo() failed.

```

I forked the project and changed the nimble file using classic ini file sections and the installation works fine: `nimble install https://github.com/schmidh/gara`

See [schmidh/gara.nimble](https://github.com/schmidh/gara/blob/master/gara.nimble).

(E.g. package `daemonize` works also fine, `nimlsp` not.)

The same is true for new nim projects created with `nimble init`.

```
nimble init nimbleTest -y
cd nimbleTest
nimble dump
     Error: Could not read package info file in /home/schmidh/Temp/nimbleTest/nimbleTest.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     [Package]
        ... version: """0.1.0"""
        ... author: """Hans-J. Schmid"""
        ... description: """A new awesome nimble package"""
        ... license: """MIT"""
        ... srcdir: """src"""
        ... backend: """c"""
        ... [Deps]
        ... requires: "nim >= 1.0.4"
        ... /home/schmidh/Temp/nimbleTest/nimbleTest_11540.nims(1, 8) Warning: imported and not used: 'system' [UnusedImport]
        ... /home/schmidh/Temp/nimbleTest/nimbleTest_11540.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
        ... printPkgInfo() failed.

```

nim has been installed just now with `choosenim`:
```
 % nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release

```

```
 % nimble -v
nimble v0.11.0 compiled at 2019-11-27 09:21:44
git hash: couldn't determine git hash

```

**Comment by genotrance** [comment]
Can you zip the contents of /tmp/nimblecache and post here? Also, you can try deleting that folder and try again and see if it fixes the issue.

**Comment by schmidh** [comment]
Now it works! I was just booting up my box, tried to install `gara` and it worked.
I am running Ubuntu and had their installation of nim. But (as usual) Ubuntu's version is pretty obsolete so I changed to `choosenim` which is the best option anyway. Maybe there were some leftovers. I don't know. Ubuntu's nim package does not install nimble and there was no `.nimble` directory. Maybe some caching issues. (The `tmp` directory is deleted on every boot. This might have helped.). I think it's more of an Ubuntu issue than anything else.

Taking the chance talking to you, if it's worthwhile could you update your really helpful Zeal/Dash documentation of `nim`?

Thanks a lot for your support! Awesome project, awesome nim community!

**Comment by genotrance** [comment]
Yes I need to get around to update Dash docs.

Meanwhile, on this issue, I see why Nimble does not regenerate the cache files - it only does so if the `.nimble` file is newer than the cache files. If you simply switch Nim or Nimble versions, it does not regenerate. So if you go between a broken Nimble version from past and a newer version, it does not regenerate. As a result, simply upgrading to a newer Nimble does not fix a broken cache.

I can add code to check if the Nim or Nimble version changed and regenerate but am wondering if this is warranted given we will have 1.0.6 soon and older broken versions of Nimble will not be out for very long. The workaround is also easy enough - delete `/tmp/nimblecache`. Alternatively, if newer Nimble versions add any more functionality that could modify the cached data, they won't be regenerated so I'm thinking a fix is worth considering. @dom96 - please let me know your thoughts.

https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/nimscriptwrapper.nim#L107
