### ISSUE TITLE
Nimble from Scoop: Could not load zlib1.dll (solved)

### ISSUE THREAD

**Issue by vegapit** [nim-lang/nimble#772]
**Nim v1.0.6** as installed by **Scoop** on **Windows10** generates a runtime error `could not load zlib1.dll` when using certain imports.

In my case, the solution involved 2 steps:
1. Adding the _~/scoop/apps/nim/current/bin_ folder to the user `Path`
2. Replacing the _zlib1.dll_ included in the _~/scoop/apps/nim/1.0.6/bin_ folder. I luckily found a version that worked in the **Scoop** installed version of **Git**: _~/scoop/apps/git/current/mingw64/bin/zlib1.dll_

Hope it helps

**Comment by dom96** [comment]
> using certain imports.

What imports? Is it when running Nimble or when running an application built by Nimble which uses certain libraries?

If the latter then this isn't a Nimble issue.

**Comment by vegapit** [comment]
I ran into the problem when compiling code using the NimData library. I am new to nim so not quite sure what falls under the respomsibility of the library or nimble.

**Comment by dom96** [comment]
@vegapit finding DLLs when using libraries that are "impure" (i.e. ones depending on external DLLs) is quite a common thing in Nim-land. Your advice is good but isn't a Nimble issue. I think a better place to put it might be somewhere on our website, maybe you can find a good page in https://github.com/nim-lang/website/ to put it in.

**Comment by vegapit** [comment]
Cool, it sounds like tips and tricks are very important in Nim-Land. Should I just raise the issue on the library's GitHub? I can try and find a section on the website otherwise.
