### ISSUE TITLE
nimble init uses \n instead of platform specific linebreak

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/nimble#778]
https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/init.nim

Multiline strings are used here which seem to always give `\n` no matter what the source file uses. This creates files with just \n and not \r\n on Windows.

Possible solution is `p` template mentioned [here](https://github.com/nim-lang/Nim/issues/7202).

**Comment by Araq** [comment]
Every editor by now can handle LF-only on Windows and LF-only is a much better use experience for git etc. "won't fix" for me.

**Comment by hlaaftana** [comment]
It's just a minor inconsistency with my other files that caught my attention. Specify git saying it will convert LF to CRLF made me notice. I'm not an expert so I won't defend that hard
