### ISSUE TITLE
[CI] travis always fails for nim=#hash after the 1st run

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#783]
not sure about "always" but that's my best guess: 
see https://github.com/nim-lang/nimble/pull/782 which really should be a noop.
It fails for `BRANCH=#ab525cc48abdbbbed1f772e58e9fe21474f70f07` (see .travis.yml)

![image](https://user-images.githubusercontent.com/2194784/76934442-62d4d380-68ac-11ea-802f-0b3b760a8f8d.png)

logs:
https://gist.github.com/timotheecour/1dafdee664d5f26f1551d91b473c3b94

shows (on linux, similar on other OS):

```
$ nim c -r tester
The program 'nim' is currently not installed. To run 'nim' please ask your administrator to install the package 'nim'
The command "nim c -r tester" exited with 127.
```

## note
it seems to only fail after the 1st push, perhaps because of caching: for the 1st push it doesn't use cache and works, after the 1st push it uses cache and fails

**Comment by genotrance** [comment]
I believe the cache needs to be cleared after which it will work fine.

**Comment by timotheecour** [comment]
I'm fixing it in https://github.com/nim-lang/nimble/pull/781 via `- choosenim $BRANCH` in travis, let me know if you have an alternate patch, but the one I have works

**Comment by genotrance** [comment]
You don't need a patch. The Travis script already does this. See the change history on that, I had this exact bug.

**Comment by timotheecour** [comment]
> You don't need a patch. The Travis script already does this. See the change history on that, I had this exact bug.

Could you please elaborate and explain what is your alternative fix for this issue? All I'm seeing in history is https://github.com/nim-lang/nimble/pull/773

**Comment by timotheecour** [comment]
so that fix to the gist indeed worked, see https://github.com/nim-lang/nimble/pull/781

**Comment by genotrance** [comment]
Gist has been updated.

**Comment by genotrance** [comment]
This was not required. It was fixed in the gist.

**Comment by timotheecour** [comment]
that PR has been updated after the fix i did was applied to the upstream gist, but the PR was still needed as it fixed other issues
