### ISSUE TITLE
could not import: X509_check_host

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#789]
I get the error

```
could not import: X509_check_host
```

just by running `nimble`, since the update to 1.2.0

**Comment by andreaferretti** [comment]
If it can help, I am using MacOS Sierra.

**Comment by andreaferretti** [comment]
I had a look at https://github.com/nim-lang/nimble/blob/master/changelog.markdown and for version 0.7.0, released on 30/12/2015, I read

> Significant changes include NimScript support, configurable package list URLs, a new publish command, **the removal of the dependency on OpenSSL**

which makes the above error even more baffling

**Comment by alaviss** [comment]
https://forum.nim-lang.org/t/6146#38137

Here's my forum post about it.

TL;DR: Compile `nimble` with `-d:nimDisableCertificateValidation` if you're running OpenSSL < 1.1. I'd recommend updating if possible, since any version older than 1.1 has reached EOL and won't receive security updates.

**Comment by dom96** [comment]
As I wrote in the forum, this is because dead code elimination is gone from the openssl wrapper. I still have no idea why, even despite @leorize's answer.

> which makes the above error even more baffling

It seems that at some point it came back as a dependency:

https://github.com/nim-lang/nimble/blob/master/src/nimble.nim.cfg#L5

**Comment by alaviss** [comment]
> this is because dead code elimination is gone from the openssl wrapper.

It's still there, we are just using more of openssl, that's why.

**Comment by dom96** [comment]
> It's still there, we are just using more of openssl, that's why.

Is it? I don't see it enabled for that file.

But you're right, I suppose that proc is used now anyway. I re-read what leorize wrote and now understand.

**Comment by alaviss** [comment]
> Is it? I don't see it enabled for that file.

Dead code elimination has been the default since 0.19. We were just removing old pragmas from the code base.

**Comment by andreaferretti** [comment]
If it can help, running `openssl version` gives me

```
andrea$ openssl version
OpenSSL 1.1.1e  17 Mar 2020
```

**Comment by alaviss** [comment]
@FedericoCeratto maybe you can shed some light on this?

**Comment by FedericoCeratto** [comment]
X509_check_host is imported by https://github.com/nim-lang/Nim/blob/devel/lib/wrappers/openssl.nim#L720 since https://github.com/nim-lang/Nim/commit/5b854442448af96d57135ba7328b0c21f1f80f40 and it's used to verify certificate.

X509_check_host is in OpenSSL since version 1.0.2

Perhaps in this case the OpenSSL library is not being found at all at and the error is misleading...?

The import can be disabled with `-d:nimDisableCertificateValidation`

**Comment by dom96** [comment]
Yes, @andreaferretti probably doesn't have `DYLD_LIBRARY_PATH` set correctly. `openssl` might be in your `PATH`, but you still need to set `DYLD_LIBRARY_PATH` (or get homebrew to link to dylibs for you, but I've never done that).

**Comment by andreaferretti** [comment]
@dom96 thank you, setting `DYLD_LIBRARY_PATH` was what solved the issue for me. Should I leave this open anyway? Seems a regression to me

**Comment by dom96** [comment]
Well, anything older than 1.1 is EOL according to @alaviss, so I think we have to live with this regression.

**Comment by andreaferretti** [comment]
Ok, so I am going to close it

**Comment by briteming** [comment]
@dom96 

hi.
i already set DYLD_LIBRARY_PATH:

yudeMacBook-Air:~ ym$ echo $DYLD_LIBRARY_PATH
/usr/local/lib/
yudeMacBook-Air:~ ym$ 

but here: https://github.com/xioren/uvd/issues/6 . when i ran ./uvd -h, the error still exists:
yudeMacBook-Air:~ ym$ echo $DYLD_LIBRARY_PATH
/usr/local/lib/
yudeMacBook-Air:~ ym$ cd uvd
yudeMacBook-Air:uvd ym$ ls
LICENSE		README.md	TODO.md		src
yudeMacBook-Air:uvd ym$ cd src
yudeMacBook-Air:src ym$ ls
common.nim	uvd		uvd.nim		vimeo.nim	youtube.nim
yudeMacBook-Air:src ym$ ./uvd -h
could not import: X509_check_host
yudeMacBook-Air:src ym$

how to fix it?
tks

**Comment by FedericoCeratto** [comment]
@briteming Something like https://yasar-yy.medium.com/installing-openssl-library-on-macos-catalina-6777a2e238a6 ?

**Comment by briteming** [comment]
@FedericoCeratto 
now it's ok.
tks a lot
