### ISSUE TITLE
Nimble fails with SIGILL on Mac OS

### ISSUE THREAD

**Issue by jfilby** [nim-lang/nimble#792]
I installed Nim 1.2.0 with brew on Mac OS Catalina. When I run the nimble command I get:

SIGILL: Illegal operation.

I have tried installing Nim and Nimble with choosenim (after brew uninstall nim):
curl https://nim-lang.org/choosenim/init.sh -sSf | sh

However when I run nimble the error remains.

When I build the Nimble source (latest) myself and run it in Debug mode I get:

Traceback (most recent call last)
/usr/local/Cellar/nim/1.2.0/nim/lib/pure/net.nim(457) net
SIGILL: Illegal operation.

Line 457 of net.nim is:
ERR_load_BIO_strings()

So this is possibly a problem with Nim calling an OpenSSL function?

**Comment by jfilby** [comment]
I was able to fix this by specifying v1.1 as the OpenSSL version:
nim --cc:gcc -d:debug -d:sslVersion=1.1 c -r src/nimble

**Comment by dom96** [comment]
@jfilby  Interesting. I made some fixes to openssl recently, can you grab Nim devel and see if a Nimble compiled using it works for you? (or whether it also needs the `-d:sslVersion=1.1`?)

**Comment by jfilby** [comment]
I did try with the latest Nim nightly and had the same problem if the sslVersion wasn't specified.

**Comment by jfilby** [comment]
I have tried again with the latest Nim code from Github (clone) and Nimble works without any errors.
