### ISSUE TITLE
Before/after hooks not run when srcDir specified

### ISSUE THREAD

**Issue by konradmb** [nim-lang/nimble#793]
Before/after hooks are not run when srcDir is specified. 

```nim
srcDir        = "src"
bin           = @["nimscript"]

before build:
   echo "before build"
after build:
   echo "after build"
```

Output:

```shell
$ nimble build
Verifying dependencies for nimscript@
Building nimscript/nimscript using c backend
```

When execHook() is running, it searches for .nimble file inside srcDir, but it is in the parent directory, so none of the hooks are processed.

https://github.com/nim-lang/nimble/blob/a10691bdf23cde83d87c8b7df947fa625fe96c7d/src/nimblepkg/nimscriptexecutor.nim#L19

**Comment by kdheepak** [comment]
I'm also running into the same issue.

**Comment by kdheepak** [comment]
Thanks for fixing! PR: https://github.com/nim-lang/nimble/pull/821
