### ISSUE TITLE
"nimble test -y" fails to install dep package binaries, while "nimble install -y" works

### ISSUE THREAD

**Issue by hiteshjasani** [nim-lang/nimble#801]
I'm building and testing code in docker images.  If I run `nimble install -y`, nimble will successfully install a package that has a generated binary.  However, if I run `nimble test -y`, the process will fail at the step generating the binary.  Here is an example with the timezones package, but the problem is not with timezones .... it's somewhere in nimble.

```text
Downloading https://github.com/GULPF/timezones using git
    Cloning latest tagged version: v0.5.2
  Verifying dependencies for timezones@0.5.2
 Installing timezones@0.5.2
     Error: No binaries built, did you specify a valid binary name?
##[error]Process completed with exit code 1.
```

I've made a repo to reproduce this behavior.  The repo name is no longer accurate - I started with thinking it was in the timezones package but now see that it's occurring in nimble.

* https://github.com/hiteshjasani/nim-timezones-testing-bug
* https://github.com/hiteshjasani/nim-timezones-testing-bug/runs/659138870?check_suite_focus=true

See the actual github action run to see both working and broken examples.

Essentially this will work

```sh
bash -c "nimble install -y; nimble test"
```

whereas this will fail with the error above.

```sh
bash -c "nimble test -y --verbose"
```

**Comment by genotrance** [comment]
This is the same root cause as https://github.com/nim-lang/nimble/issues/727.
