### ISSUE TITLE
expose parsed nimble/babel metadata as json

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#803]
the root cause of https://github.com/nim-lang/Nim/issues/14453 which I'm fixing in https://github.com/nim-lang/Nim/pull/14456 is that some packages eg (`nimble install ggplotnim`) still install old dependencies of some packages, where you'd get a babel file instead of nimble file.

The way I'm fixing it in https://github.com/nim-lang/Nim/issues/14453 leaks the fact that we still need to consider babel files, which can cause further incompatibilities down the road; instead, nimble should:

* dump the metadata it parsed (whether from nimble or babel) into a json file, eg `nimblemeta.json`; it already exists but is incomplete; eg it's missing `src` field which I'm needing in other context (eg see https://github.com/nim-lang/Nim/pull/14456 but other use cases)
* allow a `nimble dumpjson mypkg` command, which would be like `nimble dump` except it'd return as json, to avoid fragile parsing (we should not have adhoc formats for processing, no matter how "easy" it is to parse)
* add a path field to the `nimble dumpjson mypkg` json dump (same as output of `nimble path mypkg`

The goal of all this is to avoid re-implementing what's already implemented in nimble so we can guarantee it stays correct even if nimble evolves.

* finally, it would be nice if there's a lightweight (ie few dependencies) library solution to get the equivalent of `nimble dumpjson mypkg`, to avoid shelling out, and avoid having to `import nimble` which carries too many dependencies

## question
is parsing nimble metadata a "nimble complete" problem since you'd essentially have to run the nimble file to get the `src` fields (etc), or is there an easier way (besides `import nimble` or calling nimble binary) 

## relevant
* https://github.com/nim-lang/nimble/issues/590
* https://github.com/dom96/choosenim/issues/192#issuecomment-633935395

**Comment by dom96** [comment]
> is parsing nimble metadata a "nimble complete" problem since you'd essentially have to run the nimble file to get the src fields (etc), or is there an easier way (besides import nimble or calling nimble binary)

Well, we do already have `nimble dump` which outputs the nimble file as an ini file. So you can use that, no?

**Comment by timotheecour** [comment]
PR accepted to have a json output?
I'm happy with any command line so long there's one; candidates are:
* `nimble jsondump`
* `nimble --json dump`

json is more standard for tooling.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/nimble/pull/810

**Comment by genotrance** [comment]
This is already fixed.

**Comment by timotheecour** [comment]
@genotrance this one is still not implemented and needed:

> add a path field to the nimble dumpjson mypkg json dump (same as output of nimble path mypkg

**Comment by timotheecour** [comment]
> the other question I had remains: is nimble dump 100% accurate or can it be wrong if some logic inside foo.nimble overrides some fields (eg src)?


to answer my own question, yes, nimble dump is accurate (ie no heuristics used to determine srcDir + friends) eg:

```nim
# Package

version       = "0.1.0"
author        = "foo"
description   = "foo"
license       = "MIT"
# srcDir        = "src"

const s = "src3"
when false:
  srcDir        = "src2"
elif true:
  srcDir        = s
else:
  srcDir        = "src4"

srcDir        = srcDir & "_6"

# Dependencies

requires "nim >= 1.5.1"
```


nimble dump --json d02.nimble | jq -r .srcDir
src3_6
