### ISSUE TITLE
`nimble test` gives warnings about unused imports

### ISSUE THREAD

**Issue by sschwarzer** [nim-lang/nimble#807]
I just ran into this with `nimble test`:
```
$ choosenim show
  Selected: 1.2.0
   Channel: stable

$ nimble --version
nimble v0.11.4 compiled at 2020-05-30 16:46:40
git hash: 63695f490728e3935692c29f3d71944d83bb1e83

$ nimble test
  Executing task test in /home/schwa/sd/nim/lazytree/lazytree.nimble
/home/schwa/sd/nim/lazytree/lazytree_31480.nims(1, 8) Warning: imported and not used: 'system' [UnusedImport]
/home/schwa/sd/nim/lazytree/lazytree_31480.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
...
```

_Originally posted by @sschwarzer in https://github.com/nim-lang/nimble/issues/706#issuecomment-636357810_

**Comment by dom96** [comment]
Some people complain that there isn't enough output, others don't want to see any output. Who should I listen to? :)

**Comment by sschwarzer** [comment]
Both? ;-)

I wonder if it would be feasible to add a command line option to control/limit such compiler messages.

**Comment by dom96** [comment]
There is no way to listen to both, it's about what is default. For `nimble build` you already won't get any output unless you pass in ``--verbose`` (or ``--debug``), but people still complain :(

**Comment by sschwarzer** [comment]
> There is no way to listen to both, it's about what is default.

Sorry. What I meant by "both" was that the "verbose" and "non-verbose" mode should be possible at all. I'm not picky about what the default is. :-) I guess, for consistency it would be good to have the same default behavior regarding compiler messages for both `nimble build` and `nimble test`. Then you could allow `--verbose` and/or `--debug` also for `nimble test` to get the current behavior.

> but people still complain :(

Just to make sure, I didn't mean to "complain". My problem here is a relatively small one, and I assure you I appreciate how much time you put into all your open source projects! :-)

**Comment by Araq** [comment]
> but people still complain :(

So please listen to the people moreso. Make nimble --verbose the default, I don't see the point of "nimble build" not producing compiler messages. End users do not use nimble to install software, nimble is for programmers.

**Comment by sschwarzer** [comment]
> So please listen to the people moreso.

I wonder what "moreso" means here. Listening to every wish once more? ;-)

> Make nimble --verbose the default, I don't see the point of "nimble build" not producing compiler messages. End users do not use nimble to install software, nimble is for programmers.

I think you have a point here, this is a safe default. It's also what the compiler (sensibly) does and using the same default in `nimble build` and `nimble test` would even give consistency with the compiler as well.

As long as I get an option to suppress the hints and warnings I'm happy. :-)

By the way, my use case is that I use `nimble test` during refactoring, so sometimes there are `proc`s etc. that I don't use at the moment, but may need again. If I have failing tests, the output of the compiler about used modules and hints about unused stuff makes it more difficult to tell apart the compiler output and the test runner output. Again, for me it's only important to have the option, regardless of what the default is.

**Comment by dom96** [comment]
> Make nimble --verbose the default, I don't see the point of "nimble build" not producing compiler messages.

So whenever Nimble installs dependencies for a package and that package needs to be built you also want the compiler output to be shown?

**Comment by Araq** [comment]
> I wonder what "moreso" means here. 

I think it's wrong English but I couldn't be bothered to fix it. I'm sure you all understand what I mean.

**Comment by Araq** [comment]
> So whenever Nimble installs dependencies for a package and that package needs to be built you also want the compiler output to be shown?

I wouldn't mind. Ideally contributing to 3rd party libraries would be so simple that I can create PRs fixing the warnings. But even if this future never arrives, I don't mind verbose output.

**Comment by genotrance** [comment]
Note that `--verbose` still doesn't really print the Nim output, it just includes the Nimble verbose output. Neither does `--debug`.

Making `nimble build` print Nim output will show output for every command that calls the compiler including install. If this is not preferred then we need some tweaks to do that.

**Comment by genotrance** [comment]
I think we can close this one - by default, nimble now shows nim output with `--hints:off`. If you want more output from nim and nimble, you can use `--verbose`. There's also a `--silent` flag now that hides all output which will hide these unused imports.
