### ISSUE TITLE
Absolute paths in bin symlinks

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#808]
`NIMBLE_DIR` can not be moved/renamed because the symlinks in `NIMBLE_DIR/bin` are absolute. Moving NIMBLE_DIR around is handy in CI environments.

**Comment by genotrance** [comment]
This is easy to do on Linux but on Windows, the script shims when executed are relative to the current directory, not `~/.nimble/bin`. So relative paths will not resolve. You also cannot change current directory since the tool won't be running in the right folder.

Open to ideas on how to fix this.

**Comment by yglukhov** [comment]
If I understood your question, this shoul help: https://stackoverflow.com/questions/3827567/how-to-get-the-path-of-the-batch-script-in-windows

I.e. the shim should forward by the path relative to itself

**Comment by yglukhov** [comment]
Brilliant, thank you @genotrance
