### ISSUE TITLE
Document `nimble build` options, esp. `-d:release`

### ISSUE THREAD

**Issue by snej** [nim-lang/nimble#812]
Please document the options/flags the `nimble build` command takes. There are currently no docs that I can find; the help text just says "`[opts, ...]`", and the README just says it builds in debug mode.

Justification: Yesterday I tried to build and profile an optimized version of my code, and spent more than an hour trying to figure out why it was so slow — it looked like there was a terrible bottleneck in the Table class. See [this forum thread](https://forum.nim-lang.org/t/6444). The answer turned out to be that I didn't have an optimized build at all — **I had put `-d:release` in my nim.cfg file, where it didn't work, instead of putting it on the command line after `nimble build`**. I did this because I knew compiler flags could be put in the config file, and I had no idea what flags could be used with `nimble build`.

I know `nimble build` is used during development, and normally that implies a debug configuration, but it's not unusual to do profiling, or check binary sizes, during development too.

**Comment by SolitudeSF** [comment]
`nimble build` just forwards arguments to compiler. read `nim --fullhelp`

**Comment by Yardanico** [comment]
That's not a Nimble bug - see https://github.com/nim-lang/Nim/issues/14272

**Comment by snej** [comment]
> nimble build just forwards arguments to compiler.

Great. Then document that in the help text and the README, please.

**Comment by dom96** [comment]
> Then document that in the help text and the README, please.

PRs for this should be easy, please? :)

**Comment by genotrance** [comment]
This is now covered in the nimble docs.
