### ISSUE TITLE
Support project urls

### ISSUE THREAD

**Issue by xyb** [nim-lang/nimble#814]
Almost all modern software packages are configured to include links to various addresses related to the project. For examples:
- python
  - [pyproject.toml](https://python-poetry.org/docs/pyproject/): homepage, repository, documentation, urls(bug tracker or something else)
  - [setup.py](https://packaging.python.org/guides/distributing-packages-using-setuptools/): url, project_urls
- rust
  - [Cargo.toml](https://doc.rust-lang.org/cargo/reference/registries.html): homepage, documentation, repository
- npm
  - [package.json](https://docs.npmjs.com/files/package.json): homepage, repository, bugs

These links are helpful for users to find the resources they need. I think we should support them.

**Comment by dom96** [comment]
We do support this: https://github.com/nim-lang/packages/blob/master/packages.json#L12

**Comment by xyb** [comment]
@dom96 That's cool, but I think we should encourage everyone to define these by explicitly written into [PackageInfo](https://github.com/nim-lang/nimble/blob/63695f490728e3935692c29f3d71944d83bb1e83/src/nimblepkg/common.nim#L15-L43) and [init.nim](https://github.com/nim-lang/nimble/blob/63695f490728e3935692c29f3d71944d83bb1e83/src/nimblepkg/init.nim).
