### ISSUE TITLE
Please revert my commits

### ISSUE THREAD

**Issue by 3n-k1** [nim-lang/nimble#815]
Due to several issues I have had in the Nim community, as well as general behavior I've noticed from browsing IRC logs, I no longer wish to be associated with the Nim community or Nim projects in any way, including through the use of my code.

As such, I'd like to request that you revert the following commits: `4de05edf467497d312dc75a80dca418a591b71aa`, `491a681b5e40297852df7b4a02ee6af38c659e7b`.

This is by no means a legal threat, simply a request. I would prefer my code not be used, but I can't force you to stop using it.

Apologies for any disruption this may cause.

**Comment by 3n-k1** [comment]
Last time I tried to be as vague as I could people got upset, so here's backstory: The issues I've personally had are not the driving force here. What is the driving force is the community's refusal to be polite at all is disgusting. The IRC logs for July 1st 2020 contain multiple core contributors talking about how they think they should be "more blunt" despite their rudeness driving people away.

I don't want to be associated with that at all.

**Comment by 3n-k1** [comment]
I've been lead to believe that dom96 is in charge of this repo. Sorry Dom, you're a cool dude, but I gotta stick to my guns on this one. See [this thread](https://github.com/nim-lang/Nim/issues/14876) for the whole (ish) saga. To quote that thread:

To quote this Hackaday article: "Section 6 of the Berne Convention explains that the original author of a work, even if they have granted their rights to another entity, can object to its further use if they feel it has been utilized in a way which “would be prejudicial to his honor or reputation.” So in theory a disgruntled developer need only convince a judge that the maintainers of a project have damaged their reputation, say by publicly banning them for violating the Code of Conduct, and have a case for forcing the project to stop using their code regardless of preexisting licensing agreements."

Gonna have to make this a legal issue now, bud. Unless Araq apologizes for the community's conduct and bans transphobia, I'm getting a lawyer.

**Comment by dom96** [comment]
Done.

**Comment by Aspie96** [comment]
@void-witch 

I am not a lawyer, however:

> To quote this Hackaday article: "Section 6 of the Berne Convention explains that the original author of a work, even if they have granted their rights to another entity, can object to its further use if they feel it has been utilized in a way which “would be prejudicial to his honor or reputation.” So in theory a disgruntled developer need only convince a judge that the maintainers of a project have damaged their reputation, say by publicly banning them for violating the Code of Conduct, and have a case for forcing the project to stop using their code regardless of preexisting licensing agreements."

This could have fewer implications than you think.

First, this seems to be related to moral rights, which aren't implemented equally, if at all, across the globe.

In the US moral rights are very limited compared to Europe and I don't think they would have a problem in using your work further.

In Italy, where I live, according to an essay I read from an expert, moral rights on open source software in particular doesn't actually have strong negative effects.

In essence, I wouldn't be certain that your contributions had to be revoked for any legal reason and I would in fact believe the opposite is way more likely.

Your contributions were reverted, but you were right in not starting with a legal claim.
