### ISSUE TITLE
`nimble doc` failed with UnpackError

### ISSUE THREAD

**Issue by xyb** [nim-lang/nimble#818]
I have run into this problem with several projects, even empty projects just created:
```
nimble init # press enter to use the default values
nimble doc
```
I got:
```
options.nim(185)         get
Error: unhandled exception: Can't obtain a value from a `none` [UnpackError]
```

see also: https://github.com/nim-lang/Nim/issues/14281

**Comment by genotrance** [comment]
cc @snej

`nimble doc file.nim` expects file.nim. Running `nimble doc` without a file should raise an error. Not the above one which will get fixed but filename is required.
