### ISSUE TITLE
For "binary" JS projects, "nimble build" adds .exe extension on Windows

### ISSUE THREAD

**Issue by akavel** [nim-lang/nimble#822]
I tried to use nimble to create a package with JS backend. 

First, I tried to use "library" variant in `nimble init`. However, when I tried running `nimble build`, I got a "Nothing to build" error.

So, then I purged the directory, and tried to use the "binary" variant. I run `nimble build`, and... I got a `foobar.exe` result, which had correct (for me) *JavaScript contents*, but wrong name (`foobar.exe` instead of `foobar.js`). I also tried adding `switch("out", "foobar.js")` in my `foobar.nimble` file, but still no success, `nimble --debug build` didn't show the new switch in `nim` invocation. I have no idea what else to do to workaround this weird situation 😟

Would it be possible for nimble to emit `.js` instead of `.exe` extension when building projects with `backend = "js"`?

**Comment by genotrance** [comment]
Looks like a bug, I'll take a look - do you have a project to make it quick to reproduce?

**Comment by akavel** [comment]
Just uploaded at https://github.com/akavel/bookwin

**Comment by genotrance** [comment]
Looks like `bin` extension gets set during package parsing itself and `backend` may or may not be read by then. If not done there, it will need changes in multiple places.

This is also broken in posix - there's no extension at all. In case of `backend = "js"`, need to add `.js` extension.
