### ISSUE TITLE
nimble possibly doesn't ship w/ proper dll's (windows 7 prebuilt - 64bit)

### ISSUE THREAD

**Issue by G4MR** [nim-lang/nimble#83]
I had an issue where I would run into an issue which basically kept telling me it couldn't find ssleay32.dll or libeay32.dll

So after running into a wall I downloaded the dll's from the following:
https://code.google.com/p/openssl-for-windows/

Used the 64bit version and replaced the two files and everything fixed itself.  I could run "nimble update" without error and I could install packages without error.

os: windows 7 64bit

**Comment by dom96** [comment]
If you install Nimble 32bit and have a 64bit Nim compiler then bad things will happen. I'm guessing that's what happened?

**Comment by curlewool** [comment]
G4MR's method worked for me too as I had experienced the same issue too.

**Comment by Varriount** [comment]
This is part of the reason why we can't ship nimble in the Nim installer yet - it will work on the 32 bit version, but not with the 64 bit version. I think the best option would be for the bootstrap executable to unpack and rename the correct dll's from a directory.

**Comment by dom96** [comment]
Hopefully thanks to the removal of OpenSSL as a dependency this is no longer an issue.
