### ISSUE TITLE
Provide option to silence all non-essential output

### ISSUE THREAD

**Issue by al6x** [nim-lang/nimble#835]
Currently there's no way to silence non-essential output from the `nimble`, the code 

```
echo "Hi"
```

produces

```
$ nimble --hints:off run test
  Verifying dependencies for nim@1
      Info: Dependency on yaml@any version already satisfied
  Verifying dependencies for yaml@0.14.0
   Building nim/test using c backend
Hi
```

It's possible to silence nim with `nim c -r --hints:off test.nim` but not `nimble`

Would be nice to have an option so `nibmle` would produce only the program output, maybe something like `--quiet` so that the output will be

```
$ nimble --quiet run test
Hi
```

**Comment by genotrance** [comment]
@dom96: should `--silent` hide Nim compiler warnings as well? And do we want `-s`?
