### ISSUE TITLE
Structure for a hybrid package with two modules and binaries

### ISSUE THREAD

**Issue by sschwarzer** [nim-lang/nimble#837]
Both @c-blake and I tried to find a way to convince Nimble to install a package that has two `.nim` files where both files are supposed to be both Nim modules and binaries. In other words, both modules contain a `when isMainModule` statement.

The package in question is https://github.com/c-blake/hldiff . I had opened a [ticket](https://github.com/c-blake/hldiff/issues/1) there which contains a discussion of our so far unsuccessful attempts.

On the Nimble side, I don't know if https://github.com/nim-lang/nimble/issues/747 is somehow related. That ticket describes a different problem though.

What I'd like is a suggestion for a working package setup for `hldiff` and if possible an explanation for this setup, so we can transfer this knowledge to future packages. Once we have found a suitable setup, it'll probably make sense to update the Nimble readme to contain the necessary background information to arrive at this setup.

**Comment by dom96** [comment]
See my explanation in: https://github.com/c-blake/hldiff/issues/1#issuecomment-678832853. 

To add to that, there are efforts being planned to change how Nimble installs packages which will hopefully avoid these kinds of problems. CC @genotrance

**Comment by genotrance** [comment]
So I just tried hldiff and it works fine with no errors, I presume this specific issue can be closed. The `pkg` suffix issue is already being tracked in #308.

**Comment by sschwarzer** [comment]
> So I just tried hldiff and it works fine with no errors

Yes, hldiff was adapted to work with Nimble since I opened this ticket.

I'm still not totally happy with the current state of Nimble (see also https://github.com/c-blake/hldiff/issues/1 ), but that's a discussion for another ticket. ;-)
