### ISSUE TITLE
Fails to install on Fedora Rawhide

### ISSUE THREAD

**Issue by russel** [nim-lang/nimble#84]
I have installed Nim from the Git repository master branch. It seems to work fine in that I can compile and execute "Hello World" fine. On trying to execute the install of Nimble, all the compile and link succeeds, but the install phase fails:

>  [Linking]
> Hint: operation successful (36520 lines compiled; 3.165 sec total; 95.973MB) [SuccessX]
> /home/Checkouts/Git/Git/Nimble/src/nimble install
> could not load: libcrypto.so(|.1.0.0|.0.9.9|.0.9.8|.0.9.7|.0.9.6|.0.9.5|.0.9.4)
> Error: execution of an external program failed

I am not sure where the dependency is failing:

>  ldd src/nimble
>	linux-vdso.so.1 (0x00007fff1c387000)
>	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5ab3e04000)
>	libm.so.6 => /lib64/libm.so.6 (0x00007f5ab3afc000)
>	libc.so.6 => /lib64/libc.so.6 (0x00007f5ab3735000)
>	/lib64/ld-linux-x86-64.so.2 (0x00007f5ab402d000)

>  find /lib /usr/lib -iname "*libcrypto*"
> /usr/lib/.libcrypto.so.10.hmac
> /usr/lib/.libcrypto.so.1.0.1j.hmac
> /usr/lib/libcrypto.so.1.0.1j
> /usr/lib/libcrypto.so.10

**Comment by dom96** [comment]
This needs to be fixed in the openssl wrapper which is in the Nim repo in ``lib/wrappers/openssl.nim``. You can edit the file yourself or you can create a symlink to your libcrypto.so in ``/usr/lib/libcrypto.so.1.0.0``.
