### ISSUE TITLE
nimble build should complain when it requires `X >=N` and X has nimble develop at version < N

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nimble#854]
I was going to file a bug under inim but after investigation this is a bug in nimble:

inim nimble specifies `noise >= 0.1.4` but `nimble build` still uses noise@0.1.3, causing build errors without indication of what caused the error:

```nim
$ nimble dump noise|grep version
version: "0.1.3"

$ git clone https://github.com/AndreiRegiani/INim
$ cd INim

$ git rev-parse HEAD
89b1657444b6b4c6641b3842bc0a08606eedd175

$ grep noise inim.nimble
requires "noise >= 0.1.4"

# $ nimble develop # Error: Cannot develop packages that are binaries only. (=> https://github.com/nim-lang/nimble/issues/853)

$ nimble build
Verifying dependencies for inim@0.6.0
   Warning: The .nimble-link file is pointing to a missing file: /Users/timothee/git_clone/nim/nester/nester.nimble
      Hint: Remove '/Users/timothee/.nimble/pkgs/nester-#head' or restore the file it points to.
      Info: Dependency on cligen@>= 1.0.0 already satisfied
  Verifying dependencies for cligen@0.9.46
      Info: Dependency on noise@>= 0.1.4 already satisfied
  Verifying dependencies for noise@0.1.3
   Building inim/inim using c backend
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: inim
        ... Details:
inim.nim(351, 8) Error: undeclared identifier: 'ktCtrlX'
```

turns out it's because I had done `nimble develop` on an old clone of `noise`, which was stuck at 0.1.3:
```
find ~/.nimble/pkgs/noise-*
/Users/timothee/.nimble/pkgs/noise-#head
/Users/timothee/.nimble/pkgs/noise-#head/nimblemeta.json
/Users/timothee/.nimble/pkgs/noise-#head/noise.nimble-link
```

## proposal
nimble build should (by default) complain that nimble develop version is too old since we have `requires "noise >= 0.1.4"` and `nimble dump noise|grep version` returns 0.1.3

## related
* https://github.com/nim-lang/nimble/issues/405
* Forum reference - forum.nim-lang.org/t/6765#42065.

**Comment by c-blake** [comment]
This seems like it may relate to the behavior of `nimble` never auto-updating any `#head` install (which I think most find counter-intuitive).

**Comment by timotheecour** [comment]
related to https://github.com/nim-lang/nimble/issues/332 (and duplicates-ish https://github.com/nim-lang/nimble/issues/386)

**Comment by dom96** [comment]
IMO this will be resolved once lock files are implemented. Further complicating how Nimble manages develop/head packages is unnecessary.
