### ISSUE TITLE
Empty pkgs folder is created every time I run a nimble command

### ISSUE THREAD

**Issue by Clonkk** [nim-lang/nimble#864]
Since upgrading to nimble v0.12.0, everytime I run a nimble command, it create an empty `pkgs` folder in the current folder I'm in.

This is under Ubuntu 20.04 running on WSL2.

Important details : I added local dependencies by providing my own json file path in ~/.config/nimble/nimble.ini . Could it be related ?

**Comment by genotrance** [comment]
@dom96 - this is because of [this](https://github.com/dom96/choosenim/compare/v0.6.0...master#diff-3e2f4fa86493daebeb559e208f71ce653049abd6679c84122bce914a83e6733dR179) choosenim change. Each proxyexe calls newCliParams().

You don't see the issue if you use the older choosenim.

**Comment by genotrance** [comment]
PR with fix is here - https://github.com/dom96/choosenim/pull/235.

**Comment by genotrance** [comment]
This will be fixed in choosenim v0.7.4 which will be out soon.

**Comment by Clonkk** [comment]
Brillant. Thanks
