### ISSUE TITLE
Allow custom sections in .nimble file

### ISSUE THREAD

**Issue by cybernetlab** [nim-lang/nimble#872]
### Summary

It would be nice to allow custom section names in `*.nimble` files like it done in `package.json` for example or in another package managers.

### Description

Sometimes user libs needs to store project-specific configurations somewere. The `*.nimble` whould be the best choise.

**Comment by dom96** [comment]
can you be more specific? What configurations do you want to specify?

**Comment by cybernetlab** [comment]
Now I'm working on lib for embedded MCU's. I want to make it portable and implement functionality for several processors and use the one that is specified by user of library. Moreover as different MCU's has different pinout user need to specify pin aliases for each possible MCU. And a lot of other compile-time configuration that I want to place in one file. Now I'm using a different file (`embed.ini`) that is placed nearby `proj.nimble` and this works fine. This issue is more like a feature request. I just suggest to make `*.nimble` file behaves like it done in other package managers - allow lib developers and users to place custom info there because this file purpose is to configure entrie project.

Also it would be nice to have a way to get a project root dir wich contains `*.nimble` file from library. Now I'm using some kind of workaround/hack for this - inside macro that called by user code I get file source path and move up while not found `*.nimble`.

Thanks in advance!

**Comment by SolitudeSF** [comment]
you should use nim.cfg/config.nims for that.

**Comment by Araq** [comment]
The ``.nimble`` file is ordinary Nim code, use comments for your different sections.
