### ISSUE TITLE
Empty pkgs folder generated by nimble build

### ISSUE THREAD

**Issue by ArMour85** [nim-lang/nimble#876]
Hello.

Since nimble version `0.12.0` a new empty folder named `pkgs` is generated when I build with nimble.
I don't know waht it's for because it is always empty.

We can reproduce this with a new binary project, the `hello world` exe.

Nim and nimble version:
```
> nim --version
Nim Compiler Version 1.2.8 [Windows: amd64]
Compiled at 2020-10-26
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release

> nimble  --version
nimble v0.12.0 compiled at 2020-10-26 15:00:09
git hash: couldn't determine git hash
```

**Comment by ArMour85** [comment]
I can reproduce this bug only in Windows and also with Nim version 1.4.0.

**Comment by xflywind** [comment]
https://github.com/nim-lang/nimble/issues/864

**Comment by ArMour85** [comment]
OK for me. I reinstalled all and now it's good.
