### ISSUE TITLE
can not download packages.json

### ISSUE THREAD

**Issue by foisonocean** [nim-lang/nimble#884]
I can not use nimble at all since it can not be initialized, because it can not download packages.json.

![CleanShot 2020-12-23 at 15 10 32](https://user-images.githubusercontent.com/15059605/102970294-384a3200-4532-11eb-8c19-6a0ba3d53ff3.png)

My network is OK, downloading packages.json via `curl` works fine.

![CleanShot 2020-12-23 at 15 14 14](https://user-images.githubusercontent.com/15059605/102970360-5748c400-4532-11eb-8690-34a28e3a4d73.png)

**Comment by dom96** [comment]
OS? Nimble version? Also you can try with  `--debug`, might give more info.

**Comment by foisonocean** [comment]
I just solved this by using a VPN, so it's probably still a network issue.
