### ISSUE TITLE
Compiler options for `nimble run`

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/nimble#889]
I did not find a way to pass compiler options (like `--assertions:off` for example) to `nimble run`, instead the options get passed to the executable.

`nimble --help` says the following;
```
Builds and runs a package.
Binary needs to be specified after any
compilation options if there are several
binaries defined. Any flags after the binary
or -- arg are passed to the binary when it is run.
```
This implies to me that `nimble run <compiler options> <executable name>` or `nimble run <compiler options> --` should work, but they don't.

Is there anything I missed, that allows me to directly pass compiler options via `nimble run`? Or is this a bug?

**Comment by dom96** [comment]
You should be able to see what command is run if you pass `--debug`.

It's quite possible this is a bug, but we do have a bunch of tests for `nimble run`: https://github.com/nim-lang/nimble/blob/master/tests/tester.nim#L708. Can you check out how they pass the args?

**Comment by konsumlamm** [comment]
Ok, so it works if you pass the options *before* the `run`, so `nimble <compiler options> run`.

However, I believe this is actually a bug, at least the cases I would expect to work don't have any test cases i could find. For example (using `testing` as the excutable name):
* `nimble run --assertions:off testing <executable arguments>`
* `nimble run --assertions:off -- <executable arguments>`

**Comment by konsumlamm** [comment]
After looking at this more in-depth, the current behaviour seems to be intended.

However, it is inconsistent with `nim r` (where everything before the file name is used as compile flag) and for example Rust's [`cargo run`](https://doc.rust-lang.org/cargo/commands/cargo-run.html) also use everything before `--` as compile flags.

The change itself wouldn't be difficult either, one just needs to change [a few lines](https://github.com/nim-lang/nimble/blob/2e78ff328aa2515e4e15a724c56a96db1e4ae973/src/nimblepkg/options.nim#L358-L359) and update the documentation.

**Comment by dom96** [comment]
If it's consistent with `nim r` then go for it, maybe we can also ping whoever implemented this though in case they have any objections :)

**Comment by konsumlamm** [comment]
> maybe we can also ping whoever implemented this though in case they have any objections :)

[Seems like you're the person that implemented it](https://github.com/nim-lang/nimble/commit/c834faf60e1dbdd8ae46456e1fb2dc2db05e4e91#diff-8ef7f6ded95bfc175cb8e9ea5ae1f7643e40e3dfd3747072d763b55efbf524ccR291-R294) ;)

**Comment by dom96** [comment]
hah, 2 years is a long time.

> However, it is inconsistent with nim r (where everything before the file name is used as compile flag)

Looking at the test cases it appears that this is the behaviour of `nimble run`? Am I missing something?

In any case, as long as it's consistent with `nim c -r foo.nim` then I don't mind (I'm not actually sure what `nim r` is, if it is a thing then it's not used by many so I wouldn't use it as an example).

**Comment by konsumlamm** [comment]
> Looking at the test cases it appears that this is the behaviour of `nimble run`? Am I missing something?

The example program
```nim
# test.nim
assert false
```
runs fine with `nim r --assertions:off test.nim` and `nim c -r --assertions:off test.nim`, however, it throws an exception with `nimble run --assertions:off test` (in a project where `test` refers to `test.nim`).

> In any case, as long as it's consistent with `nim c -r foo.nim` then I don't mind (I'm not actually sure what `nim r` is, if it is a thing then it's not used by many so I wouldn't use it as an example).

I checked and `nim c -r` has the same behaviour as `nim r` (at least for passing command line parameters).

**Comment by konsumlamm** [comment]
One thing to note though, is that with this change, `nimble run <arguments>` (where the arguments are supposed to be passed to the program) wouldn't work anymore, it would need to be changed to `nimble run -- <arguments>`.
