### ISSUE TITLE
[Feature request] API to install and check installed nimble package

### ISSUE THREAD

**Issue by Clonkk** [nim-lang/nimble#892]
I haven't seen anything close mentionned in the doc but being able to install package from Nim itself and check version of installed package would be useful to have. 

Julia have something similar with Pkg.

**Comment by dom96** [comment]
Can you elaborate? What do you want to do exactly?

**Comment by Clonkk** [comment]
The use case I had in mind was when you use Nim from a REPL (such as inim)and need a way of installing package from inside the REPL.

**Comment by dom96** [comment]
I would say that the REPL should integrate with Nimble in that case, Nimble is already a package that can be imported but I wouldn't go that route, instead `exec(nimble install)` is a better option.

In any case, I don't think there is anything to do here for Nimble so closing.

**Comment by Clonkk** [comment]
> I would say that the REPL should integrate with Nimble in that case, Nimble is already a package that can be imported but I wouldn't go that route, instead `exec(nimble install)` is a better option.


So someone making a Jupyter notebook should just execute shell command by hand or read through Nimble code sources (since there's no api documented) to import a package ? That feels like treating REPL as second class citizens.
