### ISSUE TITLE
--shallow-submodules "breaks" packages

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/nimble#899]
Latest nimble fails to install `bearssl` package because of `--shallow-submodules` checkout, introduced in #886
```
nimble install bearssl
```
```
Downloading https://github.com/status-im/nim-bearssl using git
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: /home/.../nimble/src/nimble.nim(1231) nimble
        ... /home/.../nimble/src/nimble.nim(1159) doAction
        ... /home/.../nimble/src/nimble.nim(440) install
        ... /home/.../nimble/src/nimblepkg/download.nim(259) downloadPkg
        ... /home/.../nimble/src/nimblepkg/download.nim(208) doDownload
        ... /home/.../nimble/src/nimblepkg/download.nim(53) doClone
        ... /home/.../nimble/src/nimblepkg/tools.nim(40) doCmd
        ... Execution failed with exit code 1
        ... Command: git clone --recursive --shallow-submodules --depth 1 https://github.com/status-im/nim-bearssl /tmp/nimble_27915/githubcom_statusimnimbearssl
        ... Output: Cloning into '/tmp/nimble_27915/githubcom_statusimnimbearssl'...
        ... Submodule 'bearssl/csources' (https://www.bearssl.org/git/BearSSL) registered for path 'bearssl/csources'
        ... Cloning into '/tmp/nimble_27915/githubcom_statusimnimbearssl/bearssl/csources'...
        ... error: Server does not allow request for unadvertised object dda1f8a0c46e15b4a235163470ff700b2f13dcc5
        ... Fetched in submodule path 'bearssl/csources', but it did not contain dda1f8a0c46e15b4a235163470ff700b2f13dcc5. Direct fetching of that commit failed.
Error: execution of an external program failed: '/home/yglukhov/Projects/nimble/src/nimble install bearssl'
```

It seems that `--shallow-submodules` git feature is pretty fragile in that regards. Possible solutions:
- Retry cloning without `--shallow-submodules` but that just feels too convoluted.
- A better option is to remove this option from nimble entirely and let library authors manage that. Submodule shallowness can be configured from within the supermodule.

**Comment by stefantalpalaru** [comment]
`--shallow-submodules` assumes all submodules point to a branch HEAD, doesn't it? That would be the only way to get the target commit through a shallow clone.

**Comment by greenfork** [comment]
I didn't know you could control shallowness from supermodule when I proposed the patch. That definitely sounds better.

Could you explain what exactly happens there, why does it fail to find `dda1f8a0c46e15b4a235163470ff700b2f13dcc5` commit? Does it always clone only HEAD?

**Comment by yglukhov** [comment]
> Does it always clone only HEAD?

Not sure, but yeah, I believe @stefantalpalaru is right, or at least close.

**Comment by dom96** [comment]
That's definitely non-intuitive. I don't suppose there is a way to shallow clone the submodules at the commit specified?

**Comment by yglukhov** [comment]
> I don't suppose there is a way to shallow clone the submodules at the commit specified?

I'm not aware of any.
