### ISSUE TITLE
[Enhancement request]: Stick to patchable version: requires ^= 0.1.0

### ISSUE THREAD

**Issue by marcomq** [nim-lang/nimble#907]
Currently, nimble only supports `requirements >= version` and `requirements == version` according to the documentation.

Python has some easy requirements.txt [options ](https://pip.pypa.io/en/latest/reference/pip_install/#example-requirements-file) for pip, while node/npm packages.json has some even more complex [syntax](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies). 

Usually, when trying out python libraries or examples, the most used seems to be the ` == version` operator but there is also a less used but available `~=` operator that only installs patches.
For node/npm, tjhe default seems to be a `^` prefix, which always installs the latest patch/minor version. A  `~` is also available in node but not used that much.
There is an automatic `npm update` command to automatically change the `packages.json`  to the latest version of packages, even for those with `^`  or `~` prefix.

For nim, there is mostly a `>=` operator available, and there is also a new `==` operator for nim versions >= 1.2.
I also found a Nim syntax for requirements in the latest code `>= 1.5 & <=1.8` in /src/nimblepkg/version.nim:parseVersionRange that also seems to work but it is undocumented yet.

I would prefer a simpler npm like syntax:  `^= 1.1.1` which may be converted internally to `>= 1.1.1 & < 2.0.0`  or  `~= 1.1.1` which might be converted to `>= 1.1.1 & < 1.2.0` 
I haven't seen `&` in nim yet with `and` meaning and this actually seems to be a bit complicate for everyday usage.

**Comment by dom96** [comment]
sure, AFAIK we've got other issues for this, but I'll keep this open. It would be nice to get some sugar for an operator that means "Give me the semver compatible version"

**Comment by marcomq** [comment]
Cool. I will add a PR for this.

**Comment by dom96** [comment]
Fixed via #908.
