### ISSUE TITLE
nimble sometimes not detecting new versions

### ISSUE THREAD

**Issue by xioren** [nim-lang/nimble#909]
I have had this happen several times and am not sure if the problem is with me or nimble. The current version of my repo is v0.1.4 and is tagged as such yet nimble still installs v0.1.3. The .nimble file is up to date. Any ideas?

https://github.com/xioren/rn

**Comment by dom96** [comment]
https://github.com/xioren/rn/blob/v0.1.4/rn.nimble#L3

**Comment by xioren** [comment]
thanks
