### ISSUE TITLE
Compiler options for `nimble run` are not passed (again)

### ISSUE THREAD

**Issue by shunf4** [nim-lang/nimble#923]
Reproduction: 
[nimble-run-repro.zip](https://github.com/nim-lang/nimble/files/6721407/nimble-run-repro.zip)

```nim
# assert_fail.nim
assert false
```

```nim
# nimble_run_repro.nimble
# Package

version       = "0.1.0"
author        = "shunf4"
description   = "Nimble run with compilation arguments reproduction"
license       = "MIT"
srcDir        = "src"
bin           = @["assert_fail"]
```

`nimble --assertions:off run assert_fail` succeeds (which is expected), while
`nimble run --assertions:off assert_fail` throws (which is _not_ expected),

i.e. #889 appears again.

Tested with nimble built with the latest commit (752f88e).

**Comment by shunf4** [comment]
The patch for 752f88e solves the issue:
```
diff --git a/src/nimblepkg/options.nim b/src/nimblepkg/options.nim
index ac37bbc..eca0ede 100644
--- a/src/nimblepkg/options.nim
+++ b/src/nimblepkg/options.nim
@@ -518,14 +518,16 @@ proc parseMisc(options: var Options) =
 proc handleUnknownFlags(options: var Options) =
   if options.action.typ == actionRun:
     # actionRun uses flags that come before the command as compilation flags.
-    options.action.compileFlags =
+    options.action.compileFlags.add(
       map(options.unknownFlags, x => getFlagString(x[0], x[1], x[2]))
+    )
     options.unknownFlags = @[]
   elif options.action.typ == actionCustom:
     # actionCustom uses flags that come before the command as compilation flags
     # and flags that come after as run flags.
-    options.action.custCompileFlags =
+    options.action.custCompileFlags.add(
       map(options.unknownFlags, x => getFlagString(x[0], x[1], x[2]))
+    )
     options.unknownFlags = @[]
   else:
     # For everything else, handle the flags that came before the command

```

But I am not sure if it is good enough.

**Comment by dom96** [comment]
We've got many tests for this, I guess this is argument ordering that we didn't consider (or maybe there is a reason it isn't allowed, judging by the comment in the code it seems likely, but maybe we should still allow it). Please create a PR and tests :)

**Comment by shunf4** [comment]
Yeah from comments in code it seems this is by intention (`# actionRun uses flags that come before the command as compilation flags.`), but it contradicts with what is said in readme (it 's only required that compilation flags come before the binary).

In thread #889 it seems like you and konsumlamm reached a consensus and agreed that this should change, but konsumlamm did not change this in #896 (only the delimiter `--` was introduced).

I will look at the tests later.

**Comment by shunf4** [comment]
https://github.com/nim-lang/nimble/blob/752f88ef8e4c1ed098963d824e02e9acd261fc51/tests/tester.nim#L780-L807

I think the two tests are not good enough? `--debug` is not a compilation flag. It's for nimble.

**Comment by dom96** [comment]
> I think the two tests are not good enough?

Feel free to add more tests.

**Comment by konsumlamm** [comment]
> The patch for [752f88e](https://github.com/nim-lang/nimble/commit/752f88ef8e4c1ed098963d824e02e9acd261fc51) solves the issue:
> 
> ```
> diff --git a/src/nimblepkg/options.nim b/src/nimblepkg/options.nim
> index ac37bbc..eca0ede 100644
> --- a/src/nimblepkg/options.nim
> +++ b/src/nimblepkg/options.nim
> @@ -518,14 +518,16 @@ proc parseMisc(options: var Options) =
>  proc handleUnknownFlags(options: var Options) =
>    if options.action.typ == actionRun:
>      # actionRun uses flags that come before the command as compilation flags.
> -    options.action.compileFlags =
> +    options.action.compileFlags.add(
>        map(options.unknownFlags, x => getFlagString(x[0], x[1], x[2]))
> +    )
>      options.unknownFlags = @[]
>    elif options.action.typ == actionCustom:
>      # actionCustom uses flags that come before the command as compilation flags
>      # and flags that come after as run flags.
> -    options.action.custCompileFlags =
> +    options.action.custCompileFlags.add(
>        map(options.unknownFlags, x => getFlagString(x[0], x[1], x[2]))
> +    )
>      options.unknownFlags = @[]
>    else:
>      # For everything else, handle the flags that came before the command
> ```
> 
> But I am not sure if it is good enough.

That looks good to me, it should be enough to fix the issue.

> In thread #889 it seems like you and konsumlamm reached a consensus and agreed that this should change, but konsumlamm did not change this in #896 (only the delimiter `--` was introduced).

It was supposed to change, that was the whole point of my PR. `--` already existed before, I just changed how it works.

> https://github.com/nim-lang/nimble/blob/752f88ef8e4c1ed098963d824e02e9acd261fc51/tests/tester.nim#L780-L807
> 
> I think the two tests are not good enough? `--debug` is not a compilation flag. It's for nimble.

Ye, I didn't realize that `--debug` is special cased when writing the tests. It should be replaced by some other flag.
