### ISSUE TITLE
Don't assume `git submodule --depth 1` works

### ISSUE THREAD

**Issue by girst** [nim-lang/nimble#926]
nimble tries to update submodules with the `--depth 1` flag. This flag is not available on e.g. RHEL / CentOS 7, which means it is impossible to fetch and compile a project('s dependencies) on those systems. I'd suggest checking `git --version` before attempting to use this flag.

```
 Installing https://github.com/iffy/asynctools@#pr_fix_for_latest
Downloading https://github.com/iffy/asynctools using git
       Tip: 12 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: git submodule update --recursive --depth 1
        ... Output: usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
        ...    or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
        ...    or: git submodule [--quiet] init [--] [<path>...]
        ...    or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
        ...    or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
        ...    or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
        ...    or: git submodule [--quiet] foreach [--recursive] <command>
        ...    or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
~ % git --version
git version 1.8.3.1
```

as you can see, when git 1.8.3, the version available in rhel/centos7, is used, specifying `--depth 1` causes an error. As luck would have it, the required functionality was introduced just after that version in 1.8.4. 

this issue was introduced in commit https://github.com/nim-lang/nimble/commit/30a322c93d54855e3fa4f37ee008c5e859031f57.

**Comment by dom96** [comment]
From what I can see that Git version is from 2013: https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.3.txt. I think supporting such an old version should be outside Nimble's scope.

**Comment by dom96** [comment]
Sorry but I don't think we'll be fixing this one. You'll need to update your git.
