### ISSUE TITLE
SIGILL: Illegal operation

### ISSUE THREAD

**Issue by lua-rocks** [nim-lang/nimble#931]
This is my first introduction to Nim so excuse me if I am doing something wrong.

My OS is Xubuntu 20.04.

I downloaded latest [pre-built binaries](https://nim-lang.org/install_unix.html), unpacked them and linked ./bin directory to /bin

I've tried to run helloworld. It compiles and runs just fine!

But when I trying to install something I get errors (no matter with sudo or not)

For example:

```fish
> nimble install nico
    Prompt: No local packages.json found, download it from internet? [y/N]
y
    Answer: Downloading Official package list
SIGILL: Illegal operation.
```

Also I tried to just run `install.sh` earlier but this script doesn't create nimble binaries at all. I have no idea why.

I don't want to install Nim from official repositories because it's super old there.

And I don't want to build it from source because it's not fun 😺

**Comment by Araq** [comment]
To build from source use "koch nimble". The SIGILL might be caused by an outdated OpenSSL library.

**Comment by lua-rocks** [comment]
@Araq  Ok. Thank you! I downloaded the sources and built everything following this instruction:

```sh
sh build.sh
bin/nim c koch
./koch boot -d:release
./koch tools
```

Now I'm getting new errors:

```sh> nimble install nico
Downloading https://github.com/ftsf/nico using git
   Warning: Package 'nico' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nico', but file 'main.nim' is in a directory named 'exampleApp/src' instead. This will be an error in the future.
      Hint: If 'exampleApp/src' contains source files for building 'nico', rename it to 'nico'. Otherwise, prevent its installation by adding `skipDirs = @["exampleApp/src"]` to the .nimble file.
  Verifying dependencies for nico@0.4.2
      Info: Dependency on sdl2_nim@>= 2.0.10.0 already satisfied
  Verifying dependencies for sdl2_nim@2.0.14.2
      Info: Dependency on winim@>= 3.6.0 already satisfied
  Verifying dependencies for winim@3.6.1
      Info: Dependency on x11@>= 1.1 already satisfied
  Verifying dependencies for x11@1.1
      Info: Dependency on gifenc@>= 0.1.0 already satisfied
  Verifying dependencies for gifenc@0.1.1
      Info: Dependency on nimPNG@>= 0.3.1 already satisfied
  Verifying dependencies for nimPNG@0.3.1
      Info: Dependency on zippy@>= 0.5.9 already satisfied
  Verifying dependencies for zippy@0.6.2
 Installing nico@0.4.2
   Building nico/nicosynth using c backend
/tmp/nimble_11763/githubcom_ftsfnico/nico/controller.nim(2, 14) Error: cannot open file: sdl2/sdl
       Tip: 21 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: nico
        ... Execution failed with exit code 1
        ... Command: /opt/nim/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.4.2 --path:/home/luarocks/.nimble/pkgs/sdl2_nim-2.0.14.2 --path:/home/luarocks/.nimble/pkgs/winim-3.6.1 --path:/home/luarocks/.nimble/pkgs/x11-1.1 --path:/home/luarocks/.nimble/pkgs/gifenc-0.1.1 --path:/home/luarocks/.nimble/pkgs/nimPNG-0.3.1 --path:/home/luarocks/.nimble/pkgs/zippy-0.6.2 --hints:off -o:/tmp/nimble_11763/githubcom_ftsfnico/nicosynth /tmp/nimble_11763/githubcom_ftsfnico/nicosynth.nim
```

I have all sdl packages installed (1.* and 2.*), including -dev.

**Comment by lua-rocks** [comment]
I understand that this error is probably irrelevant, but I get the feeling that my system is just not supported :(

**Comment by dom96** [comment]
Pretty bad that the pre-built binaries aren't working :/

Anyway, your new error isn't related to your system, nico is broken because of a breaking change in the sdl2_nim package (https://github.com/Vladar4/sdl2_nim/issues/35#issuecomment-900532871). CC @ftsf

**Comment by ftsf** [comment]
@lua-rocks nico is now updated to work with the changes in sdl2_nim, if you continue to have errors installing/using nico please create an issue in the nico repo https://github.com/ftsf/nico/ thanks!

**Comment by lua-rocks** [comment]
@ftsf I'll check it tomorrow. Thank you so much! :heart:
