### ISSUE TITLE
[Feature Request] local/per-project package installation support (like venv in Python)

### ISSUE THREAD

**Issue by evan0greenup** [nim-lang/nimble#933]
If install all the dependency packages under home directory, it will make the packages a lot.

Plus, some times, need to link the relevant packages for other project to the current project for testing and debugging purpose, but the user won't want to apply it to all the other project.

Use mechanism like "virtualenv in python" can solve this problem. 

Since `Nim` is inspired from `Python`, It would be nice to provide more flexibility and control to user.

**Comment by dom96** [comment]
We support this via local deps: https://github.com/nim-lang/nimble/pull/852.
