### ISSUE TITLE
Allow installing packages from urls

### ISSUE THREAD

**Issue by flaviut** [nim-lang/nimble#94]
Ideally, I would be able to use these two commands:

```console
$ nimble install 'https://github.com/flaviut/foo.git'
$ nimble install 'git@github.com:flaviut/foo.git'
```

**Comment by dom96** [comment]
This should already work, remove the quotes perhaps?

**Comment by flaviut** [comment]
Removing the quotes does work for `https://github.com/flaviut/foo.git`, although it is unexpected behavior. Typically, quotes have no effect except to prevent the shell from interpreting certain characters specially.

`git@github.com:flaviut/foo.git` still does not work though.

**Comment by dom96** [comment]
You likely need to prefix the second URL with ``git://``

**Comment by dom96** [comment]
Shouldn't the shell get rid of the quotes?

**Comment by flaviut** [comment]
> Shouldn't the shell get rid of the quotes?

You're right, I may have made a mistake while testing this:

```c
#include <stdio.h>

int main(int argv, char** args) {
  for(int i = 0; i < argv; i++)
    printf("%s\n", args[i]);
  return 0;
}
```
```console
$ ./a.out 'asdasd'
./a.out
asdasd
```
