### ISSUE TITLE
"Error: Package in packages.json file does not contain a description field" on Manjaro Linux

### ISSUE THREAD

**Issue by ziotom78** [nim-lang/nimble#947]
Hello, I have just installed Nim and Nimble on a new Manjaro Linux machine using the binaries provided by the distribution (`pacman -Syu nim nimble`):

```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.4
Codename:	Pahvo
$ nim --version
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-06-07
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
$ nimble --version
nimble v0.13.1 compiled at 2021-04-26 22:06:28
git hash: couldn't determine git hash
```

Running `nimble refresh` works fine, but then I cannot run `numble list` nor `nimble search`:

```
$ rm -rf .nimble
$ rm -rf .config/nimble
$ nimble refresh
Downloading Official package list
    Success Package list downloaded.
$ nimble list
     Error: Package in packages.json file does not contain a description field.
$ nimble search foo
     Error: Package in packages.json file does not contain a description field.
$ ls .nimble
packages_official.json	packages_temp.json  pkgs
$ ls .config/nimble
ls: cannot access '.config/nimble': No such file or directory
```

Yet I can see that `nim refresh` properly created the folder `$HOME/.nimble` and populated it with some files.

The only reference to this error message is in an [existing issue](https://github.com/nim-lang/nimble/issues/123) that dates back to 2015, but it was closed as solved. May you please suggest me some more test to inspect what is causing the problem?

**Comment by pietroppeter** [comment]
I can confirm that running a `nimble refresh` and a `nimble search hi` on an existing Nim installation on Windows (nimble 0.13.1, nim 1.4.6), I see the same error. Some time in the past a package without description must have slipped in packages.json.

**Comment by pietroppeter** [comment]
I tested with the following short program both `packages_official.json` and `packages_temp.json` in my `.nimble` dir and I could not find any package without description:

```nim
import json

let packages = readFile("packages_official.json").parseJson()  # test also packages_temp
assert packages.kind == JArray

for package in packages:
  assert package.kind == JObject
  if "description" not_in package and "alias" not_in package:
    echo package
```

**Comment by pietroppeter** [comment]
ok, I found out the issue. package `zfdbms` has a description field but it is the empty string and the notion of required in nimble is to have a description field with a non empty string.

refs:
* nimble required function: https://github.com/nim-lang/nimble/blob/v0.13.1/src/nimblepkg/packageinfo.nim#L112
* zfdbms PR https://github.com/nim-lang/packages/pull/2012
* note that zfdbms does not show in GitHub interface in package.json file (the file is truncated, we have probably reached some limit)

**Comment by pietroppeter** [comment]
I can make a PR to package.json to fix the missing description (taking the about field of GitHub package: "Simple database generator, connector and query tools."). in principle a better package check should be enforced (even though we might need to remove it later on when nimble 0.14 is out with description not required anymore)

**Comment by dom96** [comment]
Thank you so much @pietroppeter for looking into this and fixing it :)

**Comment by pietroppeter** [comment]
You are welcome :) I can confirm that running `nimble refresh` again, `nimble search` and `nimble list` are working again

**Comment by ziotom78** [comment]
Thank you @pietroppeter !
