### ISSUE TITLE
`nimble install` doesn't respect newly downloaded `packages.json`

### ISSUE THREAD

**Issue by avahe-kellenberger** [nim-lang/nimble#953]
When a package is not found,
and prompted to download a new list from the internet,
the package will still be reported as "not found'
(even if it was in the newly downloaded list).

I experienced this with `chipmunk7`,
which was recently added to the list.

`nimble install chipmunk7` worked the second time I tried the command.

**Comment by xflywind** [comment]
It appeared in Nim repo CI too.
```
nimble install -y --nimbleDir:build/deps jester@#head
Downloading https://github.com/dom96/jester using git
  Verifying dependencies for jester@#head
 Installing httpbeast@>= 0.4.0
    Prompt: httpbeast not found in any local packages.json, check internet for updated packages? -> [forced yes]
Downloading Official package list
    Success Package list downloaded.
       Tip: 12 messages have been suppressed, use --verbose to show them.
     Error: Package not found.
FAILURE

cmd: echo runCI failed
runCI failed
```

**Comment by avahe-kellenberger** [comment]
I just tested this again and had the same issue `nimble v0.13.1 compiled at 2022-05-05 01:16:54` with the new `array2d` package
