### ISSUE TITLE
Underscore in package name not shown in package directory

### ISSUE THREAD

**Issue by TheSimpleZ** [nim-lang/nimble#978]
I tried installing this package: https://nimble.directory/pkg/simpleparseopt

According to the linked page, I should install it using `nimble install simpleparseopt`. So far so good.

Now I tried using the package by importing it using `import simpleparseopt`. However, that failed. 
The readme does not mention how I should import it. But I noticed that the title in the readme was different from the package name. 
The readme says simple_parseopt. Once I tried `import simple_parseopt`, everything worked fine.

I thought there might be some configuration error on their side.
So I also tried creating my own package and published it to the nimble directory: https://nimble.directory/pkg/conventionalsemver

Same deal. My package name is conventional_semver. [The PR submitted to publish the package](https://github.com/nim-lang/packages/pull/2116/files#diff-c508188958b68ce78976e33b66f47762f45f4a7bc134c5781cc38ee9ee81589aR24777) also has an underscore. 

But when looking at the nimble directory, the underscore is gone. I couldn't really find any mention of this behavior in the nimble readme. Is there a bug, or is it generally recommended to avoid snake_case for package names?

**Comment by Araq** [comment]
Sounds like a nimble.directory bug. Ping @FedericoCeratto

**Comment by dom96** [comment]
Yep, report here https://github.com/FedericoCeratto/nim-package-directory
