### ISSUE TITLE
`nimble build` doesn't allow compiler options

### ISSUE THREAD

**Issue by adigitoleo** [nim-lang/nimble#980]
It seems like `nimble test` respects `outdir` but not `nimble build`, which is a bit confusing.

config.nims:
```
switch("outdir", "build/bin/")

```

nimble v0.13.1 compiled at 2021-04-26 22:06:28

**Comment by adigitoleo** [comment]
I have found that in fact `nimble build` is just not passing any compiler options through. Try any of `nimble build -d:release` or `nimble build --outdir:foo/bar` etc.

This is contrary to what `nimble --help` says:

    build        [opts, ...] [bin]  Builds a package. Passes options to the Nim
                                  compiler.

**Comment by adigitoleo** [comment]
The relevant line in `test` seems to be:
https://github.com/nim-lang/nimble/blob/master/src/nimble.nim#L1393

Maybe something like that can be added to the `build` proc.

**Comment by dom96** [comment]
> I have found that in fact nimble build is just not passing any compiler options through

Are you sure? IIRC we've got tests for this. You can do `nimble build -d:release --debug` to see what Nim command Nimble is running.

**Comment by adigitoleo** [comment]
Ah, looks like the command is correct. Not sure, thought I saw "debug build" last time.

With `--outdir`, I guess I just don't understand how it works. I've got the switch in my .nims as above, but it's still putting the binary in the current directory because of an automatic `-o:/path/to/current/dir/out` flag. With `nim c src/foo.nim` it works. Should I just override the deault build target?

**Comment by dom96** [comment]
Nimble has its own out dir handling and doesn't check for an explicit `outdir`. You can change where it puts stuff using `binDir` (https://github.com/nim-lang/nimble#nimble-reference)
