### ISSUE TITLE
nimble fails to run - could not load: (ssleay32|libssl32).dll

### ISSUE THREAD

**Issue by Nuclearfossil** [nim-lang/nimble#99]
Tried installing nimble from the packaged build for Windows (Win 7).  Also tried building manually.  Each time I try running nimble, I get the following:

C:\Users\Ash\.nimble\pkgs\nimble-0.6.0>nimble.exe update
could not load: (ssleay32|libssl32).dll

Any ideas?

**Comment by Varriount** [comment]
Those dll's are for openssl and  libressl. You'll need to download or build one of those libraries. The 32-bit version of the openssl dll is packaged with the latest Nimble release. Make sure that the dll's are in your PATH environment variable.

**Comment by Nuclearfossil** [comment]
Sorry for the delay.  Copied the files into C:\Nim, which is in the path, still no go.

**Comment by dom96** [comment]
You're likely using 32 bit DLLs with a 64 bit Nimble binary. Compile Nimble using a 32 bit compiler and it should then work.

**Comment by chrisheckey** [comment]
binaries here worked for me:
https://indy.fulgan.com/SSL/

**Comment by Enamex** [comment]
Still not working for me. I put the .dll in System32 folder and they already came with the Nim installation in the bin folder (which is in fact in PATH).

Any ideas?

**Comment by dom96** [comment]
@Enamex Does putting the DLLs beside nimble.exe work?

**Comment by dom96** [comment]
OpenSSL is no longer a dependency (unless you want to download your package lists using HTTPS). The default package URL (defined [here](https://github.com/nim-lang/nimble/commit/835157ce34798ce11ba5517be97426738d6ad230#diff-0d0f411fbc50c3abb4018d6c815a191cR27)) is non-https.

**Comment by exts** [comment]
Looks like it's required again

**Comment by dom96** [comment]
Yep. Afraid so.

**Comment by exts** [comment]
Why's it required? I just manually removed it from the cloned folder and I'm not having to use the dll's anymore.

**Comment by dom96** [comment]
Two reasons:

* No SSL breaks: https://github.com/nim-lang/nimble/issues/209.
* Package list updates need to happen over SSL to prevent tampering by malicious users.
