### ISSUE TITLE
nimble error

### ISSUE THREAD

**Issue by BLAZE1960** [nim-lang/nimble#991]
choosenim
Nim 1.6.4
OS: Arch Linux
Kernel: linux-zen 5.16.9

![Screenshot_20220216_171126](https://user-images.githubusercontent.com/86563817/154282213-82e49535-5754-47b0-8249-d074865fcbf5.png)

**Comment by dom96** [comment]
nimble version?

**Comment by BLAZE1960** [comment]
nimble v0.13.1 compiled at 2022-02-09 01:06:01
